-- ============================================================================
-- seed-cooking-guides-breakfast-2.sql — authored cooking guides, BREAKFAST archetype (batch 2, 15 recipes)
-- ----------------------------------------------------------------------------
-- Git source of truth for content authored directly in the DB (instructions jsonb + recipe_kind
-- per recipe id). Content UPDATEs only — NOT schema. Idempotent (matches by id); re-runnable.
-- Same pattern + schema as the other seed-cooking-guides-*.sql files.
--
-- Regenerate from the live DB (swap the id-prefix filter for the batch):
--   select string_agg(format('-- %s', name) || E'\n' ||
--     format('update recipes set recipe_kind=%L, instructions=%L::jsonb where id=%L and user_id is null;',
--       recipe_kind, instructions::text, id::text), E'\n\n' order by name)
--   from recipes where user_id is null and instructions is not null and id::text like any(array['e22b5583%', ...]);
--
-- Progress: 164 / 299 cooking guides authored (55%) — salads 26 + smoothies 6 + wraps 5 + soups 15 + bowls 77 + originals 5 + breakfast 30 (batches 1-2).
-- ============================================================================

begin;

-- Hard Boiled Eggs with Hummus
update recipes set recipe_kind='assembly', instructions='{"reheat": "Serve cold.", "storage": "Keeps up to 3 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Peel and halve the hard-boiled eggs and plate with a scoop of hummus.", "type": "prep", "active": true, "appliance": null, "duration_min": 2, "ingredient_refs": ["egg, whole, hard-boiled", "hummus, commercial"]}, {"n": 2, "temp": null, "text": "Cut the carrots and bell peppers into sticks for dipping.", "type": "assemble", "active": true, "appliance": null, "duration_min": 3, "ingredient_refs": ["carrots, raw", "bell peppers, raw"]}], "title": "Assemble"}], "make_ahead": "Boil the eggs and cut the veg up to 3 days ahead.", "cook_time_min": 0, "prep_time_min": 5, "total_time_min": 5, "yield_servings": 1}'::jsonb where id='e22b5583-0131-40ed-af88-49613fbcdb60' and user_id is null;

-- Keto Almond Flour Breakfast Muffins
update recipes set recipe_kind='cooked', instructions='{"reheat": "Serve at room temperature or warm briefly.", "storage": "Keeps up to 4 days refrigerated or 2 months frozen.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Heat the oven to 180°C. Whisk the eggs with the melted coconut oil, vanilla, cinnamon, and sea salt, then stir in the almond flour to a batter.", "type": "prep", "active": true, "appliance": null, "duration_min": 8, "ingredient_refs": ["egg, whole, raw", "coconut oil", "vanilla extract", "cinnamon, ground", "sea salt", "almond flour"]}, {"n": 2, "temp": {"unit": "C", "value": 180}, "text": "Divide into a lined muffin tin and bake until set and golden, about 20 minutes.", "type": "cook", "active": false, "appliance": "oven", "duration_min": 20, "ingredient_refs": []}], "title": "Bake"}], "make_ahead": "Bake a batch ahead; great for grab-and-go.", "cook_time_min": 20, "prep_time_min": 8, "total_time_min": 28, "yield_servings": 1}'::jsonb where id='e4b26ead-031b-4278-92f4-e358ed2d0b8c' and user_id is null;

-- Keto Avocado Egg Cups
update recipes set recipe_kind='cooked', instructions='{"reheat": "Serve fresh.", "storage": "Keeps up to 1 day refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Heat the oven to 200°C. Halve the avocado and scoop out a little extra to make room for the egg; set in a baking dish and brush with olive oil.", "type": "prep", "active": true, "appliance": null, "duration_min": 4, "ingredient_refs": ["avocado, raw", "olive oil"]}, {"n": 2, "temp": {"unit": "C", "value": 200}, "text": "Crack an egg into each avocado half, dust with paprika and sea salt, and bake until the whites set, about 15 minutes.", "type": "cook", "active": false, "appliance": "oven", "duration_min": 16, "ingredient_refs": ["egg, whole, raw", "paprika", "sea salt"]}], "title": "Bake"}], "make_ahead": "Best baked fresh.", "cook_time_min": 16, "prep_time_min": 4, "total_time_min": 20, "yield_servings": 1}'::jsonb where id='1b0f11d5-2b53-4291-90ba-1c957c6cc7c4' and user_id is null;

-- Keto Bacon and Egg Cups
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat in the oven or microwave.", "storage": "Keeps up to 4 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Heat the oven to 190°C. Line muffin cups with the bacon and warm briefly if needed.", "type": "prep", "active": true, "appliance": null, "duration_min": 5, "ingredient_refs": ["bacon, cured, pan-fried"]}, {"n": 2, "temp": {"unit": "C", "value": 190}, "text": "Whisk the eggs with the heavy cream, stir in the cheddar, pour into the bacon-lined cups, and bake until set, about 18 minutes.", "type": "cook", "active": false, "appliance": "oven", "duration_min": 20, "ingredient_refs": ["egg, whole, raw", "heavy cream", "cheddar cheese"]}], "title": "Bake"}], "make_ahead": "Bake ahead; great for meal prep.", "cook_time_min": 20, "prep_time_min": 5, "total_time_min": 25, "yield_servings": 1}'::jsonb where id='9d0b89ab-9b48-46a4-a531-f19d4988a564' and user_id is null;

-- Keto Beef Breakfast Skillet
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat the base; add fresh eggs.", "storage": "Keeps up to 3 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Dice the bell peppers and onion and saute in olive oil until soft, about 4 minutes.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 4, "ingredient_refs": ["bell peppers, raw", "olive oil"]}, {"n": 2, "temp": null, "text": "Add the ground beef and brown, breaking it up, about 6 minutes; season with sea salt and black pepper.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 6, "ingredient_refs": ["ground beef, 80% lean, raw", "sea salt", "black pepper, ground"]}, {"n": 3, "temp": null, "text": "Make wells, crack in the eggs, scatter the cheddar over, and cook covered until the eggs set, about 4 minutes.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 4, "ingredient_refs": ["egg, whole, raw", "cheddar cheese"]}], "title": "Cook"}], "make_ahead": "Cook the beef base ahead; add eggs fresh.", "cook_time_min": 14, "prep_time_min": 5, "total_time_min": 19, "yield_servings": 1}'::jsonb where id='9af093e0-e8d0-4bcb-979c-723c4822df71' and user_id is null;

-- Keto Cauliflower Hash and Eggs
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat the hash; add fresh eggs.", "storage": "Keeps up to 3 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Pulse the cauliflower into rice and dice the onion; saute both in olive oil until golden, about 8 minutes. Season with sea salt and black pepper.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 8, "ingredient_refs": ["cauliflower, raw", "onions, raw", "olive oil", "sea salt", "black pepper, ground"]}, {"n": 2, "temp": null, "text": "Make wells, crack in the eggs, scatter the cheddar, and cook covered until the eggs set, about 5 minutes.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 6, "ingredient_refs": ["egg, whole, raw", "cheddar cheese"]}], "title": "Cook"}], "make_ahead": "Make the hash ahead; add eggs fresh.", "cook_time_min": 15, "prep_time_min": 6, "total_time_min": 21, "yield_servings": 1}'::jsonb where id='70ea6c29-7d51-4326-b908-5260e9352f1e' and user_id is null;

-- Keto Cheddar Egg Muffins
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat in the oven or microwave.", "storage": "Keeps up to 4 days refrigerated or 2 months frozen.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Heat the oven to 190°C. Whisk the eggs with the heavy cream, stir in the chopped spinach and cheddar, and season with sea salt and black pepper.", "type": "prep", "active": true, "appliance": null, "duration_min": 5, "ingredient_refs": ["egg, whole, raw", "heavy cream", "spinach, raw", "cheddar cheese", "sea salt", "black pepper, ground"]}, {"n": 2, "temp": {"unit": "C", "value": 190}, "text": "Pour into a lined muffin tin and bake until set, about 18 minutes.", "type": "cook", "active": false, "appliance": "oven", "duration_min": 18, "ingredient_refs": []}], "title": "Bake"}], "make_ahead": "Bake ahead; great for meal prep.", "cook_time_min": 18, "prep_time_min": 5, "total_time_min": 23, "yield_servings": 1}'::jsonb where id='15363e22-f23c-48da-b9dc-3a094eaab310' and user_id is null;

-- Keto Cheddar Egg Snack Puffs
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat briefly in the oven or microwave.", "storage": "Keeps up to 4 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Heat the oven to 190°C. Whisk the eggs with the cheddar and season with sea salt and black pepper.", "type": "prep", "active": true, "appliance": null, "duration_min": 4, "ingredient_refs": ["egg, whole, raw", "cheddar cheese", "sea salt", "black pepper, ground"]}, {"n": 2, "temp": {"unit": "C", "value": 190}, "text": "Pour into a lined mini-muffin tin and bake until puffed and set, about 16 minutes.", "type": "cook", "active": false, "appliance": "oven", "duration_min": 16, "ingredient_refs": []}], "title": "Bake"}], "make_ahead": "Bake ahead; great high-protein snack.", "cook_time_min": 16, "prep_time_min": 4, "total_time_min": 20, "yield_servings": 1}'::jsonb where id='2d3682a2-ebc6-4a9b-9ad2-605a4e426d9b' and user_id is null;

-- Keto Cottage Cheese Egg Scramble
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat gently; eggs are best fresh.", "storage": "Keeps up to 1 day refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Wilt the spinach in olive oil over medium, about 2 minutes.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 2, "ingredient_refs": ["spinach, raw", "olive oil"]}, {"n": 2, "temp": null, "text": "Whisk the eggs and pour in; as they begin to set, fold in the cottage cheese and softly scramble. Season with sea salt and black pepper.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 5, "ingredient_refs": ["egg, whole, raw", "cottage cheese, lowfat", "sea salt", "black pepper, ground"]}], "title": "Cook"}], "make_ahead": "Best cooked fresh.", "cook_time_min": 7, "prep_time_min": 3, "total_time_min": 10, "yield_servings": 1}'::jsonb where id='65527f5e-f792-44eb-9ec7-7f998ea61e43' and user_id is null;

-- Keto Cream Cheese Pancakes
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat in a pan or toaster.", "storage": "Keeps up to 2 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Blend the eggs, cream cheese, almond flour, vanilla, and cinnamon into a smooth batter.", "type": "prep", "active": true, "appliance": "blender", "duration_min": 4, "ingredient_refs": ["egg, whole, raw", "cream cheese", "almond flour", "vanilla extract", "cinnamon, ground"]}, {"n": 2, "temp": null, "text": "Melt a little coconut oil in a pan and cook small pancakes over medium, about 2 minutes per side, until golden.", "type": "cook", "active": false, "appliance": "stovetop", "duration_min": 10, "ingredient_refs": ["coconut oil"]}], "title": "Make the batter and cook"}], "make_ahead": "Batter can be made ahead; cook fresh.", "cook_time_min": 10, "prep_time_min": 6, "total_time_min": 16, "yield_servings": 1}'::jsonb where id='0b3a3036-bc92-43e2-8cbf-0924542b6af1' and user_id is null;

-- Keto Mushroom Egg Scramble
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat gently; eggs are best fresh.", "storage": "Keeps up to 1 day refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Slice the mushrooms and saute in olive oil until golden, about 5 minutes.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 5, "ingredient_refs": ["mushrooms, portobello, raw", "olive oil"]}, {"n": 2, "temp": null, "text": "Whisk the eggs with the heavy cream and parmesan, pour in, and softly scramble; season with sea salt.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 6, "ingredient_refs": ["egg, whole, raw", "heavy cream", "parmesan cheese", "sea salt"]}], "title": "Cook"}], "make_ahead": "Best cooked fresh.", "cook_time_min": 11, "prep_time_min": 5, "total_time_min": 16, "yield_servings": 1}'::jsonb where id='b7ed1e1f-6a8a-47be-8caf-ff8b9e275c72' and user_id is null;

-- Keto Salmon Cream Cheese Breakfast
update recipes set recipe_kind='assembly', instructions='{"reheat": "Serve cold.", "storage": "Keeps up to 1 day refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Spread the cream cheese onto a plate or over cucumber slices.", "type": "prep", "active": true, "appliance": null, "duration_min": 3, "ingredient_refs": ["cream cheese", "cucumber, raw"]}, {"n": 2, "temp": null, "text": "Drape over the smoked salmon, add the sliced avocado, and season with sea salt and black pepper.", "type": "assemble", "active": true, "appliance": null, "duration_min": 3, "ingredient_refs": ["smoked salmon", "avocado, raw", "sea salt", "black pepper, ground"]}], "title": "Assemble"}], "make_ahead": "Assemble fresh; slice components ahead.", "cook_time_min": 0, "prep_time_min": 6, "total_time_min": 6, "yield_servings": 1}'::jsonb where id='48cf28f6-afc8-4134-9e5d-405a3744da86' and user_id is null;

-- Keto Spinach Feta Frittata
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat in the oven or microwave.", "storage": "Keeps up to 3 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Heat the oven to 190°C. Wilt the spinach in an ovenproof pan with olive oil, about 2 minutes.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 3, "ingredient_refs": ["spinach, raw", "olive oil"]}, {"n": 2, "temp": null, "text": "Whisk the eggs with the heavy cream, season with sea salt, pour over the spinach, and crumble the feta on top.", "type": "prep", "active": true, "appliance": null, "duration_min": 3, "ingredient_refs": ["egg, whole, raw", "heavy cream", "sea salt", "feta cheese"]}, {"n": 3, "temp": {"unit": "C", "value": 190}, "text": "Transfer to the oven and bake until set and golden, about 15 minutes.", "type": "cook", "active": false, "appliance": "oven", "duration_min": 15, "ingredient_refs": []}], "title": "Cook the frittata"}], "make_ahead": "Bake ahead and slice; great for meal prep.", "cook_time_min": 20, "prep_time_min": 5, "total_time_min": 25, "yield_servings": 1}'::jsonb where id='a47b2643-2fa3-4d33-ac74-6e0e5b750d21' and user_id is null;

-- Keto Zucchini Egg Bake
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat in the oven or microwave.", "storage": "Keeps up to 3 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Heat the oven to 190°C. Grate the zucchini, squeeze out excess water, and mix with olive oil and italian seasoning.", "type": "prep", "active": true, "appliance": null, "duration_min": 6, "ingredient_refs": ["zucchini, raw", "olive oil", "italian seasoning"]}, {"n": 2, "temp": {"unit": "C", "value": 190}, "text": "Whisk in the eggs and mozzarella, season with sea salt, pour into a baking dish, and bake until set, about 22 minutes.", "type": "cook", "active": false, "appliance": "oven", "duration_min": 22, "ingredient_refs": ["egg, whole, raw", "mozzarella cheese", "sea salt"]}], "title": "Bake"}], "make_ahead": "Bake ahead and slice; great for meal prep.", "cook_time_min": 22, "prep_time_min": 6, "total_time_min": 28, "yield_servings": 1}'::jsonb where id='22124e91-ffad-44e9-9f92-692851840802' and user_id is null;

-- Mediterranean Avocado Egg Toast
update recipes set recipe_kind='cooked', instructions='{"reheat": "Serve fresh.", "storage": "Best eaten immediately.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Toast the bread and fry the egg to your liking.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 6, "ingredient_refs": ["whole wheat bread", "egg, whole, raw"]}, {"n": 2, "temp": null, "text": "Mash the avocado onto the toast, top with the egg and halved cherry tomatoes, drizzle with olive oil, and season with sea salt and black pepper.", "type": "assemble", "active": true, "appliance": null, "duration_min": 3, "ingredient_refs": ["avocado, raw", "tomatoes, cherry", "olive oil", "sea salt", "black pepper, ground"]}], "title": "Cook and assemble"}], "make_ahead": "Best fresh so the toast stays crisp.", "cook_time_min": 6, "prep_time_min": 4, "total_time_min": 10, "yield_servings": 1}'::jsonb where id='1b1c3ee5-c9fd-4529-bc86-0542e3385866' and user_id is null;

commit;
