-- ============================================================================
-- seed-cooking-guides-soups.sql — authored cooking guides, SOUPS/STEWS archetype (15 recipes)
-- ----------------------------------------------------------------------------
-- Git source of truth for content authored directly in the DB (instructions jsonb + recipe_kind
-- per recipe id). Content UPDATEs only — NOT schema. Idempotent (matches by id); re-runnable.
-- Same pattern + schema as scripts/reclassify-diet-tags.sql / seed-cooking-guides-salads.sql.
-- All 15 are recipe_kind='cooked' (soups/stews/curries — build → simmer).
--
-- Regenerate from the live DB (swap the id-prefix filter for the batch):
--   select string_agg(format('-- %s', name) || E'\n' ||
--     format('update recipes set recipe_kind=%L, instructions=%L::jsonb where id=%L and user_id is null;',
--       recipe_kind, instructions::text, id::text), E'\n\n' order by name)
--   from recipes where user_id is null and id::text like any(array['2ca07e17%', ...]);
--
-- Progress: 57 / 299 cooking guides authored (4 archetypes: salads 26 + smoothies 6 + wraps 5 + soups 15).
-- ============================================================================

begin;

-- Keto Beef Cauliflower Stew
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat gently on the stovetop or microwave.", "storage": "Keeps up to 4 days refrigerated or 3 months frozen.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Dice the onion and garlic and saute in olive oil over medium until soft, about 4 minutes.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 4, "ingredient_refs": ["onions, raw", "garlic, raw", "olive oil"]}, {"n": 2, "temp": null, "text": "Add the ground beef and brown, breaking it up, about 6 minutes.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 6, "ingredient_refs": ["ground beef, 90% lean, raw"]}], "title": "Brown and build"}, {"steps": [{"n": 3, "temp": null, "text": "Add the cauliflower florets, diced tomatoes, and beef broth; bring to a simmer.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 3, "ingredient_refs": ["cauliflower, raw", "tomato products, canned, diced", "beef broth"]}, {"n": 4, "temp": null, "text": "Simmer gently until the cauliflower is tender and the stew thickens, about 25 minutes.", "type": "cook", "active": false, "appliance": "stovetop", "duration_min": 25, "ingredient_refs": []}], "title": "Simmer"}], "make_ahead": "Tastes better the next day; make up to 4 days ahead.", "cook_time_min": 35, "prep_time_min": 10, "total_time_min": 45, "yield_servings": 1}'::jsonb where id='2ca07e17-a452-444d-924c-0944835aac12' and user_id is null;

-- Mediterranean Eggplant Lentil Stew
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat gently on the stovetop.", "storage": "Keeps up to 4 days refrigerated or 3 months frozen.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Dice the onion and garlic and saute in olive oil over medium until soft, about 4 minutes.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 4, "ingredient_refs": ["onions, raw", "garlic, raw", "olive oil"]}, {"n": 2, "temp": null, "text": "Add the diced eggplant and cumin and cook until the eggplant softens, about 6 minutes.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 6, "ingredient_refs": ["eggplant, raw", "cumin, ground"]}], "title": "Build"}, {"steps": [{"n": 3, "temp": null, "text": "Stir in the cooked lentils and diced tomatoes and bring to a simmer.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 2, "ingredient_refs": ["lentils, mature seeds, cooked, boiled", "tomato products, canned, diced"]}, {"n": 4, "temp": null, "text": "Simmer until thick and the flavors meld, about 18 minutes.", "type": "cook", "active": false, "appliance": "stovetop", "duration_min": 18, "ingredient_refs": []}], "title": "Simmer"}], "make_ahead": "Tastes better the next day; make up to 4 days ahead.", "cook_time_min": 30, "prep_time_min": 10, "total_time_min": 40, "yield_servings": 1}'::jsonb where id='24a9cf3d-ceb7-4d07-9bf2-0982d5267f1c' and user_id is null;

-- Mediterranean Lentil Tomato Soup
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat gently on the stovetop.", "storage": "Keeps up to 4 days refrigerated or 3 months frozen.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Dice the onion and garlic and saute in olive oil over medium until soft, about 4 minutes.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 4, "ingredient_refs": ["onions, raw", "garlic, raw", "olive oil"]}, {"n": 2, "temp": null, "text": "Stir in the cumin and toast for 30 seconds.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 1, "ingredient_refs": ["cumin, ground"]}], "title": "Build"}, {"steps": [{"n": 3, "temp": null, "text": "Add the cooked lentils, diced tomatoes, and a cup of water; season with sea salt and bring to a simmer.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 2, "ingredient_refs": ["lentils, mature seeds, cooked, boiled", "tomato products, canned, diced", "sea salt"]}, {"n": 4, "temp": null, "text": "Simmer until thickened, about 20 minutes; blend partially for a smoother soup if you like.", "type": "cook", "active": false, "appliance": "stovetop", "duration_min": 20, "ingredient_refs": []}], "title": "Simmer"}], "make_ahead": "Make up to 4 days ahead.", "cook_time_min": 27, "prep_time_min": 8, "total_time_min": 35, "yield_servings": 1}'::jsonb where id='d2798029-9afc-44b1-9a5e-459536b11f9d' and user_id is null;

-- Paleo Beef Butternut Squash Curry
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat gently on the stovetop.", "storage": "Keeps up to 4 days refrigerated or 3 months frozen.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Dice the onion and garlic and saute in olive oil over medium until soft, about 4 minutes.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 4, "ingredient_refs": ["onions, raw", "garlic, raw", "olive oil"]}, {"n": 2, "temp": null, "text": "Add the ground beef and brown, then stir in the cumin.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 6, "ingredient_refs": ["ground beef, 90% lean, raw", "cumin, ground"]}], "title": "Brown and build"}, {"steps": [{"n": 3, "temp": null, "text": "Add the cubed butternut squash and coconut milk; bring to a simmer.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 3, "ingredient_refs": ["butternut squash, raw", "coconut milk"]}, {"n": 4, "temp": null, "text": "Simmer until the squash is tender and the curry thickens, about 22 minutes.", "type": "cook", "active": false, "appliance": "stovetop", "duration_min": 22, "ingredient_refs": []}], "title": "Simmer"}], "make_ahead": "Tastes better the next day; make up to 4 days ahead.", "cook_time_min": 35, "prep_time_min": 10, "total_time_min": 45, "yield_servings": 1}'::jsonb where id='3440a487-e8a0-4033-a83c-efdeb0091758' and user_id is null;

-- Paleo Chicken Vegetable Soup
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat gently on the stovetop.", "storage": "Keeps up to 4 days refrigerated or 3 months frozen.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Dice the onion, garlic, carrots, and celery and saute in a pot until softened, about 5 minutes.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 5, "ingredient_refs": ["onions, raw", "garlic, raw", "carrots, raw", "celery, raw"]}, {"n": 2, "temp": null, "text": "Add the diced chicken and chicken broth and bring to a simmer.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 3, "ingredient_refs": ["chicken breast, broilers or fryers, raw", "chicken broth"]}], "title": "Build"}, {"steps": [{"n": 3, "temp": null, "text": "Simmer until the chicken is cooked through and the vegetables are tender, about 18 minutes.", "type": "cook", "active": false, "appliance": "stovetop", "duration_min": 18, "ingredient_refs": []}, {"n": 4, "temp": null, "text": "Stir in the chopped kale and cook until wilted, about 4 minutes.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 4, "ingredient_refs": ["kale, raw"]}], "title": "Simmer"}], "make_ahead": "Make up to 4 days ahead.", "cook_time_min": 30, "prep_time_min": 10, "total_time_min": 40, "yield_servings": 1}'::jsonb where id='ca2e1d24-d3ff-4778-9542-1128282fa5d6' and user_id is null;

-- Paleo Lamb Stew Root Vegetables
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat gently on the stovetop.", "storage": "Keeps up to 4 days refrigerated or 3 months frozen.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Season the lamb and sear in olive oil over medium-high until browned, about 5 minutes; add the diced onion.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 6, "ingredient_refs": ["lamb, rib chop, lean, raw", "olive oil", "onions, raw"]}], "title": "Brown and build"}, {"steps": [{"n": 2, "temp": null, "text": "Add the carrots, sweet potato, beef broth, and rosemary; bring to a simmer.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 4, "ingredient_refs": ["carrots, raw", "sweet potato, raw", "beef broth", "rosemary, fresh"]}, {"n": 3, "temp": null, "text": "Cover and simmer gently until the lamb is tender and the vegetables are soft, about 40 minutes.", "type": "cook", "active": false, "appliance": "stovetop", "duration_min": 40, "ingredient_refs": []}], "title": "Simmer"}], "make_ahead": "Tastes better the next day; make up to 4 days ahead.", "cook_time_min": 50, "prep_time_min": 12, "total_time_min": 62, "yield_servings": 1}'::jsonb where id='bcd16425-5906-49ae-b87b-731e917a75fb' and user_id is null;

-- Pescatarian Mahi Mahi Coconut Curry
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat gently so the fish does not overcook.", "storage": "Keeps up to 2 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Dice the onion, garlic, and ginger and saute in olive oil until fragrant, about 4 minutes; stir in the cumin.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 4, "ingredient_refs": ["onions, raw", "garlic, raw", "ginger root, raw", "olive oil", "cumin, ground"]}, {"n": 2, "temp": null, "text": "Add the diced tomatoes and coconut milk and simmer 8 minutes to make a sauce.", "type": "cook", "active": false, "appliance": "stovetop", "duration_min": 8, "ingredient_refs": ["tomato products, canned, diced", "coconut milk"]}], "title": "Build the sauce"}, {"steps": [{"n": 3, "temp": null, "text": "Nestle the mahi-mahi into the sauce and simmer gently until it flakes, about 10 minutes.", "type": "cook", "active": false, "appliance": "stovetop", "duration_min": 10, "ingredient_refs": ["mahi-mahi, raw"]}], "title": "Cook the fish"}], "make_ahead": "Make the sauce up to 3 days ahead; cook the fish fresh.", "cook_time_min": 25, "prep_time_min": 10, "total_time_min": 35, "yield_servings": 1}'::jsonb where id='6c6b607a-3df7-4db4-a54c-b6a17e62ee79' and user_id is null;

-- Vegan Black Bean Quinoa Chili
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat gently on the stovetop.", "storage": "Keeps up to 4 days refrigerated or 3 months frozen.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Dice the onion, garlic, and bell peppers and saute in olive oil until soft, about 5 minutes; stir in the cumin.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 5, "ingredient_refs": ["onions, raw", "garlic, raw", "bell peppers, raw", "olive oil", "cumin, ground"]}], "title": "Build"}, {"steps": [{"n": 2, "temp": null, "text": "Add the black beans, cooked quinoa, and diced tomatoes; bring to a simmer.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 3, "ingredient_refs": ["black beans, canned, drained", "quinoa, cooked", "tomato products, canned, diced"]}, {"n": 3, "temp": null, "text": "Simmer until thick and the flavors meld, about 17 minutes.", "type": "cook", "active": false, "appliance": "stovetop", "duration_min": 17, "ingredient_refs": []}], "title": "Simmer"}], "make_ahead": "Tastes better the next day; make up to 4 days ahead.", "cook_time_min": 25, "prep_time_min": 10, "total_time_min": 35, "yield_servings": 1}'::jsonb where id='5b60a29c-9805-426a-8c96-f2d78f5e0c67' and user_id is null;

-- Vegan Butternut Squash Lentil Soup
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat gently on the stovetop.", "storage": "Keeps up to 4 days refrigerated or 3 months frozen.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Dice the onion and garlic and saute in olive oil until soft, about 4 minutes; stir in the cumin.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 4, "ingredient_refs": ["onions, raw", "garlic, raw", "olive oil", "cumin, ground"]}], "title": "Build"}, {"steps": [{"n": 2, "temp": null, "text": "Add the cubed butternut squash, cooked lentils, and a cup of water; season with sea salt and bring to a simmer.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 3, "ingredient_refs": ["butternut squash, raw", "lentils, mature seeds, cooked, boiled", "sea salt"]}, {"n": 3, "temp": null, "text": "Simmer until the squash is tender, about 23 minutes; blend partially for a creamier soup.", "type": "cook", "active": false, "appliance": "stovetop", "duration_min": 23, "ingredient_refs": []}], "title": "Simmer"}], "make_ahead": "Make up to 4 days ahead.", "cook_time_min": 30, "prep_time_min": 10, "total_time_min": 40, "yield_servings": 1}'::jsonb where id='30f054e1-b518-434a-81ba-ba5aae1c53dc' and user_id is null;

-- Vegan Chickpea Curry
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat gently on the stovetop.", "storage": "Keeps up to 4 days refrigerated or 3 months frozen.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Dice the onion and garlic and saute in olive oil until soft, about 4 minutes.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 4, "ingredient_refs": ["onions, raw", "garlic, raw", "olive oil"]}, {"n": 2, "temp": null, "text": "Add the diced tomatoes and coconut milk and simmer 6 minutes.", "type": "cook", "active": false, "appliance": "stovetop", "duration_min": 6, "ingredient_refs": ["tomato products, canned, diced", "coconut milk"]}], "title": "Build the sauce"}, {"steps": [{"n": 3, "temp": null, "text": "Stir in the chickpeas and simmer until thick, about 12 minutes. Serve over the brown rice.", "type": "cook", "active": false, "appliance": "stovetop", "duration_min": 12, "ingredient_refs": ["chickpeas, mature seeds, canned, drained", "brown rice, cooked"]}], "title": "Simmer"}], "make_ahead": "Tastes better the next day; make up to 4 days ahead.", "cook_time_min": 22, "prep_time_min": 8, "total_time_min": 30, "yield_servings": 1}'::jsonb where id='08bf16fd-39d2-454f-8733-e0c09f1bdc05' and user_id is null;

-- Vegan Chickpea Eggplant Stew
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat gently on the stovetop.", "storage": "Keeps up to 4 days refrigerated or 3 months frozen.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Dice the onion and garlic and saute in olive oil until soft, about 4 minutes; add the diced eggplant and cumin and cook 6 minutes.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 10, "ingredient_refs": ["onions, raw", "garlic, raw", "olive oil", "eggplant, raw", "cumin, ground"]}], "title": "Build"}, {"steps": [{"n": 2, "temp": null, "text": "Add the chickpeas and diced tomatoes and bring to a simmer.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 2, "ingredient_refs": ["chickpeas, mature seeds, canned, drained", "tomato products, canned, diced"]}, {"n": 3, "temp": null, "text": "Simmer until thick and the eggplant is silky, about 16 minutes.", "type": "cook", "active": false, "appliance": "stovetop", "duration_min": 16, "ingredient_refs": []}], "title": "Simmer"}], "make_ahead": "Tastes better the next day; make up to 4 days ahead.", "cook_time_min": 28, "prep_time_min": 10, "total_time_min": 38, "yield_servings": 1}'::jsonb where id='88152ce1-46a4-415c-8601-e9affeeb4938' and user_id is null;

-- Vegan Chickpea Spinach Coconut Curry
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat gently on the stovetop.", "storage": "Keeps up to 4 days refrigerated or 3 months frozen.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Dice the onion and garlic and saute in olive oil until soft, about 4 minutes; stir in the cumin.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 4, "ingredient_refs": ["onions, raw", "garlic, raw", "olive oil", "cumin, ground"]}, {"n": 2, "temp": null, "text": "Add the diced tomatoes and coconut milk and simmer 6 minutes.", "type": "cook", "active": false, "appliance": "stovetop", "duration_min": 6, "ingredient_refs": ["tomato products, canned, diced", "coconut milk"]}], "title": "Build the sauce"}, {"steps": [{"n": 3, "temp": null, "text": "Stir in the chickpeas and simmer 8 minutes, then fold in the spinach until wilted.", "type": "cook", "active": false, "appliance": "stovetop", "duration_min": 10, "ingredient_refs": ["chickpeas, mature seeds, canned, drained", "spinach, raw"]}], "title": "Simmer"}], "make_ahead": "Make up to 4 days ahead.", "cook_time_min": 22, "prep_time_min": 8, "total_time_min": 30, "yield_servings": 1}'::jsonb where id='bf0bf78c-d5bc-4093-8621-8a675bcbc59b' and user_id is null;

-- Vegan Coconut Chickpea Curry
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat gently on the stovetop.", "storage": "Keeps up to 4 days refrigerated or 3 months frozen.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Dice the onion, garlic, and ginger and saute in olive oil until fragrant, about 4 minutes; stir in the cumin.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 4, "ingredient_refs": ["onions, raw", "garlic, raw", "ginger root, raw", "olive oil", "cumin, ground"]}, {"n": 2, "temp": null, "text": "Add the coconut milk and simmer 6 minutes.", "type": "cook", "active": false, "appliance": "stovetop", "duration_min": 6, "ingredient_refs": ["coconut milk"]}], "title": "Build the sauce"}, {"steps": [{"n": 3, "temp": null, "text": "Stir in the chickpeas and simmer 8 minutes, then fold in the spinach until wilted.", "type": "cook", "active": false, "appliance": "stovetop", "duration_min": 10, "ingredient_refs": ["chickpeas, mature seeds, canned, drained", "spinach, raw"]}], "title": "Simmer"}], "make_ahead": "Make up to 4 days ahead.", "cook_time_min": 22, "prep_time_min": 8, "total_time_min": 30, "yield_servings": 1}'::jsonb where id='e16025b7-1b42-449f-a384-67f3e33311ea' and user_id is null;

-- Vegan Lentil Sweet Potato Soup
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat gently on the stovetop.", "storage": "Keeps up to 4 days refrigerated or 3 months frozen.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Dice the onion and garlic and saute in olive oil until soft, about 4 minutes; stir in the cumin.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 4, "ingredient_refs": ["onions, raw", "garlic, raw", "olive oil", "cumin, ground"]}], "title": "Build"}, {"steps": [{"n": 2, "temp": null, "text": "Add the cooked lentils, cubed sweet potato, and a cup of water; season with sea salt and bring to a simmer.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 3, "ingredient_refs": ["lentils, mature seeds, cooked, boiled", "sweet potato, raw", "sea salt"]}, {"n": 3, "temp": null, "text": "Simmer until the sweet potato is tender, about 20 minutes.", "type": "cook", "active": false, "appliance": "stovetop", "duration_min": 20, "ingredient_refs": []}], "title": "Simmer"}], "make_ahead": "Make up to 4 days ahead.", "cook_time_min": 27, "prep_time_min": 8, "total_time_min": 35, "yield_servings": 1}'::jsonb where id='443d543f-831a-4e41-b6fa-4f4237da7d61' and user_id is null;

-- Vegan Lentil Vegetable Soup
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat gently on the stovetop.", "storage": "Keeps up to 4 days refrigerated or 3 months frozen.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Dice the onion, garlic, carrots, and celery and saute in olive oil until softened, about 5 minutes; stir in the cumin.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 5, "ingredient_refs": ["onions, raw", "garlic, raw", "carrots, raw", "celery, raw", "olive oil", "cumin, ground"]}], "title": "Build"}, {"steps": [{"n": 2, "temp": null, "text": "Add the cooked lentils, chopped tomatoes, and a cup of water; bring to a simmer.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 3, "ingredient_refs": ["lentils, mature seeds, cooked, boiled", "tomatoes, raw"]}, {"n": 3, "temp": null, "text": "Simmer until the vegetables are tender and the soup thickens, about 17 minutes.", "type": "cook", "active": false, "appliance": "stovetop", "duration_min": 17, "ingredient_refs": []}], "title": "Simmer"}], "make_ahead": "Make up to 4 days ahead.", "cook_time_min": 25, "prep_time_min": 10, "total_time_min": 35, "yield_servings": 1}'::jsonb where id='935def94-2594-483c-be96-64fc49da0d5d' and user_id is null;

commit;
