-- ============================================================================
-- seed-cooking-guides-mains-6.sql — authored cooking guides, MAINS archetype (batch 6, 15 recipes)
-- ----------------------------------------------------------------------------
-- Git source of truth for content authored directly in the DB (instructions jsonb + recipe_kind
-- per recipe id). Content UPDATEs only — NOT schema. Idempotent (matches by id); re-runnable.
-- Same pattern + schema as the other seed-cooking-guides-*.sql files.
--
-- Regenerate from the live DB (swap the id-prefix filter for the batch):
--   select string_agg(format('-- %s', name) || E'\n' ||
--     format('update recipes set recipe_kind=%L, instructions=%L::jsonb where id=%L and user_id is null;',
--       recipe_kind, instructions::text, id::text), E'\n\n' order by name)
--   from recipes where user_id is null and instructions is not null and id::text like any(array['3c8762cf%', ...]);
--
-- Progress: 281 / 299 cooking guides authored (94%) — salads 26 + smoothies 6 + wraps 5 + soups 15 + bowls 77 + originals 5 + breakfast 57 + mains 90 (batches 1-6).
-- ============================================================================

begin;

-- Paleo Pork Tenderloin with Apple
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat gently.", "storage": "Keeps up to 3 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Slice the onion and apple and saute in olive oil with the cinnamon until soft and caramelized, about 8 minutes.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 8, "ingredient_refs": ["onions, raw", "apples, raw", "olive oil", "cinnamon, ground"]}, {"n": 2, "temp": {"unit": "C", "value": 63}, "text": "Season the pork with sea salt, sear, then cook through over medium about 12 minutes (63°C internal); rest, slice, and serve with the apples.", "type": "cook", "active": false, "appliance": "stovetop", "duration_min": 12, "ingredient_refs": ["pork tenderloin, raw", "sea salt"]}], "title": "Cook"}], "make_ahead": "Cook up to 3 days ahead.", "cook_time_min": 20, "prep_time_min": 6, "total_time_min": 26, "yield_servings": 1}'::jsonb where id='3c8762cf-c90b-420d-a5b8-90bccc632499' and user_id is null;

-- Paleo Pumpkin Seed Hemp Mix
update recipes set recipe_kind='cooked', instructions='{"reheat": "Serve at room temperature.", "storage": "Keeps up to 2 weeks in an airtight container.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Toast the pumpkin seeds and almonds in a dry pan over medium until golden, about 6 minutes; add the hemp seeds for the last minute.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 6, "ingredient_refs": ["pumpkin seeds, raw", "almonds, raw", "hemp seeds, hulled"]}, {"n": 2, "temp": null, "text": "Toss with sea salt and cinnamon and let cool.", "type": "assemble", "active": true, "appliance": null, "duration_min": 1, "ingredient_refs": ["sea salt", "cinnamon, ground"]}], "title": "Toast"}], "make_ahead": "Make a batch ahead; keeps well.", "cook_time_min": 7, "prep_time_min": 2, "total_time_min": 9, "yield_servings": 1}'::jsonb where id='484e4bbc-b111-44bf-9a8d-b55a156fcdba' and user_id is null;

-- Paleo Salmon with Mango Avocado Salsa
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat the salmon gently; add salsa fresh.", "storage": "Keeps up to 1 day refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Dice the mango and avocado and toss with lemon juice for a fresh salsa.", "type": "prep", "active": true, "appliance": null, "duration_min": 6, "ingredient_refs": ["mango, raw", "avocado, raw", "lemon juice, raw"]}], "title": "Make the salsa"}, {"steps": [{"n": 2, "temp": null, "text": "Season the salmon and pan-sear in olive oil about 4 minutes per side until it flakes; top with the mango avocado salsa.", "type": "cook", "active": false, "appliance": "stovetop", "duration_min": 10, "ingredient_refs": ["salmon, atlantic, farmed, raw", "olive oil"]}], "title": "Cook the salmon"}], "make_ahead": "Make the salsa a few hours ahead; cook the salmon fresh.", "cook_time_min": 10, "prep_time_min": 8, "total_time_min": 18, "yield_servings": 1}'::jsonb where id='ff95c6af-6a14-4878-8799-139a6f219b6d' and user_id is null;

-- Paleo Shrimp Asparagus Stir Fry
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat gently.", "storage": "Keeps up to 1 day refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Mince the garlic and trim the asparagus. Saute the shrimp in olive oil with the garlic until pink, about 3 minutes; remove.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 4, "ingredient_refs": ["garlic, raw", "asparagus, raw", "shrimp, raw", "olive oil"]}, {"n": 2, "temp": null, "text": "Stir-fry the asparagus until tender-crisp, about 5 minutes, return the shrimp, and finish with lemon juice and sea salt.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 6, "ingredient_refs": ["lemon juice, raw", "sea salt"]}], "title": "Cook"}], "make_ahead": "Best cooked fresh.", "cook_time_min": 10, "prep_time_min": 5, "total_time_min": 15, "yield_servings": 1}'::jsonb where id='dcb572ab-e085-4384-a920-a948455ea962' and user_id is null;

-- Paleo Smoked Salmon Avocado Plate
update recipes set recipe_kind='assembly', instructions='{"reheat": "Serve cold.", "storage": "Keeps up to 1 day refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Slice the avocado and cucumber and arrange on a plate with the smoked salmon.", "type": "prep", "active": true, "appliance": null, "duration_min": 5, "ingredient_refs": ["avocado, raw", "cucumber, raw", "smoked salmon"]}, {"n": 2, "temp": null, "text": "Drizzle with olive oil and lemon juice and season with sea salt.", "type": "assemble", "active": true, "appliance": null, "duration_min": 2, "ingredient_refs": ["olive oil", "lemon juice, raw", "sea salt"]}], "title": "Assemble"}], "make_ahead": "Assemble fresh; slice components ahead.", "cook_time_min": 0, "prep_time_min": 7, "total_time_min": 7, "yield_servings": 1}'::jsonb where id='841a288f-580b-425e-9773-bdc8eaae3a1d' and user_id is null;

-- Pescatarian Baked Halibut Tomato Dinner
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat gently so the fish does not dry out.", "storage": "Keeps up to 1 day refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Heat the oven to 200°C. Mince the garlic and mix the diced tomatoes with olive oil, lemon juice, italian seasoning, and sea salt.", "type": "prep", "active": true, "appliance": null, "duration_min": 6, "ingredient_refs": ["garlic, raw", "tomato products, canned, diced", "olive oil", "lemon juice, raw", "italian seasoning", "sea salt"]}, {"n": 2, "temp": {"unit": "C", "value": 200}, "text": "Set the halibut in a baking dish, spoon the tomato sauce over, and bake until it flakes, about 18 minutes.", "type": "cook", "active": false, "appliance": "oven", "duration_min": 18, "ingredient_refs": ["halibut, atlantic, raw"]}], "title": "Bake"}], "make_ahead": "Best baked fresh.", "cook_time_min": 18, "prep_time_min": 6, "total_time_min": 24, "yield_servings": 1}'::jsonb where id='307fa54f-ae4b-43ec-af89-cdd12243ac86' and user_id is null;

-- Pescatarian Cod Lemon Asparagus
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat gently so the fish does not dry out.", "storage": "Keeps up to 1 day refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Mince the garlic and trim the asparagus; saute in olive oil with the garlic until tender-crisp, about 8 minutes, finishing with lemon juice and sea salt.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 8, "ingredient_refs": ["garlic, raw", "asparagus, raw", "olive oil", "lemon juice, raw", "sea salt"]}, {"n": 2, "temp": null, "text": "Pan-sear the seasoned cod about 3-4 minutes per side until it flakes; serve with the asparagus.", "type": "cook", "active": false, "appliance": "stovetop", "duration_min": 7, "ingredient_refs": ["cod, atlantic, raw"]}], "title": "Cook"}], "make_ahead": "Best cooked fresh.", "cook_time_min": 15, "prep_time_min": 5, "total_time_min": 20, "yield_servings": 1}'::jsonb where id='596a0498-ab33-4eac-b601-60fe8689971f' and user_id is null;

-- Pescatarian Halibut Kale Lemon Plate
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat gently so the fish does not dry out.", "storage": "Keeps up to 1 day refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Mince the garlic. Massage the kale, then saute in olive oil with the garlic until wilted, about 5 minutes; finish with lemon juice and sea salt.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 5, "ingredient_refs": ["garlic, raw", "kale, raw", "olive oil", "lemon juice, raw", "sea salt"]}, {"n": 2, "temp": null, "text": "Pan-sear the seasoned halibut about 4 minutes per side until it flakes; serve over the kale.", "type": "cook", "active": false, "appliance": "stovetop", "duration_min": 9, "ingredient_refs": ["halibut, atlantic, raw"]}], "title": "Cook"}], "make_ahead": "Best cooked fresh.", "cook_time_min": 14, "prep_time_min": 5, "total_time_min": 19, "yield_servings": 1}'::jsonb where id='8db6cff6-27ae-4628-8d06-fde4d693dbe6' and user_id is null;

-- Pescatarian Salmon Herb Quinoa Dinner
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat gently.", "storage": "Keeps up to 2 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Mince the garlic and trim the asparagus; saute in olive oil with the garlic until tender-crisp, about 8 minutes, finishing with lemon juice and sea salt.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 8, "ingredient_refs": ["garlic, raw", "asparagus, raw", "olive oil", "lemon juice, raw", "sea salt"]}, {"n": 2, "temp": null, "text": "Pan-sear the salmon about 4 minutes per side until it flakes; serve over the quinoa with the asparagus.", "type": "cook", "active": false, "appliance": "stovetop", "duration_min": 8, "ingredient_refs": ["salmon, atlantic, farmed, raw", "quinoa, cooked"]}], "title": "Cook"}], "make_ahead": "Cook the quinoa ahead; cook the salmon fresh.", "cook_time_min": 16, "prep_time_min": 5, "total_time_min": 21, "yield_servings": 1}'::jsonb where id='db06c303-3013-44eb-b8c5-5782bb4d6b19' and user_id is null;

-- Pescatarian Salmon Spinach Quinoa Bake
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat gently in the oven.", "storage": "Keeps up to 2 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Heat the oven to 200°C. Mince the garlic and toss the cooked quinoa and spinach with olive oil, garlic, lemon juice, and sea salt in a baking dish.", "type": "prep", "active": true, "appliance": null, "duration_min": 5, "ingredient_refs": ["garlic, raw", "quinoa, cooked", "spinach, raw", "olive oil", "lemon juice, raw", "sea salt"]}, {"n": 2, "temp": {"unit": "C", "value": 200}, "text": "Set the salmon on top and bake until the salmon flakes and the greens wilt, about 16 minutes.", "type": "cook", "active": false, "appliance": "oven", "duration_min": 16, "ingredient_refs": ["salmon, atlantic, farmed, raw"]}], "title": "Bake"}], "make_ahead": "Cook the quinoa ahead; bake fresh.", "cook_time_min": 18, "prep_time_min": 5, "total_time_min": 23, "yield_servings": 1}'::jsonb where id='fe52c884-f544-475d-b893-a9072cde8299' and user_id is null;

-- Pescatarian Shrimp Broccoli Garlic Rice
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat in a pan or microwave.", "storage": "Keeps up to 2 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Mince the garlic. Cut the broccoli into florets and saute in olive oil with the garlic until tender-crisp, about 5 minutes.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 5, "ingredient_refs": ["garlic, raw", "broccoli, raw", "olive oil"]}, {"n": 2, "temp": null, "text": "Add the shrimp and saute until pink, about 3 minutes, finishing with lemon juice and sea salt; serve over the brown rice.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 7, "ingredient_refs": ["shrimp, raw", "lemon juice, raw", "sea salt", "brown rice, cooked"]}], "title": "Cook"}], "make_ahead": "Cook the rice ahead; the skillet is fast.", "cook_time_min": 12, "prep_time_min": 5, "total_time_min": 17, "yield_servings": 1}'::jsonb where id='c0ce8851-09cc-44b3-bc0d-16263a0f2da1' and user_id is null;

-- Pescatarian Shrimp Stir Fry Brown Rice
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat in a pan.", "storage": "Keeps up to 2 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Mince the garlic and grate the ginger. Cut the broccoli into florets and stir-fry in sesame oil with the garlic and ginger until tender-crisp, about 5 minutes.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 5, "ingredient_refs": ["garlic, raw", "ginger root, raw", "broccoli, raw", "sesame oil"]}, {"n": 2, "temp": null, "text": "Add the shrimp and stir-fry until pink, about 3 minutes, splashing with soy sauce; serve over the brown rice.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 7, "ingredient_refs": ["shrimp, raw", "soy sauce", "brown rice, cooked"]}], "title": "Stir-fry"}], "make_ahead": "Cook the rice ahead; stir-fry fresh.", "cook_time_min": 12, "prep_time_min": 5, "total_time_min": 17, "yield_servings": 1}'::jsonb where id='ae3c1e4f-737b-412c-8add-e61c7c2d4575' and user_id is null;

-- Pescatarian Tilapia Avocado Mango Salsa
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat the fish gently; add salsa fresh.", "storage": "Keeps up to 1 day refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Dice the avocado and mango and toss with lemon juice and a pinch of sea salt.", "type": "prep", "active": true, "appliance": null, "duration_min": 6, "ingredient_refs": ["avocado, raw", "mango, raw", "lemon juice, raw", "sea salt"]}], "title": "Make the salsa"}, {"steps": [{"n": 2, "temp": null, "text": "Season the tilapia and pan-sear in olive oil about 3 minutes per side until it flakes; top with the salsa.", "type": "cook", "active": false, "appliance": "stovetop", "duration_min": 8, "ingredient_refs": ["tilapia, raw", "olive oil"]}], "title": "Cook the fish"}], "make_ahead": "Make the salsa a few hours ahead; cook the fish fresh.", "cook_time_min": 8, "prep_time_min": 8, "total_time_min": 16, "yield_servings": 1}'::jsonb where id='e3ab61d8-55aa-4732-a2cc-645e4c283ed2' and user_id is null;

-- Pescatarian Tilapia Sweet Potato Dinner
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat in the oven.", "storage": "Keeps up to 2 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": {"unit": "C", "value": 220}, "text": "Heat the oven to 220°C. Cube the sweet potato and cut the broccoli into florets; toss with olive oil, paprika, and sea salt and roast 20 minutes.", "type": "cook", "active": false, "appliance": "oven", "duration_min": 20, "ingredient_refs": ["sweet potato, raw", "broccoli, raw", "olive oil", "paprika", "sea salt"]}], "title": "Roast"}, {"steps": [{"n": 2, "temp": {"unit": "C", "value": 220}, "text": "Add the tilapia to the tray for the last 8 minutes, or pan-sear separately about 3 minutes per side until it flakes.", "type": "cook", "active": false, "appliance": "oven", "duration_min": 4, "ingredient_refs": ["tilapia, raw"]}], "title": "Cook the fish"}], "make_ahead": "Roast the vegetables ahead; cook the fish fresh.", "cook_time_min": 24, "prep_time_min": 6, "total_time_min": 30, "yield_servings": 1}'::jsonb where id='41b8e20a-18d6-4802-b5bf-950e498c2a43' and user_id is null;

-- Pork Tenderloin with Roasted Sweet Potato
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat in the oven.", "storage": "Keeps up to 3 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": {"unit": "C", "value": 220}, "text": "Heat the oven to 220°C. Mince the garlic. Cube the sweet potato and cut the broccoli into florets; toss with olive oil, garlic, and rosemary and roast 22 minutes.", "type": "cook", "active": false, "appliance": "oven", "duration_min": 22, "ingredient_refs": ["garlic, raw", "sweet potato, raw", "broccoli, raw", "olive oil", "rosemary, fresh"]}], "title": "Roast"}, {"steps": [{"n": 2, "temp": {"unit": "C", "value": 63}, "text": "Season the pork, sear, and cook through over medium about 12 minutes (63°C internal); rest, slice, and serve with the roasted vegetables.", "type": "cook", "active": false, "appliance": "stovetop", "duration_min": 5, "ingredient_refs": ["pork tenderloin, raw"]}], "title": "Cook the pork"}], "make_ahead": "Roast the vegetables ahead; cook the pork fresh.", "cook_time_min": 27, "prep_time_min": 6, "total_time_min": 33, "yield_servings": 1}'::jsonb where id='c8fe956a-f4a4-4f84-9d21-d08532e6e648' and user_id is null;

commit;
