-- ============================================================================
-- seed-cooking-guides-salads.sql — authored cooking guides, SALAD archetype (26 recipes)
-- ----------------------------------------------------------------------------
-- Git source of truth for content that was authored directly in the DB (instructions jsonb +
-- recipe_kind per recipe). Same pattern as scripts/reclassify-diet-tags.sql — re-runnable and
-- idempotent (matches by recipe id; re-applying the same values is a no-op).
--
-- SCOPE: shared preset recipes (user_id IS NULL) whose name matches the salad archetype.
--   Content UPDATEs only — NOT schema (the instructions/recipe_kind columns already exist via
--   migrations add_recipe_instructions_and_kind + add_recipe_primary_diet).
--
-- instructions schema (rendered by the meal-detail screen, fuel.jsx / NutritionDetail-adjacent):
--   { prep_time_min, cook_time_min, total_time_min, yield_servings,
--     sections: [{ title, steps: [{ n, text, type:'prep'|'cook'|'assemble'|'rest',
--       active, duration_min, appliance, temp:{value,unit}|null, ingredient_refs:[] }] }],
--     make_ahead, storage, reheat }
--   recipe_kind: 'assembly' (no cook section) | 'cooked' (has a cook section).
--
-- Regenerate this file from the live DB after authoring more salads:
--   select string_agg(format('-- %s', name) || E'\n' ||
--     format('update recipes set recipe_kind=%L, instructions=%L::jsonb where id=%L and user_id is null;',
--       recipe_kind, instructions::text, id::text), E'\n\n' order by name)
--   from recipes where user_id is null and name ilike '%salad%' and instructions is not null;
--
-- (More archetypes — bowls, breakfast, soups, etc. — captured in sibling seed files.)
-- ============================================================================

begin;

-- Keto Chicken Caesar Salad
update recipes set recipe_kind='cooked', instructions='{"reheat": "Serve cold, or warm the chicken briefly if preferred.", "storage": "Store undressed up to 3 days refrigerated; dress just before eating.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Pat the chicken breast dry and season with sea salt.", "type": "prep", "active": true, "appliance": null, "duration_min": 2, "ingredient_refs": ["chicken breast, broilers or fryers, raw", "sea salt"]}, {"n": 2, "temp": {"unit": "C", "value": 74}, "text": "Heat a drizzle of the olive oil in a pan over medium-high and cook the chicken 5-6 minutes per side, until golden and cooked through (74°C internal).", "type": "cook", "active": false, "appliance": "stovetop", "duration_min": 12, "ingredient_refs": ["chicken breast, broilers or fryers, raw", "olive oil"]}, {"n": 3, "temp": null, "text": "Rest the chicken 3 minutes, then slice.", "type": "rest", "active": false, "appliance": null, "duration_min": 3, "ingredient_refs": ["chicken breast, broilers or fryers, raw"]}], "title": "Cook the chicken"}, {"steps": [{"n": 4, "temp": null, "text": "Chop the romaine and add to a bowl.", "type": "prep", "active": true, "appliance": null, "duration_min": 2, "ingredient_refs": ["romaine lettuce"]}, {"n": 5, "temp": null, "text": "Whisk the remaining olive oil with lemon juice and dijon mustard; toss with the romaine.", "type": "assemble", "active": true, "appliance": null, "duration_min": 2, "ingredient_refs": ["olive oil", "lemon juice, raw", "dijon mustard"]}, {"n": 6, "temp": null, "text": "Top with the sliced chicken and shaved parmesan.", "type": "assemble", "active": true, "appliance": null, "duration_min": 1, "ingredient_refs": ["chicken breast, broilers or fryers, raw", "parmesan cheese"]}], "title": "Assemble"}], "make_ahead": "Cook the chicken up to 3 days ahead; keep dressing separate.", "cook_time_min": 15, "prep_time_min": 5, "total_time_min": 20, "yield_servings": 1}'::jsonb where id='8edf4513-5589-4f1f-b695-ad1ab4088c8f' and user_id is null;

-- Keto Cobb Salad
update recipes set recipe_kind='assembly', instructions='{"reheat": "Serve cold.", "storage": "Store undressed up to 2 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Chop the romaine and add to a bowl with the diced avocado.", "type": "prep", "active": true, "appliance": null, "duration_min": 3, "ingredient_refs": ["romaine lettuce", "avocado, raw"]}, {"n": 2, "temp": null, "text": "Slice the hard-boiled egg and crumble the pan-fried bacon over the top; add the roasted chicken and cheddar.", "type": "prep", "active": true, "appliance": null, "duration_min": 3, "ingredient_refs": ["egg, whole, hard-boiled", "bacon, cured, pan-fried", "chicken breast, broilers or fryers, cooked, roasted", "cheddar cheese"]}, {"n": 3, "temp": null, "text": "Drizzle with olive oil and serve.", "type": "assemble", "active": true, "appliance": null, "duration_min": 1, "ingredient_refs": ["olive oil"]}], "title": "Assemble"}], "make_ahead": "Use pre-cooked chicken, bacon, and eggs; assemble when ready.", "cook_time_min": 0, "prep_time_min": 8, "total_time_min": 8, "yield_servings": 1}'::jsonb where id='36c93f36-9df7-4395-987d-81887fe6401f' and user_id is null;

-- Keto Egg Salad Lettuce Cups
update recipes set recipe_kind='assembly', instructions='{"reheat": "Serve cold.", "storage": "Store the egg salad up to 2 days refrigerated; fill the cups fresh.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Chop the hard-boiled eggs and mix with dijon mustard and olive oil; season with sea salt and black pepper.", "type": "prep", "active": true, "appliance": null, "duration_min": 5, "ingredient_refs": ["egg, whole, hard-boiled", "dijon mustard", "olive oil", "sea salt", "black pepper, ground"]}, {"n": 2, "temp": null, "text": "Spoon the egg salad into romaine leaves to serve as cups.", "type": "assemble", "active": true, "appliance": null, "duration_min": 2, "ingredient_refs": ["romaine lettuce"]}], "title": "Assemble"}], "make_ahead": "Make the egg salad up to 2 days ahead.", "cook_time_min": 0, "prep_time_min": 7, "total_time_min": 7, "yield_servings": 1}'::jsonb where id='3fe666d7-29e0-4014-9e5f-a4f09ffea8f4' and user_id is null;

-- Keto Greek Salad with Feta
update recipes set recipe_kind='assembly', instructions='{"reheat": "Serve cold.", "storage": "Store undressed up to 2 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Slice the cucumber and halve the cherry tomatoes; add to a bowl with the arugula.", "type": "prep", "active": true, "appliance": null, "duration_min": 4, "ingredient_refs": ["cucumber, raw", "tomatoes, cherry", "arugula, raw"]}, {"n": 2, "temp": null, "text": "Crumble over the feta, then dress with olive oil and balsamic vinegar.", "type": "assemble", "active": true, "appliance": null, "duration_min": 3, "ingredient_refs": ["feta cheese", "olive oil", "balsamic vinegar"]}], "title": "Assemble"}], "make_ahead": "Prep the vegetables up to 2 days ahead.", "cook_time_min": 0, "prep_time_min": 7, "total_time_min": 7, "yield_servings": 1}'::jsonb where id='a1870bc9-7f35-4ec4-8409-a5f3cd266f4f' and user_id is null;

-- Keto Lamb Feta Salad
update recipes set recipe_kind='cooked', instructions='{"reheat": "Serve cold or gently warm the lamb.", "storage": "Store undressed up to 3 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Season the lamb chop with sea salt.", "type": "prep", "active": true, "appliance": null, "duration_min": 1, "ingredient_refs": ["lamb, rib chop, lean, raw", "sea salt"]}, {"n": 2, "temp": null, "text": "Sear the lamb in a little olive oil over medium-high, 3-4 minutes per side for medium; rest 3 minutes and slice.", "type": "cook", "active": false, "appliance": "stovetop", "duration_min": 10, "ingredient_refs": ["lamb, rib chop, lean, raw", "olive oil"]}], "title": "Cook the lamb"}, {"steps": [{"n": 3, "temp": null, "text": "Add the mixed greens, cucumber, and crumbled feta to a bowl.", "type": "prep", "active": true, "appliance": null, "duration_min": 3, "ingredient_refs": ["mixed greens", "cucumber, raw", "feta cheese"]}, {"n": 4, "temp": null, "text": "Dress with the remaining olive oil and lemon juice, then top with the sliced lamb.", "type": "assemble", "active": true, "appliance": null, "duration_min": 2, "ingredient_refs": ["olive oil", "lemon juice, raw", "lamb, rib chop, lean, raw"]}], "title": "Assemble"}], "make_ahead": "Cook the lamb up to 3 days ahead.", "cook_time_min": 10, "prep_time_min": 6, "total_time_min": 16, "yield_servings": 1}'::jsonb where id='88855d7c-91ff-4483-8510-5253008dea95' and user_id is null;

-- Keto Salmon Spinach Salad
update recipes set recipe_kind='cooked', instructions='{"reheat": "Serve cold or gently warm the salmon.", "storage": "Store undressed up to 2 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Season the salmon with sea salt.", "type": "prep", "active": true, "appliance": null, "duration_min": 1, "ingredient_refs": ["salmon, atlantic, farmed, raw", "sea salt"]}, {"n": 2, "temp": null, "text": "Pan-sear the salmon in a little olive oil over medium-high, about 4 minutes per side, until it flakes easily.", "type": "cook", "active": false, "appliance": "stovetop", "duration_min": 10, "ingredient_refs": ["salmon, atlantic, farmed, raw", "olive oil"]}], "title": "Cook the salmon"}, {"steps": [{"n": 3, "temp": null, "text": "Add the spinach and sliced avocado to a bowl.", "type": "prep", "active": true, "appliance": null, "duration_min": 2, "ingredient_refs": ["spinach, raw", "avocado, raw"]}, {"n": 4, "temp": null, "text": "Dress with the remaining olive oil and lemon juice and top with the salmon.", "type": "assemble", "active": true, "appliance": null, "duration_min": 2, "ingredient_refs": ["olive oil", "lemon juice, raw", "salmon, atlantic, farmed, raw"]}], "title": "Assemble"}], "make_ahead": "Cook the salmon up to 2 days ahead.", "cook_time_min": 10, "prep_time_min": 5, "total_time_min": 15, "yield_servings": 1}'::jsonb where id='aabe5746-25e5-4143-b17c-12c188e1eb60' and user_id is null;

-- Keto Tuna Avocado Salad
update recipes set recipe_kind='assembly', instructions='{"reheat": "Serve cold.", "storage": "Eat immediately once dressed; avocado browns over time.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Drain the tuna and add to a bowl.", "type": "prep", "active": true, "appliance": null, "duration_min": 1, "ingredient_refs": ["tuna, canned in water, drained"]}, {"n": 2, "temp": null, "text": "Dice the avocado and cucumber and chop the romaine; add to the bowl.", "type": "prep", "active": true, "appliance": null, "duration_min": 4, "ingredient_refs": ["avocado, raw", "cucumber, raw", "romaine lettuce"]}, {"n": 3, "temp": null, "text": "Drizzle with olive oil and lemon juice and toss gently to combine.", "type": "assemble", "active": true, "appliance": null, "duration_min": 2, "ingredient_refs": ["olive oil", "lemon juice, raw"]}], "title": "Assemble"}], "make_ahead": "Best assembled fresh; prep the cucumber and romaine up to 2 days ahead.", "cook_time_min": 0, "prep_time_min": 8, "total_time_min": 8, "yield_servings": 1}'::jsonb where id='652898a6-2bf9-4355-b6e3-4cb9e884757b' and user_id is null;

-- Mediterranean Chicken Quinoa Salad
update recipes set recipe_kind='cooked', instructions='{"reheat": "Serve cold or warm the chicken.", "storage": "Store undressed up to 3 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Season the chicken with sea salt.", "type": "prep", "active": true, "appliance": null, "duration_min": 1, "ingredient_refs": ["chicken breast, broilers or fryers, raw"]}, {"n": 2, "temp": {"unit": "C", "value": 74}, "text": "Cook the chicken in a little olive oil over medium-high, 5-6 minutes per side (74°C internal); rest 3 minutes and slice.", "type": "cook", "active": false, "appliance": "stovetop", "duration_min": 15, "ingredient_refs": ["chicken breast, broilers or fryers, raw", "olive oil"]}], "title": "Cook the chicken"}, {"steps": [{"n": 3, "temp": null, "text": "Add the cooked quinoa, cherry tomatoes, cucumber, and feta to a bowl.", "type": "prep", "active": true, "appliance": null, "duration_min": 3, "ingredient_refs": ["quinoa, cooked", "tomatoes, cherry", "cucumber, raw", "feta cheese"]}, {"n": 4, "temp": null, "text": "Dress with the remaining olive oil and lemon juice and top with the sliced chicken.", "type": "assemble", "active": true, "appliance": null, "duration_min": 2, "ingredient_refs": ["olive oil", "lemon juice, raw", "chicken breast, broilers or fryers, raw"]}], "title": "Assemble"}], "make_ahead": "Cook the chicken and quinoa up to 3 days ahead.", "cook_time_min": 15, "prep_time_min": 5, "total_time_min": 20, "yield_servings": 1}'::jsonb where id='3ce7b934-c63f-44a3-be50-184a5ffbecca' and user_id is null;

-- Mediterranean Quinoa Veggie Salad
update recipes set recipe_kind='assembly', instructions='{"reheat": "Serve cold.", "storage": "Keeps up to 3 days refrigerated; great for meal prep.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Add the cooked quinoa and drained chickpeas to a bowl.", "type": "prep", "active": true, "appliance": null, "duration_min": 2, "ingredient_refs": ["quinoa, cooked", "chickpeas, mature seeds, canned, drained"]}, {"n": 2, "temp": null, "text": "Dice the cucumber and tomatoes and add with the crumbled feta.", "type": "prep", "active": true, "appliance": null, "duration_min": 3, "ingredient_refs": ["cucumber, raw", "tomatoes, raw", "feta cheese"]}, {"n": 3, "temp": null, "text": "Dress with olive oil and lemon juice and toss.", "type": "assemble", "active": true, "appliance": null, "duration_min": 2, "ingredient_refs": ["olive oil", "lemon juice, raw"]}], "title": "Assemble"}], "make_ahead": "Cook the quinoa up to 3 days ahead.", "cook_time_min": 0, "prep_time_min": 7, "total_time_min": 7, "yield_servings": 1}'::jsonb where id='a65096b7-0cce-4cd5-a9df-ca8669111cb1' and user_id is null;

-- Mediterranean Salmon Arugula Salad
update recipes set recipe_kind='cooked', instructions='{"reheat": "Serve cold.", "storage": "Store undressed up to 2 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Season the salmon with sea salt.", "type": "prep", "active": true, "appliance": null, "duration_min": 1, "ingredient_refs": ["salmon, atlantic, farmed, raw", "sea salt"]}, {"n": 2, "temp": null, "text": "Pan-sear the salmon in a little olive oil over medium-high, about 4 minutes per side, until it flakes easily.", "type": "cook", "active": false, "appliance": "stovetop", "duration_min": 10, "ingredient_refs": ["salmon, atlantic, farmed, raw", "olive oil"]}], "title": "Cook the salmon"}, {"steps": [{"n": 3, "temp": null, "text": "Add the arugula and cherry tomatoes to a bowl and scatter over the feta.", "type": "prep", "active": true, "appliance": null, "duration_min": 2, "ingredient_refs": ["arugula, raw", "tomatoes, cherry", "feta cheese"]}, {"n": 4, "temp": null, "text": "Dress with the remaining olive oil and balsamic vinegar and top with the salmon.", "type": "assemble", "active": true, "appliance": null, "duration_min": 2, "ingredient_refs": ["olive oil", "balsamic vinegar", "salmon, atlantic, farmed, raw"]}], "title": "Assemble"}], "make_ahead": "Cook the salmon up to 2 days ahead.", "cook_time_min": 10, "prep_time_min": 5, "total_time_min": 15, "yield_servings": 1}'::jsonb where id='d4fd2343-c6cf-4547-914d-847525d2387c' and user_id is null;

-- Mediterranean Shrimp Tuna Salad
update recipes set recipe_kind='cooked', instructions='{"reheat": "Serve cold.", "storage": "Store undressed up to 2 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Pat the shrimp dry and season lightly.", "type": "prep", "active": true, "appliance": null, "duration_min": 1, "ingredient_refs": ["shrimp, raw"]}, {"n": 2, "temp": null, "text": "Saute the shrimp in a little olive oil over medium-high, 2-3 minutes per side, until pink and opaque.", "type": "cook", "active": false, "appliance": "stovetop", "duration_min": 6, "ingredient_refs": ["shrimp, raw", "olive oil"]}], "title": "Cook the shrimp"}, {"steps": [{"n": 3, "temp": null, "text": "Add the mixed greens and cherry tomatoes to a bowl, drain and flake in the tuna, and scatter over the feta.", "type": "prep", "active": true, "appliance": null, "duration_min": 3, "ingredient_refs": ["mixed greens", "tomatoes, cherry", "tuna, canned in water, drained", "feta cheese"]}, {"n": 4, "temp": null, "text": "Dress with the remaining olive oil and lemon juice and top with the shrimp.", "type": "assemble", "active": true, "appliance": null, "duration_min": 2, "ingredient_refs": ["olive oil", "lemon juice, raw", "shrimp, raw"]}], "title": "Assemble"}], "make_ahead": "Cook the shrimp up to 1 day ahead.", "cook_time_min": 6, "prep_time_min": 5, "total_time_min": 11, "yield_servings": 1}'::jsonb where id='8664e9d2-c219-4cca-a77e-5082ad1c9f1f' and user_id is null;

-- Mediterranean Tuna Olive Salad
update recipes set recipe_kind='assembly', instructions='{"reheat": "Serve cold.", "storage": "Keeps up to 2 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Add the mixed greens to a bowl and drain and flake in the tuna.", "type": "prep", "active": true, "appliance": null, "duration_min": 2, "ingredient_refs": ["mixed greens", "tuna, canned in water, drained"]}, {"n": 2, "temp": null, "text": "Dice the cucumber and halve the cherry tomatoes; add to the bowl.", "type": "prep", "active": true, "appliance": null, "duration_min": 3, "ingredient_refs": ["cucumber, raw", "tomatoes, cherry"]}, {"n": 3, "temp": null, "text": "Dress with olive oil and lemon juice, season with sea salt, and toss.", "type": "assemble", "active": true, "appliance": null, "duration_min": 2, "ingredient_refs": ["olive oil", "lemon juice, raw", "sea salt"]}], "title": "Assemble"}], "make_ahead": "Prep the vegetables up to 2 days ahead.", "cook_time_min": 0, "prep_time_min": 7, "total_time_min": 7, "yield_servings": 1}'::jsonb where id='0c302d42-7e74-40d8-ba6a-c0d4968a42a4' and user_id is null;

-- Paleo Beef and Beet Salad
update recipes set recipe_kind='cooked', instructions='{"reheat": "Serve cold or gently warm the beef.", "storage": "Store undressed up to 3 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Season the sirloin with sea salt.", "type": "prep", "active": true, "appliance": null, "duration_min": 1, "ingredient_refs": ["beef, sirloin steak, lean, raw", "sea salt"]}, {"n": 2, "temp": null, "text": "Sear the steak in a little olive oil over medium-high, 3-4 minutes per side for medium; rest 5 minutes and slice thin.", "type": "cook", "active": false, "appliance": "stovetop", "duration_min": 10, "ingredient_refs": ["beef, sirloin steak, lean, raw", "olive oil"]}], "title": "Cook the beef"}, {"steps": [{"n": 3, "temp": null, "text": "Add the arugula and sliced beets to a bowl and scatter over the walnuts.", "type": "prep", "active": true, "appliance": null, "duration_min": 3, "ingredient_refs": ["arugula, raw", "beets, raw", "walnuts, raw"]}, {"n": 4, "temp": null, "text": "Dress with the remaining olive oil and balsamic vinegar and top with the sliced beef.", "type": "assemble", "active": true, "appliance": null, "duration_min": 2, "ingredient_refs": ["olive oil", "balsamic vinegar", "beef, sirloin steak, lean, raw"]}], "title": "Assemble"}], "make_ahead": "Cook the beef up to 3 days ahead.", "cook_time_min": 10, "prep_time_min": 6, "total_time_min": 16, "yield_servings": 1}'::jsonb where id='0d65cc35-d149-4965-ad43-a46711bb04ec' and user_id is null;

-- Paleo Mango Chicken Salad
update recipes set recipe_kind='cooked', instructions='{"reheat": "Serve cold.", "storage": "Store undressed up to 3 days refrigerated; add mango and avocado fresh.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Season the chicken with a pinch of salt.", "type": "prep", "active": true, "appliance": null, "duration_min": 1, "ingredient_refs": ["chicken breast, broilers or fryers, raw"]}, {"n": 2, "temp": {"unit": "C", "value": 74}, "text": "Cook the chicken in a little olive oil over medium-high, 5-6 minutes per side (74°C internal); rest and slice.", "type": "cook", "active": false, "appliance": "stovetop", "duration_min": 15, "ingredient_refs": ["chicken breast, broilers or fryers, raw", "olive oil"]}], "title": "Cook the chicken"}, {"steps": [{"n": 3, "temp": null, "text": "Add the mixed greens, diced mango, and avocado to a bowl.", "type": "prep", "active": true, "appliance": null, "duration_min": 3, "ingredient_refs": ["mixed greens", "mango, raw", "avocado, raw"]}, {"n": 4, "temp": null, "text": "Dress with the remaining olive oil and lemon juice and top with the sliced chicken.", "type": "assemble", "active": true, "appliance": null, "duration_min": 2, "ingredient_refs": ["olive oil", "lemon juice, raw", "chicken breast, broilers or fryers, raw"]}], "title": "Assemble"}], "make_ahead": "Cook the chicken up to 3 days ahead.", "cook_time_min": 15, "prep_time_min": 5, "total_time_min": 20, "yield_servings": 1}'::jsonb where id='08cf6890-3d30-448d-8e93-cdec1150d211' and user_id is null;

-- Paleo Pork Apple Salad
update recipes set recipe_kind='cooked', instructions='{"reheat": "Serve cold or gently warm the pork.", "storage": "Store undressed up to 3 days refrigerated; add apple fresh.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Season the pork tenderloin with sea salt.", "type": "prep", "active": true, "appliance": null, "duration_min": 1, "ingredient_refs": ["pork tenderloin, raw", "sea salt"]}, {"n": 2, "temp": {"unit": "C", "value": 63}, "text": "Sear the pork in a little olive oil, then cook through over medium, about 15 minutes total (63°C internal); rest 5 minutes and slice.", "type": "cook", "active": false, "appliance": "stovetop", "duration_min": 18, "ingredient_refs": ["pork tenderloin, raw", "olive oil"]}], "title": "Cook the pork"}, {"steps": [{"n": 3, "temp": null, "text": "Add the mixed greens and sliced apple to a bowl and scatter over the walnuts.", "type": "prep", "active": true, "appliance": null, "duration_min": 3, "ingredient_refs": ["mixed greens", "apples, raw", "walnuts, raw"]}, {"n": 4, "temp": null, "text": "Dress with the remaining olive oil and balsamic vinegar and top with the sliced pork.", "type": "assemble", "active": true, "appliance": null, "duration_min": 2, "ingredient_refs": ["olive oil", "balsamic vinegar", "pork tenderloin, raw"]}], "title": "Assemble"}], "make_ahead": "Cook the pork up to 3 days ahead.", "cook_time_min": 18, "prep_time_min": 5, "total_time_min": 23, "yield_servings": 1}'::jsonb where id='a0e0db5e-0d9c-4e52-a382-33629a2ca21e' and user_id is null;

-- Paleo Salmon Avocado Mixed Green Salad
update recipes set recipe_kind='cooked', instructions='{"reheat": "Serve cold.", "storage": "Store undressed up to 2 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Season the salmon with sea salt.", "type": "prep", "active": true, "appliance": null, "duration_min": 1, "ingredient_refs": ["salmon, atlantic, farmed, raw", "sea salt"]}, {"n": 2, "temp": null, "text": "Pan-sear the salmon in a little olive oil, about 4 minutes per side, until it flakes easily.", "type": "cook", "active": false, "appliance": "stovetop", "duration_min": 10, "ingredient_refs": ["salmon, atlantic, farmed, raw", "olive oil"]}], "title": "Cook the salmon"}, {"steps": [{"n": 3, "temp": null, "text": "Add the mixed greens and sliced avocado to a bowl.", "type": "prep", "active": true, "appliance": null, "duration_min": 2, "ingredient_refs": ["mixed greens", "avocado, raw"]}, {"n": 4, "temp": null, "text": "Dress with the remaining olive oil and lemon juice and top with the salmon.", "type": "assemble", "active": true, "appliance": null, "duration_min": 2, "ingredient_refs": ["olive oil", "lemon juice, raw", "salmon, atlantic, farmed, raw"]}], "title": "Assemble"}], "make_ahead": "Cook the salmon up to 2 days ahead.", "cook_time_min": 10, "prep_time_min": 4, "total_time_min": 14, "yield_servings": 1}'::jsonb where id='0e53d85b-138c-4d15-9f40-9961a5393653' and user_id is null;

-- Paleo Shrimp and Vegetable Salad
update recipes set recipe_kind='cooked', instructions='{"reheat": "Serve cold.", "storage": "Store undressed up to 2 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Pat the shrimp dry.", "type": "prep", "active": true, "appliance": null, "duration_min": 1, "ingredient_refs": ["shrimp, raw"]}, {"n": 2, "temp": null, "text": "Saute the shrimp in a little olive oil over medium-high, 2-3 minutes per side, until pink and opaque.", "type": "cook", "active": false, "appliance": "stovetop", "duration_min": 6, "ingredient_refs": ["shrimp, raw", "olive oil"]}], "title": "Cook the shrimp"}, {"steps": [{"n": 3, "temp": null, "text": "Add the mixed greens, sliced avocado, and grated carrot to a bowl.", "type": "prep", "active": true, "appliance": null, "duration_min": 3, "ingredient_refs": ["mixed greens", "avocado, raw", "carrots, raw"]}, {"n": 4, "temp": null, "text": "Dress with the remaining olive oil and lemon juice, season with sea salt, and top with the shrimp.", "type": "assemble", "active": true, "appliance": null, "duration_min": 2, "ingredient_refs": ["olive oil", "lemon juice, raw", "sea salt", "shrimp, raw"]}], "title": "Assemble"}], "make_ahead": "Cook the shrimp up to 1 day ahead.", "cook_time_min": 6, "prep_time_min": 5, "total_time_min": 11, "yield_servings": 1}'::jsonb where id='11cf8edf-f692-468a-838c-f72224138c32' and user_id is null;

-- Pescatarian Cod Kale Salad
update recipes set recipe_kind='cooked', instructions='{"reheat": "Serve cold or gently warm the cod.", "storage": "Store undressed up to 2 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Season the cod with sea salt.", "type": "prep", "active": true, "appliance": null, "duration_min": 1, "ingredient_refs": ["cod, atlantic, raw", "sea salt"]}, {"n": 2, "temp": null, "text": "Pan-sear the cod in a little olive oil, about 3-4 minutes per side, until it flakes easily.", "type": "cook", "active": false, "appliance": "stovetop", "duration_min": 10, "ingredient_refs": ["cod, atlantic, raw", "olive oil"]}], "title": "Cook the cod"}, {"steps": [{"n": 3, "temp": null, "text": "Massage the kale with a little olive oil, then add to a bowl with the sliced avocado.", "type": "prep", "active": true, "appliance": null, "duration_min": 3, "ingredient_refs": ["kale, raw", "olive oil", "avocado, raw"]}, {"n": 4, "temp": null, "text": "Dress with lemon juice, season with sea salt, and top with the cod.", "type": "assemble", "active": true, "appliance": null, "duration_min": 2, "ingredient_refs": ["lemon juice, raw", "sea salt", "cod, atlantic, raw"]}], "title": "Assemble"}], "make_ahead": "Cook the cod up to 1 day ahead.", "cook_time_min": 10, "prep_time_min": 4, "total_time_min": 14, "yield_servings": 1}'::jsonb where id='268af380-8753-4eaf-8ea6-ef0dea66f4f1' and user_id is null;

-- Pescatarian Halibut Quinoa Salad
update recipes set recipe_kind='cooked', instructions='{"reheat": "Serve cold.", "storage": "Store undressed up to 2 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Season the halibut with sea salt.", "type": "prep", "active": true, "appliance": null, "duration_min": 1, "ingredient_refs": ["halibut, atlantic, raw", "sea salt"]}, {"n": 2, "temp": null, "text": "Pan-sear the halibut in a little olive oil, about 4 minutes per side, until it flakes easily.", "type": "cook", "active": false, "appliance": "stovetop", "duration_min": 10, "ingredient_refs": ["halibut, atlantic, raw", "olive oil"]}], "title": "Cook the halibut"}, {"steps": [{"n": 3, "temp": null, "text": "Add the cooked quinoa and arugula to a bowl.", "type": "prep", "active": true, "appliance": null, "duration_min": 2, "ingredient_refs": ["quinoa, cooked", "arugula, raw"]}, {"n": 4, "temp": null, "text": "Dress with the remaining olive oil and lemon juice, season with sea salt, and top with the halibut.", "type": "assemble", "active": true, "appliance": null, "duration_min": 2, "ingredient_refs": ["olive oil", "lemon juice, raw", "sea salt", "halibut, atlantic, raw"]}], "title": "Assemble"}], "make_ahead": "Cook the halibut and quinoa up to 2 days ahead.", "cook_time_min": 10, "prep_time_min": 4, "total_time_min": 14, "yield_servings": 1}'::jsonb where id='16007356-a468-415f-ac68-6dd3b0e17862' and user_id is null;

-- Pescatarian Shrimp Avocado Salad
update recipes set recipe_kind='cooked', instructions='{"reheat": "Serve cold.", "storage": "Store undressed up to 2 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Pat the shrimp dry.", "type": "prep", "active": true, "appliance": null, "duration_min": 1, "ingredient_refs": ["shrimp, raw"]}, {"n": 2, "temp": null, "text": "Saute the shrimp in a little olive oil over medium-high, 2-3 minutes per side, until pink and opaque.", "type": "cook", "active": false, "appliance": "stovetop", "duration_min": 6, "ingredient_refs": ["shrimp, raw", "olive oil"]}], "title": "Cook the shrimp"}, {"steps": [{"n": 3, "temp": null, "text": "Add the mixed greens, sliced avocado, and cucumber to a bowl.", "type": "prep", "active": true, "appliance": null, "duration_min": 3, "ingredient_refs": ["mixed greens", "avocado, raw", "cucumber, raw"]}, {"n": 4, "temp": null, "text": "Dress with the remaining olive oil and lemon juice, season with sea salt, and top with the shrimp.", "type": "assemble", "active": true, "appliance": null, "duration_min": 2, "ingredient_refs": ["olive oil", "lemon juice, raw", "sea salt", "shrimp, raw"]}], "title": "Assemble"}], "make_ahead": "Cook the shrimp up to 1 day ahead.", "cook_time_min": 6, "prep_time_min": 5, "total_time_min": 11, "yield_servings": 1}'::jsonb where id='d9ce87f3-a0eb-4bab-98ff-5aef748d2cad' and user_id is null;

-- Pescatarian Tuna Mediterranean Salad
update recipes set recipe_kind='assembly', instructions='{"reheat": "Serve cold.", "storage": "Keeps up to 2 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Add the mixed greens to a bowl and drain and flake in the tuna.", "type": "prep", "active": true, "appliance": null, "duration_min": 2, "ingredient_refs": ["mixed greens", "tuna, canned in water, drained"]}, {"n": 2, "temp": null, "text": "Halve the cherry tomatoes and dice the cucumber; add with the crumbled feta.", "type": "prep", "active": true, "appliance": null, "duration_min": 3, "ingredient_refs": ["tomatoes, cherry", "cucumber, raw", "feta cheese"]}, {"n": 3, "temp": null, "text": "Dress with olive oil and lemon juice and toss.", "type": "assemble", "active": true, "appliance": null, "duration_min": 2, "ingredient_refs": ["olive oil", "lemon juice, raw"]}], "title": "Assemble"}], "make_ahead": "Prep the vegetables up to 2 days ahead.", "cook_time_min": 0, "prep_time_min": 7, "total_time_min": 7, "yield_servings": 1}'::jsonb where id='c0e5ed24-a7d5-444e-8d17-7a761540ed01' and user_id is null;

-- Tuna Nicoise Salad
update recipes set recipe_kind='assembly', instructions='{"reheat": "Serve cold.", "storage": "Store undressed up to 2 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Blanch the green beans briefly if desired, then add to a plate with the halved cherry tomatoes.", "type": "prep", "active": true, "appliance": null, "duration_min": 4, "ingredient_refs": ["green beans, raw", "tomatoes, cherry"]}, {"n": 2, "temp": null, "text": "Drain the tuna and arrange on the plate with the sliced hard-boiled egg.", "type": "prep", "active": true, "appliance": null, "duration_min": 4, "ingredient_refs": ["tuna, canned in water, drained", "egg, whole, hard-boiled"]}, {"n": 3, "temp": null, "text": "Drizzle with olive oil and lemon juice to serve.", "type": "assemble", "active": true, "appliance": null, "duration_min": 2, "ingredient_refs": ["olive oil", "lemon juice, raw"]}], "title": "Assemble"}], "make_ahead": "Use pre-boiled eggs; assemble when ready.", "cook_time_min": 0, "prep_time_min": 10, "total_time_min": 10, "yield_servings": 1}'::jsonb where id='4cc66a9e-08e3-480f-b6e0-76b577cec8c1' and user_id is null;

-- Tuna Quinoa Protein Salad
update recipes set recipe_kind='assembly', instructions='{"reheat": "Serve cold.", "storage": "Keeps up to 3 days refrigerated; great for meal prep.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Add the cooked quinoa to a bowl and drain and flake in the tuna.", "type": "prep", "active": true, "appliance": null, "duration_min": 2, "ingredient_refs": ["quinoa, cooked", "tuna, canned in water, drained"]}, {"n": 2, "temp": null, "text": "Dice the cucumber and tomatoes and add to the bowl.", "type": "prep", "active": true, "appliance": null, "duration_min": 3, "ingredient_refs": ["cucumber, raw", "tomatoes, raw"]}, {"n": 3, "temp": null, "text": "Dress with olive oil and lemon juice and toss.", "type": "assemble", "active": true, "appliance": null, "duration_min": 2, "ingredient_refs": ["olive oil", "lemon juice, raw"]}], "title": "Assemble"}], "make_ahead": "Cook the quinoa up to 3 days ahead.", "cook_time_min": 0, "prep_time_min": 7, "total_time_min": 7, "yield_servings": 1}'::jsonb where id='2aea4ac3-030e-4978-af4f-d84a187bb017' and user_id is null;

-- Vegan Chickpea Avocado Salad
update recipes set recipe_kind='assembly', instructions='{"reheat": "Serve cold.", "storage": "Eat immediately once dressed; avocado browns over time.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Drain and rinse the chickpeas and add to a bowl.", "type": "prep", "active": true, "appliance": null, "duration_min": 2, "ingredient_refs": ["chickpeas, mature seeds, canned, drained"]}, {"n": 2, "temp": null, "text": "Dice the avocado, cucumber, and cherry tomatoes; add to the bowl.", "type": "prep", "active": true, "appliance": null, "duration_min": 4, "ingredient_refs": ["avocado, raw", "cucumber, raw", "tomatoes, cherry"]}, {"n": 3, "temp": null, "text": "Drizzle with olive oil and lemon juice, season with sea salt, and toss gently.", "type": "assemble", "active": true, "appliance": null, "duration_min": 2, "ingredient_refs": ["olive oil", "lemon juice, raw", "sea salt"]}], "title": "Assemble"}], "make_ahead": "Prep the vegetables up to 2 days ahead; combine when ready.", "cook_time_min": 0, "prep_time_min": 8, "total_time_min": 8, "yield_servings": 1}'::jsonb where id='e5ad9a3a-cc2e-4c74-8679-2e147476d431' and user_id is null;

-- Vegan Edamame Quinoa Salad
update recipes set recipe_kind='assembly', instructions='{"reheat": "Serve cold.", "storage": "Keeps up to 3 days refrigerated; great for meal prep.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Add the cooked quinoa and edamame to a bowl.", "type": "prep", "active": true, "appliance": null, "duration_min": 2, "ingredient_refs": ["quinoa, cooked", "edamame, frozen, prepared"]}, {"n": 2, "temp": null, "text": "Dice the cucumber and grate in a little fresh ginger; add to the bowl.", "type": "prep", "active": true, "appliance": null, "duration_min": 3, "ingredient_refs": ["cucumber, raw", "ginger root, raw"]}, {"n": 3, "temp": null, "text": "Whisk the sesame oil, soy sauce, and lemon juice and toss through.", "type": "assemble", "active": true, "appliance": null, "duration_min": 2, "ingredient_refs": ["sesame oil", "soy sauce", "lemon juice, raw"]}], "title": "Assemble"}], "make_ahead": "Cook the quinoa and edamame up to 3 days ahead.", "cook_time_min": 0, "prep_time_min": 7, "total_time_min": 7, "yield_servings": 1}'::jsonb where id='6601b1c9-9f48-4350-a024-9b2fd7b3a6f9' and user_id is null;

-- Vegan Lentil Mango Salad
update recipes set recipe_kind='assembly', instructions='{"reheat": "Serve cold.", "storage": "Keeps up to 2 days refrigerated; add mango fresh.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Add the cooked lentils and arugula to a bowl.", "type": "prep", "active": true, "appliance": null, "duration_min": 2, "ingredient_refs": ["lentils, mature seeds, cooked, boiled", "arugula, raw"]}, {"n": 2, "temp": null, "text": "Dice the mango and add to the bowl.", "type": "prep", "active": true, "appliance": null, "duration_min": 2, "ingredient_refs": ["mango, raw"]}, {"n": 3, "temp": null, "text": "Dress with olive oil and lemon juice, season with sea salt, and toss.", "type": "assemble", "active": true, "appliance": null, "duration_min": 2, "ingredient_refs": ["olive oil", "lemon juice, raw", "sea salt"]}], "title": "Assemble"}], "make_ahead": "Cook the lentils up to 3 days ahead.", "cook_time_min": 0, "prep_time_min": 6, "total_time_min": 6, "yield_servings": 1}'::jsonb where id='a2af4e1f-0ff1-45a4-8b95-5bf9d7057bbd' and user_id is null;

commit;
