-- ============================================================================
-- seed-cooking-guides-mains-4.sql — authored cooking guides, MAINS archetype (batch 4, 15 recipes)
-- ----------------------------------------------------------------------------
-- Git source of truth for content authored directly in the DB (instructions jsonb + recipe_kind
-- per recipe id). Content UPDATEs only — NOT schema. Idempotent (matches by id); re-runnable.
-- Same pattern + schema as the other seed-cooking-guides-*.sql files.
--
-- Regenerate from the live DB (swap the id-prefix filter for the batch):
--   select string_agg(format('-- %s', name) || E'\n' ||
--     format('update recipes set recipe_kind=%L, instructions=%L::jsonb where id=%L and user_id is null;',
--       recipe_kind, instructions::text, id::text), E'\n\n' order by name)
--   from recipes where user_id is null and instructions is not null and id::text like any(array['bca3f17b%', ...]);
--
-- Progress: 251 / 299 cooking guides authored (84%) — salads 26 + smoothies 6 + wraps 5 + soups 15 + bowls 77 + originals 5 + breakfast 57 + mains 60 (batches 1-4).
-- ============================================================================

begin;

-- Keto Pork Tenderloin Asparagus
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat gently.", "storage": "Keeps up to 3 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Mince the garlic. Trim the asparagus and saute in olive oil with the garlic until tender-crisp, about 8 minutes; season with sea salt and black pepper.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 8, "ingredient_refs": ["garlic, raw", "asparagus, raw", "olive oil", "sea salt", "black pepper, ground"]}, {"n": 2, "temp": {"unit": "C", "value": 63}, "text": "Season the pork and sear, then cook through over medium about 12 minutes (63°C internal); rest and slice.", "type": "cook", "active": false, "appliance": "stovetop", "duration_min": 12, "ingredient_refs": ["pork tenderloin, raw"]}], "title": "Cook"}], "make_ahead": "Cook up to 3 days ahead.", "cook_time_min": 20, "prep_time_min": 5, "total_time_min": 25, "yield_servings": 1}'::jsonb where id='bca3f17b-e39a-492a-9d12-14e9fdcca269' and user_id is null;

-- Keto Pork Tenderloin Cream Sauce
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat gently.", "storage": "Keeps up to 3 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": {"unit": "C", "value": 63}, "text": "Season the pork with sea salt and black pepper and sear all over, then cook through over medium about 12 minutes (63°C internal); rest and slice.", "type": "cook", "active": false, "appliance": "stovetop", "duration_min": 15, "ingredient_refs": ["pork tenderloin, raw", "sea salt", "black pepper, ground"]}, {"n": 2, "temp": null, "text": "Mince the garlic and add to the pan with the heavy cream and rosemary; simmer into a sauce and spoon over the pork.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 5, "ingredient_refs": ["garlic, raw", "heavy cream", "rosemary, fresh"]}], "title": "Cook"}], "make_ahead": "Cook up to 3 days ahead.", "cook_time_min": 20, "prep_time_min": 4, "total_time_min": 24, "yield_servings": 1}'::jsonb where id='18ccd054-7551-4859-a1c9-34f66a046ffc' and user_id is null;

-- Keto Pork Tenderloin with Herb Cream
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat gently.", "storage": "Keeps up to 3 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": {"unit": "C", "value": 63}, "text": "Season the pork and sear in olive oil, then cook through over medium about 12 minutes (63°C internal); rest and slice.", "type": "cook", "active": false, "appliance": "stovetop", "duration_min": 15, "ingredient_refs": ["pork tenderloin, raw", "olive oil"]}, {"n": 2, "temp": null, "text": "Mince the garlic and add to the pan with the heavy cream and dijon; simmer, wilt in the spinach, and spoon the herb cream over the pork.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 5, "ingredient_refs": ["garlic, raw", "heavy cream", "dijon mustard", "spinach, raw"]}], "title": "Cook"}], "make_ahead": "Cook up to 3 days ahead.", "cook_time_min": 20, "prep_time_min": 5, "total_time_min": 25, "yield_servings": 1}'::jsonb where id='f29f2316-2266-4953-84b2-0fb72fab7371' and user_id is null;

-- Keto Pumpkin Seed Parmesan Mix
update recipes set recipe_kind='cooked', instructions='{"reheat": "Serve at room temperature.", "storage": "Keeps up to 1 week in an airtight container.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Toast the pumpkin seeds in a dry pan over medium until they pop and turn golden, about 5 minutes.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 5, "ingredient_refs": ["pumpkin seeds, raw"]}, {"n": 2, "temp": null, "text": "Off the heat, toss with the parmesan, sea salt, and paprika while warm so the cheese clings.", "type": "assemble", "active": true, "appliance": null, "duration_min": 3, "ingredient_refs": ["parmesan cheese", "sea salt", "paprika"]}], "title": "Toast"}], "make_ahead": "Make a batch ahead; keeps well.", "cook_time_min": 8, "prep_time_min": 3, "total_time_min": 11, "yield_servings": 1}'::jsonb where id='1bd85354-a705-4785-afb8-cffcf1b7e1e8' and user_id is null;

-- Keto Pumpkin Seed Snack Mix
update recipes set recipe_kind='cooked', instructions='{"reheat": "Serve at room temperature.", "storage": "Keeps up to 2 weeks in an airtight container.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Toast the pumpkin seeds, almonds, and sunflower seeds in a dry pan over medium, stirring, until golden and fragrant, about 6 minutes.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 6, "ingredient_refs": ["pumpkin seeds, raw", "almonds, raw", "sunflower seeds, raw"]}, {"n": 2, "temp": null, "text": "Toss with sea salt and let cool.", "type": "assemble", "active": true, "appliance": null, "duration_min": 1, "ingredient_refs": ["sea salt"]}], "title": "Toast"}], "make_ahead": "Make a batch ahead; keeps well.", "cook_time_min": 7, "prep_time_min": 2, "total_time_min": 9, "yield_servings": 1}'::jsonb where id='7f9de4a0-5d4d-4318-bb6b-474184723cc9' and user_id is null;

-- Keto Salmon Avocado Cream Dinner
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat gently; add avocado fresh.", "storage": "Keeps up to 1 day refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Mince the garlic. Season the salmon with sea salt and pan-sear about 4 minutes per side until it flakes; remove.", "type": "cook", "active": false, "appliance": "stovetop", "duration_min": 8, "ingredient_refs": ["garlic, raw", "salmon, atlantic, farmed, raw", "sea salt"]}, {"n": 2, "temp": null, "text": "Add the garlic and heavy cream to the pan with lemon juice and simmer to a sauce; serve over the salmon with sliced avocado.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 3, "ingredient_refs": ["heavy cream", "lemon juice, raw", "avocado, raw"]}], "title": "Cook"}], "make_ahead": "Best cooked fresh.", "cook_time_min": 11, "prep_time_min": 5, "total_time_min": 16, "yield_servings": 1}'::jsonb where id='2ec293c3-f9c7-4336-9391-099ab0c727ab' and user_id is null;

-- Keto Salmon Cucumber Rounds
update recipes set recipe_kind='assembly', instructions='{"reheat": "Serve cold.", "storage": "Keeps up to 1 day refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Slice the cucumber into thick rounds and spread each with cream cheese.", "type": "prep", "active": true, "appliance": null, "duration_min": 3, "ingredient_refs": ["cucumber, raw", "cream cheese"]}, {"n": 2, "temp": null, "text": "Top each with a piece of smoked salmon and season with sea salt.", "type": "assemble", "active": true, "appliance": null, "duration_min": 3, "ingredient_refs": ["smoked salmon", "sea salt"]}], "title": "Assemble"}], "make_ahead": "Assemble up to a few hours ahead.", "cook_time_min": 0, "prep_time_min": 6, "total_time_min": 6, "yield_servings": 1}'::jsonb where id='9dd2907a-0c45-46a8-aee0-50444af75ea6' and user_id is null;

-- Keto Salmon with Parmesan Cream Sauce
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat gently so the fish does not dry out.", "storage": "Keeps up to 1 day refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Mince the garlic. Season the salmon and pan-sear in olive oil about 4 minutes per side until it flakes; remove.", "type": "cook", "active": false, "appliance": "stovetop", "duration_min": 8, "ingredient_refs": ["garlic, raw", "salmon, atlantic, farmed, raw", "olive oil"]}, {"n": 2, "temp": null, "text": "Add the garlic, heavy cream, and parmesan to the pan and simmer to a sauce; wilt in the spinach and spoon over the salmon.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 4, "ingredient_refs": ["heavy cream", "parmesan cheese", "spinach, raw"]}], "title": "Cook"}], "make_ahead": "Best cooked fresh.", "cook_time_min": 12, "prep_time_min": 5, "total_time_min": 17, "yield_servings": 1}'::jsonb where id='70758f00-71f4-44c7-b798-05e78058f255' and user_id is null;

-- Keto Shrimp Scampi Zucchini Noodles
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat gently.", "storage": "Keeps up to 1 day refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Mince the garlic and saute the shrimp in olive oil with the garlic until pink, about 3 minutes; finish with lemon juice, sea salt, and black pepper and remove.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 5, "ingredient_refs": ["garlic, raw", "shrimp, raw", "olive oil", "lemon juice, raw", "sea salt", "black pepper, ground"]}, {"n": 2, "temp": null, "text": "Spiralize the zucchini into noodles and toss in the pan to just soften, about 3 minutes; return the shrimp.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 5, "ingredient_refs": ["zucchini, raw"]}], "title": "Cook"}], "make_ahead": "Best cooked fresh so the zucchini stays firm.", "cook_time_min": 10, "prep_time_min": 6, "total_time_min": 16, "yield_servings": 1}'::jsonb where id='b0b83e67-4a48-4801-88d8-292d131fc795' and user_id is null;

-- Keto Shrimp with Zucchini Noodles
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat gently.", "storage": "Keeps up to 1 day refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Mince the garlic and saute the shrimp in olive oil with the garlic until pink, about 3 minutes; remove.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 4, "ingredient_refs": ["garlic, raw", "shrimp, raw", "olive oil"]}, {"n": 2, "temp": null, "text": "Add the heavy cream and parmesan to the pan and simmer to a sauce; toss the spiralized zucchini to soften, then return the shrimp.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 7, "ingredient_refs": ["heavy cream", "parmesan cheese", "zucchini, raw"]}], "title": "Cook"}], "make_ahead": "Best cooked fresh so the zucchini stays firm.", "cook_time_min": 11, "prep_time_min": 6, "total_time_min": 17, "yield_servings": 1}'::jsonb where id='cb6b8e3c-9b17-44db-8b63-59dc7649aa4f' and user_id is null;

-- Keto Turkey Avocado Lettuce Cups
update recipes set recipe_kind='assembly', instructions='{"reheat": "Serve cold.", "storage": "Best eaten immediately.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Mash the avocado with dijon, sea salt, and black pepper.", "type": "prep", "active": true, "appliance": null, "duration_min": 3, "ingredient_refs": ["avocado, raw", "dijon mustard", "sea salt", "black pepper, ground"]}, {"n": 2, "temp": null, "text": "Layer the deli turkey and avocado into the romaine leaves and roll or fold into cups.", "type": "assemble", "active": true, "appliance": null, "duration_min": 3, "ingredient_refs": ["turkey breast, deli, sliced", "romaine lettuce"]}], "title": "Assemble"}], "make_ahead": "Assemble fresh; mash the avocado just before.", "cook_time_min": 0, "prep_time_min": 6, "total_time_min": 6, "yield_servings": 1}'::jsonb where id='82cc3d02-a596-4728-bc89-81a461f723fd' and user_id is null;

-- Keto Turkey Cheese Roll-Ups
update recipes set recipe_kind='assembly', instructions='{"reheat": "Serve cold.", "storage": "Keeps up to 2 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Spread the cream cheese and a little dijon onto the deli turkey slices.", "type": "prep", "active": true, "appliance": null, "duration_min": 3, "ingredient_refs": ["cream cheese", "dijon mustard", "turkey breast, deli, sliced"]}, {"n": 2, "temp": null, "text": "Lay a strip of cheddar on each and roll up tightly.", "type": "assemble", "active": true, "appliance": null, "duration_min": 3, "ingredient_refs": ["cheddar cheese"]}], "title": "Assemble"}], "make_ahead": "Roll up to 1 day ahead.", "cook_time_min": 0, "prep_time_min": 6, "total_time_min": 6, "yield_servings": 1}'::jsonb where id='5cd1e34f-3d30-4a05-8937-28b58a76dbf1' and user_id is null;

-- Keto Turkey Cream Cheese Rolls
update recipes set recipe_kind='assembly', instructions='{"reheat": "Serve cold.", "storage": "Keeps up to 2 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Spread the cream cheese onto the deli turkey slices.", "type": "prep", "active": true, "appliance": null, "duration_min": 3, "ingredient_refs": ["cream cheese", "turkey breast, deli, sliced"]}, {"n": 2, "temp": null, "text": "Lay a cucumber spear on each, season with sea salt, and roll up.", "type": "assemble", "active": true, "appliance": null, "duration_min": 3, "ingredient_refs": ["cucumber, raw", "sea salt"]}], "title": "Assemble"}], "make_ahead": "Roll up to 1 day ahead.", "cook_time_min": 0, "prep_time_min": 6, "total_time_min": 6, "yield_servings": 1}'::jsonb where id='35a53edc-a678-4c58-8c59-ea3f6943f3c5' and user_id is null;

-- Keto Turkey Stuffed Bell Pepper
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat in the oven or microwave.", "storage": "Keeps up to 3 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Dice the onion and saute until soft, about 3 minutes; add the ground turkey and brown, about 7 minutes. Stir in the diced tomatoes and italian seasoning and season with sea salt.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 13, "ingredient_refs": ["onions, raw", "ground turkey, raw", "tomato products, canned, diced", "italian seasoning", "sea salt"]}], "title": "Make the filling"}, {"steps": [{"n": 2, "temp": null, "text": "Heat the oven to 190°C. Halve and seed the bell peppers, fill with the turkey, and top with cheddar.", "type": "prep", "active": true, "appliance": null, "duration_min": 4, "ingredient_refs": ["bell peppers, raw", "cheddar cheese"]}, {"n": 3, "temp": {"unit": "C", "value": 190}, "text": "Bake until the peppers are tender and the cheese melts, about 22 minutes.", "type": "cook", "active": false, "appliance": "oven", "duration_min": 22, "ingredient_refs": []}], "title": "Stuff and bake"}], "make_ahead": "Stuff up to 1 day ahead and bake fresh.", "cook_time_min": 32, "prep_time_min": 8, "total_time_min": 40, "yield_servings": 1}'::jsonb where id='1b5f7bad-75a9-4f27-bb58-d779f5878c28' and user_id is null;

-- Lamb Chops with Roasted Sweet Potato
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat the sweet potato; gently warm the lamb.", "storage": "Keeps up to 3 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": {"unit": "C", "value": 220}, "text": "Heat the oven to 220°C. Mince the garlic. Cube the sweet potato and toss with olive oil, garlic, and rosemary; roast until tender, about 22 minutes.", "type": "cook", "active": false, "appliance": "oven", "duration_min": 22, "ingredient_refs": ["garlic, raw", "sweet potato, raw", "olive oil", "rosemary, fresh"]}], "title": "Roast the sweet potato"}, {"steps": [{"n": 2, "temp": null, "text": "Season the lamb chops and sear 3-4 minutes per side for medium; rest and serve with the roasted sweet potato.", "type": "cook", "active": false, "appliance": "stovetop", "duration_min": 10, "ingredient_refs": ["lamb, rib chop, lean, raw"]}], "title": "Cook the lamb"}], "make_ahead": "Roast the sweet potato ahead; cook the lamb fresh.", "cook_time_min": 27, "prep_time_min": 6, "total_time_min": 33, "yield_servings": 1}'::jsonb where id='79f0314a-2142-469e-b7a8-f8432c2f15c0' and user_id is null;

commit;
