-- ============================================================================
-- seed-cooking-guides-mains-7.sql — authored cooking guides, MAINS archetype (batch 7, FINAL, 18 recipes)
-- ----------------------------------------------------------------------------
-- Git source of truth for content authored directly in the DB (instructions jsonb + recipe_kind
-- per recipe id). Content UPDATEs only — NOT schema. Idempotent (matches by id); re-runnable.
-- Same pattern + schema as the other seed-cooking-guides-*.sql files.
--
-- FINAL batch — COMPLETES the entire cooking-guide library (299/299, 100%).
-- Mains archetype total: 108 across batches 1-7.
--
-- Regenerate from the live DB (swap the id-prefix filter for the batch):
--   select string_agg(format('-- %s', name) || E'\n' ||
--     format('update recipes set recipe_kind=%L, instructions=%L::jsonb where id=%L and user_id is null;',
--       recipe_kind, instructions::text, id::text), E'\n\n' order by name)
--   from recipes where user_id is null and instructions is not null and id::text like any(array['f0b6febb%', ...]);
--
-- Progress: 299 / 299 cooking guides authored (100%) — salads 26 + smoothies 6 + wraps 5 + soups 15 + bowls 77 + originals 5 + breakfast 57 + mains 108. LIBRARY COMPLETE.
-- ============================================================================

begin;

-- Tilapia Fish Tacos with Cabbage Slaw
update recipes set recipe_kind='cooked', instructions='{"reheat": "Warm the fish and tortillas; assemble fresh.", "storage": "Keeps components up to 2 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Shred the cabbage and toss with lemon juice and a pinch of salt for a quick slaw.", "type": "prep", "active": true, "appliance": null, "duration_min": 5, "ingredient_refs": ["cabbage, raw", "lemon juice, raw"]}], "title": "Make the slaw"}, {"steps": [{"n": 2, "temp": null, "text": "Season the tilapia and pan-sear in olive oil about 3 minutes per side until it flakes; break into pieces.", "type": "cook", "active": false, "appliance": "stovetop", "duration_min": 8, "ingredient_refs": ["tilapia, raw", "olive oil"]}, {"n": 3, "temp": null, "text": "Warm the corn tortillas, fill with the fish and slaw, and top with salsa.", "type": "assemble", "active": true, "appliance": null, "duration_min": 3, "ingredient_refs": ["corn tortilla", "salsa, ready-to-serve"]}], "title": "Cook and assemble"}], "make_ahead": "Make the slaw ahead; cook the fish fresh.", "cook_time_min": 8, "prep_time_min": 8, "total_time_min": 16, "yield_servings": 1}'::jsonb where id='f0b6febb-347f-4eb4-92b7-ab6dc27adab8' and user_id is null;

-- Tuna Cucumber Bites
update recipes set recipe_kind='assembly', instructions='{"reheat": "Serve cold.", "storage": "Keeps up to 1 day refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Drain the tuna and mix with dijon, lemon juice, and sea salt.", "type": "prep", "active": true, "appliance": null, "duration_min": 3, "ingredient_refs": ["tuna, canned in water, drained", "dijon mustard", "lemon juice, raw", "sea salt"]}, {"n": 2, "temp": null, "text": "Slice the cucumber into thick rounds and spoon the tuna on top.", "type": "assemble", "active": true, "appliance": null, "duration_min": 3, "ingredient_refs": ["cucumber, raw"]}], "title": "Assemble"}], "make_ahead": "Make the tuna up to 1 day ahead; top the cucumber fresh.", "cook_time_min": 0, "prep_time_min": 6, "total_time_min": 6, "yield_servings": 1}'::jsonb where id='5ae7c071-6069-4cec-86cf-244cdba74ed5' and user_id is null;

-- Turkey Hummus Rollup Snack
update recipes set recipe_kind='assembly', instructions='{"reheat": "Serve cold.", "storage": "Keeps up to 2 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Spread the hummus onto the deli turkey slices.", "type": "prep", "active": true, "appliance": null, "duration_min": 3, "ingredient_refs": ["turkey breast, deli, sliced", "hummus, commercial"]}, {"n": 2, "temp": null, "text": "Lay the spinach and a cucumber spear on each and roll up.", "type": "assemble", "active": true, "appliance": null, "duration_min": 3, "ingredient_refs": ["spinach, raw", "cucumber, raw"]}], "title": "Assemble"}], "make_ahead": "Roll up to 1 day ahead.", "cook_time_min": 0, "prep_time_min": 6, "total_time_min": 6, "yield_servings": 1}'::jsonb where id='2f721c42-4b1a-4a77-8a8b-d738c71975fe' and user_id is null;

-- Turkey Meatball Zucchini Marinara
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat and toss with fresh zucchini.", "storage": "Keeps up to 3 days refrigerated or 3 months frozen.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Mince the garlic and mix into the ground turkey with italian seasoning; roll into meatballs and brown in olive oil, about 8 minutes.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 10, "ingredient_refs": ["garlic, raw", "ground turkey, raw", "italian seasoning", "olive oil"]}], "title": "Make the meatballs"}, {"steps": [{"n": 2, "temp": null, "text": "Add the diced tomatoes and simmer the meatballs in the marinara, about 10 minutes.", "type": "cook", "active": false, "appliance": "stovetop", "duration_min": 10, "ingredient_refs": ["tomato products, canned, diced"]}, {"n": 3, "temp": null, "text": "Spiralize or dice the zucchini and toss through the hot sauce to soften.", "type": "assemble", "active": true, "appliance": null, "duration_min": 2, "ingredient_refs": ["zucchini, raw"]}], "title": "Sauce and serve"}], "make_ahead": "Make the meatballs and sauce up to 3 days ahead.", "cook_time_min": 22, "prep_time_min": 8, "total_time_min": 30, "yield_servings": 1}'::jsonb where id='33ed31a8-43ba-45c0-a7ef-ab029a3edec4' and user_id is null;

-- Vegan Almond Date Protein Balls
update recipes set recipe_kind='assembly', instructions='{"reheat": "Serve chilled.", "storage": "Keeps up to 1 week refrigerated or 2 months frozen.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Finely chop or grind the almonds and mix with the almond butter, plant protein, chia seeds, cinnamon, and melted coconut oil into a stiff dough.", "type": "prep", "active": true, "appliance": null, "duration_min": 8, "ingredient_refs": ["almonds, raw", "almond butter", "protein powder, plant-based", "chia seeds", "cinnamon, ground", "coconut oil"]}, {"n": 2, "temp": null, "text": "Roll into balls and chill until firm, at least 20 minutes.", "type": "assemble", "active": true, "appliance": null, "duration_min": 4, "ingredient_refs": []}], "title": "Make the balls"}], "make_ahead": "Make a batch ahead; they keep well.", "cook_time_min": 0, "prep_time_min": 12, "total_time_min": 12, "yield_servings": 1}'::jsonb where id='c48d2410-13a8-4e63-9390-9d3b0879ec7f' and user_id is null;

-- Vegan Coconut Almond Energy Bar
update recipes set recipe_kind='assembly', instructions='{"reheat": "Serve chilled.", "storage": "Keeps up to 1 week refrigerated or 2 months frozen.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Chop the almonds and mix with the almond butter, ground flaxseed, cocoa powder, maple syrup, and melted coconut oil into a thick mixture.", "type": "prep", "active": true, "appliance": null, "duration_min": 8, "ingredient_refs": ["almonds, raw", "almond butter", "flaxseed, ground", "cocoa powder, unsweetened", "maple syrup", "coconut oil"]}, {"n": 2, "temp": null, "text": "Press into a lined dish and chill until firm, then cut into bars.", "type": "assemble", "active": true, "appliance": null, "duration_min": 4, "ingredient_refs": []}], "title": "Make the bars"}], "make_ahead": "Make a batch ahead; they keep well.", "cook_time_min": 0, "prep_time_min": 12, "total_time_min": 12, "yield_servings": 1}'::jsonb where id='34630a4f-d055-4aec-a64d-8effffa2bd55' and user_id is null;

-- Vegan Dark Chocolate Almond Bites
update recipes set recipe_kind='assembly', instructions='{"reheat": "Serve chilled.", "storage": "Keeps up to 1 week refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Mix the almond butter, rolled oats, dark chocolate chips, chia seeds, and maple syrup into a stiff dough.", "type": "prep", "active": true, "appliance": null, "duration_min": 6, "ingredient_refs": ["almond butter", "rolled oats", "dark chocolate chips", "chia seeds", "maple syrup"]}, {"n": 2, "temp": null, "text": "Roll into bites and chill until firm, at least 20 minutes.", "type": "assemble", "active": true, "appliance": null, "duration_min": 4, "ingredient_refs": []}], "title": "Make the bites"}], "make_ahead": "Make a batch ahead; they keep well.", "cook_time_min": 0, "prep_time_min": 10, "total_time_min": 10, "yield_servings": 1}'::jsonb where id='993c9ad8-5576-453d-8008-84dbc0c99ac1' and user_id is null;

-- Vegan Edamame with Sea Salt
update recipes set recipe_kind='cooked', instructions='{"reheat": "Serve warm or cold.", "storage": "Keeps up to 3 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Steam or boil the edamame until tender, about 4 minutes.", "type": "cook", "active": false, "appliance": "stovetop", "duration_min": 4, "ingredient_refs": ["edamame, frozen, prepared"]}, {"n": 2, "temp": null, "text": "Drain and toss with the sesame oil and sea salt.", "type": "assemble", "active": true, "appliance": null, "duration_min": 1, "ingredient_refs": ["sesame oil", "sea salt"]}], "title": "Cook"}], "make_ahead": "Cook ahead; good warm or cold.", "cook_time_min": 5, "prep_time_min": 2, "total_time_min": 7, "yield_servings": 1}'::jsonb where id='52dfc584-f022-40d2-afbc-7ae7b1385b9a' and user_id is null;

-- Vegan Energy Balls
update recipes set recipe_kind='assembly', instructions='{"reheat": "Serve chilled.", "storage": "Keeps up to 1 week refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Mix the rolled oats, almond butter, honey, dark chocolate chips, and chia seeds into a stiff dough.", "type": "prep", "active": true, "appliance": null, "duration_min": 6, "ingredient_refs": ["rolled oats", "almond butter", "honey", "dark chocolate chips", "chia seeds"]}, {"n": 2, "temp": null, "text": "Roll into balls and chill until firm, at least 20 minutes.", "type": "assemble", "active": true, "appliance": null, "duration_min": 4, "ingredient_refs": []}], "title": "Make the balls"}], "make_ahead": "Make a batch ahead; they keep well.", "cook_time_min": 0, "prep_time_min": 10, "total_time_min": 10, "yield_servings": 1}'::jsonb where id='9eb63383-56e9-45b1-a0ba-4546bbe7f961' and user_id is null;

-- Vegan Hemp Seed Cocoa Bites
update recipes set recipe_kind='assembly', instructions='{"reheat": "Serve chilled.", "storage": "Keeps up to 1 week refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Mix the hemp seeds, cocoa powder, almond butter, maple syrup, vanilla, and melted coconut oil into a stiff dough.", "type": "prep", "active": true, "appliance": null, "duration_min": 6, "ingredient_refs": ["hemp seeds, hulled", "cocoa powder, unsweetened", "almond butter", "maple syrup", "vanilla extract", "coconut oil"]}, {"n": 2, "temp": null, "text": "Roll into bites and chill until firm, at least 20 minutes.", "type": "assemble", "active": true, "appliance": null, "duration_min": 4, "ingredient_refs": []}], "title": "Make the bites"}], "make_ahead": "Make a batch ahead; they keep well.", "cook_time_min": 0, "prep_time_min": 10, "total_time_min": 10, "yield_servings": 1}'::jsonb where id='0682ef5c-c394-4abe-89f3-e7d35ab8f969' and user_id is null;

-- Vegan Lentil Shepherds Pie
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat in the oven or microwave.", "storage": "Keeps up to 4 days refrigerated or 3 months frozen.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Cube the sweet potato and boil until soft, about 12 minutes; mash and set aside.", "type": "cook", "active": false, "appliance": "stovetop", "duration_min": 12, "ingredient_refs": ["sweet potato, raw"]}], "title": "Make the mash"}, {"steps": [{"n": 2, "temp": null, "text": "Dice the onion and carrots and saute in olive oil until soft, about 6 minutes; stir in the cooked lentils, cumin, and sea salt and warm through.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 10, "ingredient_refs": ["onions, raw", "carrots, raw", "olive oil", "lentils, mature seeds, cooked, boiled", "cumin, ground", "sea salt"]}, {"n": 3, "temp": {"unit": "C", "value": 200}, "text": "Heat the oven to 200°C. Spoon the lentils into a dish, spread the mash over, and bake until golden, about 15 minutes.", "type": "cook", "active": false, "appliance": "oven", "duration_min": 18, "ingredient_refs": []}], "title": "Make the filling and bake"}], "make_ahead": "Assemble up to 1 day ahead and bake fresh; freezes well.", "cook_time_min": 40, "prep_time_min": 10, "total_time_min": 50, "yield_servings": 1}'::jsonb where id='0e8033ae-9957-466f-b697-8160c566749f' and user_id is null;

-- Vegan Lentil Walnut Bolognese
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat gently on the stovetop.", "storage": "Keeps up to 4 days refrigerated or 3 months frozen.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Dice the onion and mince the garlic; saute in olive oil until soft, about 4 minutes. Finely chop the walnuts and add to toast for 2 minutes.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 6, "ingredient_refs": ["onions, raw", "garlic, raw", "olive oil", "walnuts, raw"]}, {"n": 2, "temp": null, "text": "Stir in the cooked lentils, diced tomatoes, and italian seasoning and simmer into a rich bolognese, about 16 minutes.", "type": "cook", "active": false, "appliance": "stovetop", "duration_min": 16, "ingredient_refs": ["lentils, mature seeds, cooked, boiled", "tomato products, canned, diced", "italian seasoning"]}], "title": "Build the sauce"}], "make_ahead": "Tastes even better the next day; make up to 4 days ahead.", "cook_time_min": 22, "prep_time_min": 8, "total_time_min": 30, "yield_servings": 1}'::jsonb where id='97c18d2c-a3d4-49a5-a184-7525304f1066' and user_id is null;

-- Vegan Peanut Butter Apple Slices
update recipes set recipe_kind='assembly', instructions='{"reheat": "Serve fresh.", "storage": "Eat soon after slicing.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Core and slice the apple into rounds or wedges.", "type": "prep", "active": true, "appliance": null, "duration_min": 2, "ingredient_refs": ["apples, raw"]}, {"n": 2, "temp": null, "text": "Spread with peanut butter, sprinkle with chia seeds, and dust with cinnamon.", "type": "assemble", "active": true, "appliance": null, "duration_min": 3, "ingredient_refs": ["peanut butter, smooth", "chia seeds", "cinnamon, ground"]}], "title": "Assemble"}], "make_ahead": "Best fresh so the apple stays crisp.", "cook_time_min": 0, "prep_time_min": 5, "total_time_min": 5, "yield_servings": 1}'::jsonb where id='82264bb3-43cb-4b89-a0cd-390e14ba8ec0' and user_id is null;

-- Vegan Tempeh Broccoli Stir Fry
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat in a pan.", "storage": "Keeps up to 3 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Mince the garlic and grate the ginger. Cube the tempeh and stir-fry in sesame oil with the garlic and ginger until golden, about 8 minutes.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 8, "ingredient_refs": ["garlic, raw", "ginger root, raw", "tempeh", "sesame oil"]}, {"n": 2, "temp": null, "text": "Add the broccoli florets and stir-fry until tender-crisp, about 5 minutes, splashing with soy sauce; serve over the brown rice.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 5, "ingredient_refs": ["broccoli, raw", "soy sauce", "brown rice, cooked"]}], "title": "Stir-fry"}], "make_ahead": "Cook the rice ahead; stir-fry fresh.", "cook_time_min": 13, "prep_time_min": 5, "total_time_min": 18, "yield_servings": 1}'::jsonb where id='16fb5c38-4dcd-4d83-a877-91f49ad6e643' and user_id is null;

-- Vegan Tofu Mushroom Stir Fry
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat in a pan.", "storage": "Keeps up to 3 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Mince the garlic and grate the ginger. Cube the tofu and slice the mushrooms; stir-fry the tofu in sesame oil with the garlic and ginger until golden, about 8 minutes.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 8, "ingredient_refs": ["garlic, raw", "ginger root, raw", "tofu, firm, raw", "mushrooms, portobello, raw", "sesame oil"]}, {"n": 2, "temp": null, "text": "Add the mushrooms and stir-fry until softened, about 5 minutes, splashing with soy sauce; serve over the brown rice.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 6, "ingredient_refs": ["soy sauce", "brown rice, cooked"]}], "title": "Stir-fry"}], "make_ahead": "Cook the rice ahead; stir-fry fresh.", "cook_time_min": 14, "prep_time_min": 5, "total_time_min": 19, "yield_servings": 1}'::jsonb where id='33e9e280-fba3-48dc-adf5-b0e704e97fb5' and user_id is null;

-- Vegan Tofu Sesame Noodles
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat the tofu in a pan; serve the noodles cold or warm.", "storage": "Keeps up to 3 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Grate the ginger. Cube the tofu and pan-fry in sesame oil with the ginger until golden and crisp, about 8 minutes.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 8, "ingredient_refs": ["ginger root, raw", "tofu, firm, raw", "sesame oil"]}], "title": "Cook the tofu"}, {"steps": [{"n": 2, "temp": null, "text": "Whisk the peanut butter with soy sauce and a little warm water into a sauce. Toss with the warm brown rice and sliced cucumber, then top with the tofu.", "type": "assemble", "active": true, "appliance": null, "duration_min": 4, "ingredient_refs": ["peanut butter, smooth", "soy sauce", "brown rice, cooked", "cucumber, raw"]}], "title": "Sauce and serve"}], "make_ahead": "Cook the rice ahead; crisp the tofu fresh.", "cook_time_min": 10, "prep_time_min": 8, "total_time_min": 18, "yield_servings": 1}'::jsonb where id='48f2e572-2d44-4d09-8187-f560801dffac' and user_id is null;

-- Vegan Tofu Tikka Masala
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat gently on the stovetop.", "storage": "Keeps up to 3 days refrigerated or 2 months frozen.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Cube the tofu and pan-fry in olive oil until golden, about 8 minutes; remove and set aside.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 8, "ingredient_refs": ["tofu, firm, raw", "olive oil"]}], "title": "Cook the tofu"}, {"steps": [{"n": 2, "temp": null, "text": "Dice the onion and mince the garlic and ginger; saute until soft and fragrant, about 5 minutes, then stir in the cumin.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 5, "ingredient_refs": ["onions, raw", "garlic, raw", "ginger root, raw", "cumin, ground"]}, {"n": 3, "temp": null, "text": "Add the diced tomatoes and coconut milk and simmer 8 minutes, then return the tofu and simmer until the sauce is rich, about 6 minutes.", "type": "cook", "active": false, "appliance": "stovetop", "duration_min": 14, "ingredient_refs": ["tomato products, canned, diced", "coconut milk"]}], "title": "Make the sauce"}], "make_ahead": "Tastes even better the next day; make up to 3 days ahead.", "cook_time_min": 27, "prep_time_min": 8, "total_time_min": 35, "yield_servings": 1}'::jsonb where id='a7e88607-41e0-4b5e-952d-b54f6cf2d49f' and user_id is null;

-- Walnut Blueberry Trail Mix
update recipes set recipe_kind='assembly', instructions='{"reheat": "Serve at room temperature.", "storage": "Keeps up to 1 week in an airtight container.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Toss the walnuts, pumpkin seeds, and dark chocolate chips together.", "type": "prep", "active": true, "appliance": null, "duration_min": 3, "ingredient_refs": ["walnuts, raw", "pumpkin seeds, raw", "dark chocolate chips"]}, {"n": 2, "temp": null, "text": "Fold in the dried or fresh blueberries.", "type": "assemble", "active": true, "appliance": null, "duration_min": 2, "ingredient_refs": ["blueberries, raw"]}], "title": "Assemble"}], "make_ahead": "Mix a batch ahead; keeps well with dried blueberries.", "cook_time_min": 0, "prep_time_min": 5, "total_time_min": 5, "yield_servings": 1}'::jsonb where id='1025f090-488d-4bda-94d4-d282b200de02' and user_id is null;

commit;
