-- ============================================================================
-- seed-cooking-guides-bowls-1.sql — authored cooking guides, BOWLS archetype (batch 1 of N, 15 recipes)
-- ----------------------------------------------------------------------------
-- Git source of truth for content authored directly in the DB (instructions jsonb + recipe_kind
-- per recipe id). Content UPDATEs only — NOT schema. Idempotent (matches by id); re-runnable.
-- Same pattern + schema as the other seed-cooking-guides-*.sql files.
--
-- ~62 bowls total → captured across numbered batches (bowls-1, bowls-2, ...). This is batch 1.
--
-- Regenerate from the live DB (swap the id-prefix filter for the batch):
--   select string_agg(format('-- %s', name) || E'\n' ||
--     format('update recipes set recipe_kind=%L, instructions=%L::jsonb where id=%L and user_id is null;',
--       recipe_kind, instructions::text, id::text), E'\n\n' order by name)
--   from recipes where user_id is null and id::text like any(array['d64594ab%', ...]);
--
-- Progress: 72 / 299 cooking guides authored (24%) — salads 26 + smoothies 6 + wraps 5 + soups 15 + bowls 15 (batch 1).
-- ============================================================================

begin;

-- Carnivore Bacon Ground Beef Bowl
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat the beef and bacon; add a fresh egg.", "storage": "Keeps up to 3 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Brown the ground beef in a pan over medium-high, breaking it up, about 6 minutes; season with sea salt.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 6, "ingredient_refs": ["ground beef, 90% lean, raw", "sea salt"]}, {"n": 2, "temp": null, "text": "Fry the egg in the same pan to your liking and warm the bacon through.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 4, "ingredient_refs": ["egg, whole, raw", "bacon, cured, pan-fried"]}, {"n": 3, "temp": null, "text": "Pile the beef, bacon, and egg into a bowl.", "type": "assemble", "active": true, "appliance": null, "duration_min": 2, "ingredient_refs": []}], "title": "Cook"}], "make_ahead": "Cook the beef and bacon up to 3 days ahead; fry the egg fresh.", "cook_time_min": 12, "prep_time_min": 3, "total_time_min": 15, "yield_servings": 1}'::jsonb where id='d64594ab-c49f-4b02-8da2-4992a016fafe' and user_id is null;

-- Carnivore Beef Jerky Bowl
update recipes set recipe_kind='cooked', instructions='{"reheat": "Serve cold or gently warm.", "storage": "Keeps up to 3 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Season the sirloin generously with sea salt and black pepper.", "type": "prep", "active": true, "appliance": null, "duration_min": 2, "ingredient_refs": ["beef, sirloin steak, lean, raw", "sea salt", "black pepper, ground"]}, {"n": 2, "temp": null, "text": "Sear the steak in a hot dry pan, 3-4 minutes per side for medium; rest 5 minutes and slice thin.", "type": "cook", "active": false, "appliance": "stovetop", "duration_min": 10, "ingredient_refs": ["beef, sirloin steak, lean, raw"]}], "title": "Cook"}], "make_ahead": "Cook the steak up to 3 days ahead.", "cook_time_min": 10, "prep_time_min": 5, "total_time_min": 15, "yield_servings": 1}'::jsonb where id='cd04b493-cca3-4a94-a8d8-7e943fa7aa29' and user_id is null;

-- Carnivore Cod Egg Breakfast Bowl
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat gently so the cod does not dry out.", "storage": "Keeps up to 1 day refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Season the cod with sea salt and black pepper and pan-sear in a little butter or oil, about 3-4 minutes per side, until it flakes.", "type": "cook", "active": false, "appliance": "stovetop", "duration_min": 8, "ingredient_refs": ["cod, atlantic, raw", "sea salt", "black pepper, ground"]}, {"n": 2, "temp": null, "text": "Fry the egg in the same pan and serve alongside the cod.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 4, "ingredient_refs": ["egg, whole, raw"]}], "title": "Cook"}], "make_ahead": "Best cooked fresh.", "cook_time_min": 12, "prep_time_min": 3, "total_time_min": 15, "yield_servings": 1}'::jsonb where id='83c5dfab-2680-46df-863e-86961bd38722' and user_id is null;

-- Carnivore Ground Beef and Egg Bowl
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat the beef; add a fresh egg.", "storage": "Keeps up to 3 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Brown the ground beef in a pan with a splash of beef broth, breaking it up, about 7 minutes; season with sea salt and black pepper.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 7, "ingredient_refs": ["ground beef, 90% lean, raw", "beef broth", "sea salt", "black pepper, ground"]}, {"n": 2, "temp": null, "text": "Fry the egg to your liking and set it on top of the beef.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 3, "ingredient_refs": ["egg, whole, raw"]}], "title": "Cook"}], "make_ahead": "Cook the beef up to 3 days ahead; fry the egg fresh.", "cook_time_min": 10, "prep_time_min": 3, "total_time_min": 13, "yield_servings": 1}'::jsonb where id='cd9e36e5-602d-4d77-9998-cb4124342efe' and user_id is null;

-- Carnivore Ground Beef Burger Bowl
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat the patty; add a fresh egg.", "storage": "Keeps up to 2 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Form the ground beef into a patty and cook in a pan over medium-high, 3-4 minutes per side; season with sea salt and black pepper.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 8, "ingredient_refs": ["ground beef, 80% lean, raw", "sea salt", "black pepper, ground"]}, {"n": 2, "temp": null, "text": "Top the patty with cheddar to melt, fry the egg, and serve together in a bowl.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 3, "ingredient_refs": ["cheddar cheese", "egg, whole, raw"]}], "title": "Cook"}], "make_ahead": "Best cooked fresh.", "cook_time_min": 11, "prep_time_min": 3, "total_time_min": 14, "yield_servings": 1}'::jsonb where id='d66d6e93-234a-440a-bc22-8145447addc9' and user_id is null;

-- Carnivore Ground Beef Dinner Bowl
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat the beef; add a fresh egg.", "storage": "Keeps up to 3 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Brown the ground beef in a pan over medium-high, breaking it up, about 7 minutes; season with sea salt and black pepper.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 7, "ingredient_refs": ["ground beef, 80% lean, raw", "sea salt", "black pepper, ground"]}, {"n": 2, "temp": null, "text": "Stir the cheddar through to melt, fry the egg, and set it on top.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 4, "ingredient_refs": ["cheddar cheese", "egg, whole, raw"]}], "title": "Cook"}], "make_ahead": "Cook the beef up to 3 days ahead; fry the egg fresh.", "cook_time_min": 11, "prep_time_min": 3, "total_time_min": 14, "yield_servings": 1}'::jsonb where id='446cfb1e-fd62-47f1-b11b-8e410bb16517' and user_id is null;

-- Carnivore Ground Lamb Dinner Bowl
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat gently on the stovetop.", "storage": "Keeps up to 3 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Season the lamb and ground beef with sea salt and black pepper.", "type": "prep", "active": true, "appliance": null, "duration_min": 2, "ingredient_refs": ["lamb, rib chop, lean, raw", "ground beef, 90% lean, raw", "sea salt", "black pepper, ground"]}, {"n": 2, "temp": null, "text": "Sear the lamb 3-4 minutes per side and brown the ground beef alongside; slice the lamb and combine in a bowl.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 10, "ingredient_refs": []}], "title": "Cook"}], "make_ahead": "Cook up to 3 days ahead.", "cook_time_min": 12, "prep_time_min": 3, "total_time_min": 15, "yield_servings": 1}'::jsonb where id='dff00ec3-94b7-40cb-9dd2-9cbaedfc8486' and user_id is null;

-- Carnivore Pork Bacon Egg Bowl
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat the pork and bacon; add a fresh egg.", "storage": "Keeps up to 3 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Season the pork chop with sea salt and pan-sear, about 4 minutes per side, until cooked through; slice.", "type": "cook", "active": false, "appliance": "stovetop", "duration_min": 10, "ingredient_refs": ["pork chop, lean, raw", "sea salt"]}, {"n": 2, "temp": null, "text": "Fry the egg and warm the bacon, then combine with the pork in a bowl.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 4, "ingredient_refs": ["egg, whole, raw", "bacon, cured, pan-fried"]}], "title": "Cook"}], "make_ahead": "Cook the pork and bacon up to 3 days ahead; fry the egg fresh.", "cook_time_min": 14, "prep_time_min": 3, "total_time_min": 17, "yield_servings": 1}'::jsonb where id='1861ed3f-07b0-4132-8edb-21c16c191387' and user_id is null;

-- Carnivore Shrimp Butter Lunch Bowl
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat gently so the shrimp stay tender.", "storage": "Keeps up to 1 day refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Pat the shrimp dry and season with sea salt and black pepper.", "type": "prep", "active": true, "appliance": null, "duration_min": 1, "ingredient_refs": ["shrimp, raw", "sea salt", "black pepper, ground"]}, {"n": 2, "temp": null, "text": "Saute the shrimp in the heavy cream over medium until pink and the cream reduces to a light sauce, about 6 minutes.", "type": "cook", "active": false, "appliance": "stovetop", "duration_min": 6, "ingredient_refs": ["shrimp, raw", "heavy cream"]}], "title": "Cook"}], "make_ahead": "Best cooked fresh.", "cook_time_min": 7, "prep_time_min": 3, "total_time_min": 10, "yield_servings": 1}'::jsonb where id='2ebbd08d-01ab-4e82-b521-598bacc8960e' and user_id is null;

-- Chicken Rice Power Bowl
update recipes set recipe_kind='assembly', instructions='{"reheat": "Microwave 2 minutes.", "storage": "Keeps up to 3 days refrigerated; great for meal prep.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Add the cooked brown rice to a bowl and top with the sliced roasted chicken.", "type": "prep", "active": true, "appliance": null, "duration_min": 2, "ingredient_refs": ["brown rice, cooked", "chicken breast, broilers or fryers, cooked, roasted"]}, {"n": 2, "temp": null, "text": "Steam or blanch the broccoli briefly, then add to the bowl.", "type": "prep", "active": true, "appliance": null, "duration_min": 4, "ingredient_refs": ["broccoli, raw"]}, {"n": 3, "temp": null, "text": "Drizzle with olive oil and soy sauce and toss.", "type": "assemble", "active": true, "appliance": null, "duration_min": 2, "ingredient_refs": ["olive oil", "soy sauce"]}], "title": "Assemble"}], "make_ahead": "Use pre-cooked chicken and rice; assemble in minutes.", "cook_time_min": 0, "prep_time_min": 8, "total_time_min": 8, "yield_servings": 1}'::jsonb where id='fc2c2086-6108-4a56-86bb-fd7e7a06201b' and user_id is null;

-- Cottage Cheese and Fruit Bowl
update recipes set recipe_kind='assembly', instructions='{"reheat": "Serve cold.", "storage": "Keeps up to 2 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Spoon the cottage cheese into a bowl.", "type": "prep", "active": true, "appliance": null, "duration_min": 1, "ingredient_refs": ["cottage cheese, lowfat"]}, {"n": 2, "temp": null, "text": "Top with the strawberries and blueberries and drizzle with honey.", "type": "assemble", "active": true, "appliance": null, "duration_min": 3, "ingredient_refs": ["strawberries, raw", "blueberries, raw", "honey"]}], "title": "Assemble"}], "make_ahead": "Assemble fresh, or pack the fruit separately.", "cook_time_min": 0, "prep_time_min": 4, "total_time_min": 4, "yield_servings": 1}'::jsonb where id='e66084d8-e697-41a7-98a2-3cf7acc22a83' and user_id is null;

-- Edamame Brown Rice Power Bowl
update recipes set recipe_kind='assembly', instructions='{"reheat": "Serve cold or at room temperature.", "storage": "Keeps up to 3 days refrigerated; great for meal prep.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Add the cooked brown rice and edamame to a bowl.", "type": "prep", "active": true, "appliance": null, "duration_min": 2, "ingredient_refs": ["brown rice, cooked", "edamame, frozen, prepared"]}, {"n": 2, "temp": null, "text": "Grate the carrot and slice the cucumber; add to the bowl.", "type": "prep", "active": true, "appliance": null, "duration_min": 4, "ingredient_refs": ["carrots, raw", "cucumber, raw"]}, {"n": 3, "temp": null, "text": "Whisk the sesame oil and soy sauce and toss through.", "type": "assemble", "active": true, "appliance": null, "duration_min": 2, "ingredient_refs": ["sesame oil", "soy sauce"]}], "title": "Assemble"}], "make_ahead": "Cook the rice and edamame up to 3 days ahead.", "cook_time_min": 0, "prep_time_min": 8, "total_time_min": 8, "yield_servings": 1}'::jsonb where id='a9ed6365-1497-41e5-ac9e-eb62f80a5a52' and user_id is null;

-- Greek Yogurt Almond Protein Bowl
update recipes set recipe_kind='assembly', instructions='{"reheat": "Serve cold.", "storage": "Keeps up to 2 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Spoon the Greek yogurt into a bowl.", "type": "prep", "active": true, "appliance": null, "duration_min": 1, "ingredient_refs": ["greek yogurt, plain, nonfat"]}, {"n": 2, "temp": null, "text": "Top with the almonds and blueberries, drizzle with honey, and dust with cinnamon.", "type": "assemble", "active": true, "appliance": null, "duration_min": 3, "ingredient_refs": ["almonds, raw", "blueberries, raw", "honey", "cinnamon, ground"]}], "title": "Assemble"}], "make_ahead": "Assemble fresh, or layer in a jar the night before.", "cook_time_min": 0, "prep_time_min": 4, "total_time_min": 4, "yield_servings": 1}'::jsonb where id='64cac626-4501-4866-9976-56b34ac532e3' and user_id is null;

-- Greek Yogurt Protein Bowl
update recipes set recipe_kind='assembly', instructions='{"reheat": "Serve cold.", "storage": "Keeps up to 2 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Spoon the Greek yogurt into a bowl and stir in the rolled oats.", "type": "prep", "active": true, "appliance": null, "duration_min": 2, "ingredient_refs": ["Greek yogurt, plain, nonfat", "rolled oats"]}, {"n": 2, "temp": null, "text": "Top with the blueberries and almonds and drizzle with honey.", "type": "assemble", "active": true, "appliance": null, "duration_min": 2, "ingredient_refs": ["blueberries, raw", "almonds, raw", "honey"]}], "title": "Assemble"}], "make_ahead": "Layer in a jar overnight for softer oats.", "cook_time_min": 0, "prep_time_min": 4, "total_time_min": 4, "yield_servings": 1}'::jsonb where id='d51200f4-020d-42cb-b1de-a511f0a6c2cf' and user_id is null;

-- Grilled Chicken Quinoa Bowl
update recipes set recipe_kind='cooked', instructions='{"reheat": "Serve cold or warm the chicken.", "storage": "Keeps up to 3 days refrigerated; great for meal prep.", "sections": [{"steps": [{"n": 1, "temp": {"unit": "C", "value": 74}, "text": "Season the chicken with a pinch of salt and cook in a little olive oil over medium-high, 5-6 minutes per side (74°C internal); rest and slice.", "type": "cook", "active": false, "appliance": "stovetop", "duration_min": 15, "ingredient_refs": ["chicken breast, broilers or fryers, raw", "olive oil"]}], "title": "Cook the chicken"}, {"steps": [{"n": 2, "temp": null, "text": "Add the cooked quinoa to a bowl with the diced cucumber, tomatoes, and crumbled feta.", "type": "prep", "active": true, "appliance": null, "duration_min": 3, "ingredient_refs": ["quinoa, cooked", "cucumber, raw", "tomatoes, raw", "feta cheese"]}, {"n": 3, "temp": null, "text": "Dress with the remaining olive oil and lemon juice and top with the sliced chicken.", "type": "assemble", "active": true, "appliance": null, "duration_min": 2, "ingredient_refs": ["olive oil", "lemon juice, raw", "chicken breast, broilers or fryers, raw"]}], "title": "Assemble"}], "make_ahead": "Cook the chicken and quinoa up to 3 days ahead.", "cook_time_min": 15, "prep_time_min": 5, "total_time_min": 20, "yield_servings": 1}'::jsonb where id='5f5a42a7-e187-42ae-8a61-8947808d3a56' and user_id is null;

commit;
