-- ============================================================================
-- seed-cooking-guides-originals.sql — authored cooking guides, PRE-SEED PILOT recipes (5)
-- ----------------------------------------------------------------------------
-- Git source of truth for content authored directly in the DB (instructions jsonb + recipe_kind
-- per recipe id). Content UPDATEs only — NOT schema. Idempotent (matches by id); re-runnable.
-- Same pattern + schema as the other seed-cooking-guides-*.sql files.
--
-- These 5 guides were authored during the Phase-1 pilot, BEFORE the seed-file practice began, so
-- they had live DB guides but no git home. This file closes that gap: seed files now capture all
-- 134 authored guides (0 uncaptured). Mixed archetypes (smoothie, salmon, stir-fry, bowl, wrap).
--
-- Regenerate from the live DB:
--   select string_agg(format('-- %s', name) || E'\n' ||
--     format('update recipes set recipe_kind=%L, instructions=%L::jsonb where id=%L and user_id is null;',
--       recipe_kind, instructions::text, id::text), E'\n\n' order by name)
--   from recipes where user_id is null and instructions is not null
--     and id::text like any(array['c9cb1173%','ccb851a8%','3b0af339%','99365399%','ce8d7b7b%']);
--
-- Progress: 134 / 299 cooking guides authored (45%) — salads 26 + smoothies 6 + wraps 5 + soups 15 + bowls 77 + 5 originals.
-- ============================================================================

begin;

-- Almond Butter Protein Smoothie
update recipes set recipe_kind='assembly', instructions='{"reheat": null, "storage": "Drink fresh; if needed, keep in a sealed bottle in the fridge up to 12h and shake before drinking.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Add the milk, banana, and almond butter to the blender first so they pull down into the blades.", "type": "assemble", "active": true, "appliance": "blender", "duration_min": 1, "ingredient_refs": ["whole milk", "banana, raw", "almond butter"]}, {"n": 2, "temp": null, "text": "Add the whey protein and chia seeds on top.", "type": "assemble", "active": true, "appliance": "blender", "duration_min": 1, "ingredient_refs": ["whey protein powder", "chia seeds"]}, {"n": 3, "temp": null, "text": "Blend on high 30 to 45 sec until completely smooth, with no clumps of chia left.", "type": "cook", "active": true, "appliance": "blender", "duration_min": 1, "ingredient_refs": ["chia seeds"]}], "title": "Blend"}], "make_ahead": "Freeze the banana and pre-portion the dry ingredients the night before for a 1-minute morning blend.", "cook_time_min": 0, "prep_time_min": 4, "total_time_min": 4, "yield_servings": 1}'::jsonb where id='c9cb1173-d2fa-4c38-9907-e6490ce1188f' and user_id is null;

-- Baked Salmon with Asparagus
update recipes set recipe_kind='cooked', instructions='{"reheat": "Oven at 150C / 300F for 8 to 10 min, or eat cold over greens.", "storage": "Airtight in the fridge up to 3 days.", "sections": [{"steps": [{"n": 1, "temp": {"unit": "C", "value": 220}, "text": "Heat the oven to 220C / 425F and line a sheet pan with foil.", "type": "prep", "active": true, "appliance": "oven", "duration_min": 1, "ingredient_refs": []}, {"n": 2, "temp": null, "text": "Mince the garlic, then toss the asparagus with half the olive oil on the pan.", "type": "prep", "active": true, "appliance": null, "duration_min": 3, "ingredient_refs": ["garlic, raw", "asparagus, raw", "olive oil"]}, {"n": 3, "temp": null, "text": "Pat the salmon dry, set it on the pan, and rub with the rest of the olive oil, the garlic, and the lemon juice.", "type": "prep", "active": true, "appliance": null, "duration_min": 3, "ingredient_refs": ["salmon, atlantic, farmed, raw", "olive oil", "garlic, raw", "lemon juice, raw"]}], "title": "Prep"}, {"steps": [{"n": 4, "temp": {"unit": "C", "value": 220}, "text": "Roast 12 to 15 min, until the salmon flakes easily with a fork and the asparagus is tender-crisp.", "type": "cook", "active": false, "appliance": "oven", "duration_min": 14, "ingredient_refs": ["salmon, atlantic, farmed, raw", "asparagus, raw"]}, {"n": 5, "temp": null, "text": "Rest 2 min, then divide between two plates.", "type": "rest", "active": false, "appliance": null, "duration_min": 2, "ingredient_refs": []}], "title": "Roast"}], "make_ahead": "Prep the pan (oil, garlic, lemon) and refrigerate up to 12h; roast fresh.", "cook_time_min": 15, "prep_time_min": 10, "total_time_min": 25, "yield_servings": 2}'::jsonb where id='ccb851a8-4196-4a14-941d-3d6d458a5dd1' and user_id is null;

-- Beef and Vegetable Stir Fry
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat in a hot pan 2 to 3 min; the microwave softens the veg.", "storage": "Airtight in the fridge up to 3 days.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Slice the beef thinly against the grain. Cut the broccoli into florets and the bell pepper into strips.", "type": "prep", "active": true, "appliance": null, "duration_min": 6, "ingredient_refs": ["beef, sirloin steak, lean, raw", "broccoli, raw", "bell peppers, raw"]}, {"n": 2, "temp": null, "text": "Mince the garlic and ginger, then stir them together with the soy sauce in a small bowl.", "type": "prep", "active": true, "appliance": null, "duration_min": 3, "ingredient_refs": ["garlic, raw", "ginger root, raw", "soy sauce"]}], "title": "Prep"}, {"steps": [{"n": 3, "temp": null, "text": "Heat the sesame oil in a wok or large pan over high heat until it shimmers.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 1, "ingredient_refs": ["sesame oil"]}, {"n": 4, "temp": null, "text": "Sear the beef in a single layer, 1 to 2 min per side, until browned but not fully cooked; move it to a plate.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 3, "ingredient_refs": ["beef, sirloin steak, lean, raw"]}, {"n": 5, "temp": null, "text": "Add the broccoli and pepper to the hot pan and stir-fry 3 to 4 min until tender-crisp and bright.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 4, "ingredient_refs": ["broccoli, raw", "bell peppers, raw"]}, {"n": 6, "temp": null, "text": "Return the beef, pour in the sauce, and toss 1 min until everything is glossy and coated.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 1, "ingredient_refs": ["beef, sirloin steak, lean, raw", "soy sauce", "garlic, raw", "ginger root, raw"]}], "title": "Stir-fry"}], "make_ahead": "Slice the beef and veg and mix the sauce up to a day ahead; the stir-fry is under 10 min from cold.", "cook_time_min": 10, "prep_time_min": 12, "total_time_min": 22, "yield_servings": 2}'::jsonb where id='3b0af339-8c90-43b9-9776-f804aadffcb4' and user_id is null;

-- Blueberry Protein Yogurt Bowl
update recipes set recipe_kind='assembly', instructions='{"reheat": null, "storage": "Best fresh. Covered in the fridge up to 24h (nuts soften).", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Spoon the Greek yogurt into a bowl and stir in the whey protein until smooth, with no dry streaks left.", "type": "assemble", "active": true, "appliance": null, "duration_min": 2, "ingredient_refs": ["greek yogurt, plain, nonfat", "whey protein powder"]}, {"n": 2, "temp": null, "text": "Scatter the blueberries and almonds over the top.", "type": "assemble", "active": true, "appliance": null, "duration_min": 1, "ingredient_refs": ["blueberries, raw", "almonds, raw"]}, {"n": 3, "temp": null, "text": "Drizzle with honey and serve right away.", "type": "assemble", "active": true, "appliance": null, "duration_min": 1, "ingredient_refs": ["honey"]}], "title": "Assemble"}], "make_ahead": "Stir the yogurt and protein up to a day ahead; add berries, almonds, and honey just before eating so they stay crisp.", "cook_time_min": 0, "prep_time_min": 5, "total_time_min": 5, "yield_servings": 1}'::jsonb where id='99365399-cb40-4d9e-9f1e-722edd51bf89' and user_id is null;

-- Lean Turkey Wrap
update recipes set recipe_kind='assembly', instructions='{"reheat": null, "storage": "Fridge up to 1 day, wrapped tightly.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Lay the tortilla flat and spread the mustard across the centre.", "type": "assemble", "active": true, "appliance": null, "duration_min": 1, "ingredient_refs": ["flour tortilla, large", "mustard, prepared"]}, {"n": 2, "temp": null, "text": "Layer on the turkey, then the romaine and sliced tomatoes.", "type": "assemble", "active": true, "appliance": null, "duration_min": 2, "ingredient_refs": ["turkey breast, deli, sliced", "romaine lettuce", "tomatoes, raw"]}, {"n": 3, "temp": null, "text": "Slice the avocado and fan it over the fillings.", "type": "prep", "active": true, "appliance": null, "duration_min": 2, "ingredient_refs": ["avocado, raw"]}, {"n": 4, "temp": null, "text": "Fold in the sides, roll tightly from the bottom, and slice in half.", "type": "assemble", "active": true, "appliance": null, "duration_min": 1, "ingredient_refs": ["flour tortilla, large"]}], "title": "Build the wrap"}], "make_ahead": "Wrap whole in foil up to 4h ahead; pat the tomato dry first so it does not go soggy.", "cook_time_min": 0, "prep_time_min": 8, "total_time_min": 8, "yield_servings": 1}'::jsonb where id='ce8d7b7b-dcea-4d87-ad7b-1e9f5067cf8b' and user_id is null;

commit;
