-- ============================================================================
-- seed-cooking-guides-breakfast-1.sql — authored cooking guides, BREAKFAST archetype (batch 1, 15 recipes)
-- ----------------------------------------------------------------------------
-- Git source of truth for content authored directly in the DB (instructions jsonb + recipe_kind
-- per recipe id). Content UPDATEs only — NOT schema. Idempotent (matches by id); re-runnable.
-- Same pattern + schema as the other seed-cooking-guides-*.sql files.
--
-- Regenerate from the live DB (swap the id-prefix filter for the batch):
--   select string_agg(format('-- %s', name) || E'\n' ||
--     format('update recipes set recipe_kind=%L, instructions=%L::jsonb where id=%L and user_id is null;',
--       recipe_kind, instructions::text, id::text), E'\n\n' order by name)
--   from recipes where user_id is null and instructions is not null and id::text like any(array['db44fe56%', ...]);
--
-- Progress: 149 / 299 cooking guides authored (50%) — salads 26 + smoothies 6 + wraps 5 + soups 15 + bowls 77 + originals 5 + breakfast 15 (batch 1).
-- ============================================================================

begin;

-- Carnivore Bacon Egg Skillet
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat gently; eggs are best fresh.", "storage": "Keeps up to 1 day refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Warm the bacon in a skillet with a splash of beef broth over medium.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 3, "ingredient_refs": ["bacon, cured, pan-fried", "beef broth"]}, {"n": 2, "temp": null, "text": "Crack in the eggs and cook to your liking; season with sea salt and black pepper.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 5, "ingredient_refs": ["egg, whole, raw", "sea salt", "black pepper, ground"]}], "title": "Cook"}], "make_ahead": "Best cooked fresh.", "cook_time_min": 8, "prep_time_min": 2, "total_time_min": 10, "yield_servings": 1}'::jsonb where id='db44fe56-624b-449c-8b4b-2df6342c99cb' and user_id is null;

-- Carnivore Beef and Egg Protein Bites
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat in a pan or microwave.", "storage": "Keeps up to 3 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Chop the hard-boiled eggs and mix into the ground beef with sea salt and black pepper.", "type": "prep", "active": true, "appliance": null, "duration_min": 4, "ingredient_refs": ["egg, whole, hard-boiled", "ground beef, 90% lean, raw", "sea salt", "black pepper, ground"]}, {"n": 2, "temp": null, "text": "Roll into bite-sized balls and pan-fry over medium until browned and cooked through, about 10 minutes.", "type": "cook", "active": false, "appliance": "stovetop", "duration_min": 10, "ingredient_refs": []}], "title": "Cook"}], "make_ahead": "Make up to 3 days ahead; great protein snack.", "cook_time_min": 12, "prep_time_min": 5, "total_time_min": 17, "yield_servings": 1}'::jsonb where id='c6f628b6-a64a-4c6c-be55-113a5fcf3cb8' and user_id is null;

-- Carnivore Beef Tenderloin Breakfast Plate
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat the steak; add fresh eggs.", "storage": "Keeps up to 3 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Season the sirloin with sea salt and black pepper and sear, 3-4 minutes per side for medium; rest and slice.", "type": "cook", "active": false, "appliance": "stovetop", "duration_min": 10, "ingredient_refs": ["beef, sirloin steak, lean, raw", "sea salt", "black pepper, ground"]}, {"n": 2, "temp": null, "text": "Fry the eggs and warm the bacon in the same pan; plate with the steak.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 4, "ingredient_refs": ["egg, whole, raw", "bacon, cured, pan-fried"]}], "title": "Cook"}], "make_ahead": "Cook the steak and bacon ahead; fry eggs fresh.", "cook_time_min": 14, "prep_time_min": 3, "total_time_min": 17, "yield_servings": 1}'::jsonb where id='ac64f320-37d0-4b2d-835f-36e5f6cdaa03' and user_id is null;

-- Carnivore Ground Beef Breakfast Patty Plate
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat the patty; add fresh eggs.", "storage": "Keeps up to 3 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Form the ground beef into a patty, season with sea salt and black pepper, and cook 3-4 minutes per side.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 8, "ingredient_refs": ["ground beef, 80% lean, raw", "sea salt", "black pepper, ground"]}, {"n": 2, "temp": null, "text": "Fry the eggs in the same pan and plate with the patty.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 3, "ingredient_refs": ["egg, whole, raw"]}], "title": "Cook"}], "make_ahead": "Cook the patty ahead; fry eggs fresh.", "cook_time_min": 11, "prep_time_min": 3, "total_time_min": 14, "yield_servings": 1}'::jsonb where id='c6d0535d-e9d3-4a93-9664-2459ecce6aff' and user_id is null;

-- Carnivore Ground Turkey Egg Bake
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat in the oven or microwave.", "storage": "Keeps up to 3 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Heat the oven to 190°C. Brown the ground turkey in a pan, breaking it up, about 6 minutes; season with sea salt and black pepper.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 6, "ingredient_refs": ["ground turkey, raw", "sea salt", "black pepper, ground"]}, {"n": 2, "temp": {"unit": "C", "value": 190}, "text": "Transfer to a small baking dish, whisk the eggs and pour over, scatter the cheddar on top, and bake until set, about 14 minutes.", "type": "cook", "active": false, "appliance": "oven", "duration_min": 14, "ingredient_refs": ["egg, whole, raw", "cheddar cheese"]}], "title": "Bake"}], "make_ahead": "Bake ahead and slice; great for meal prep.", "cook_time_min": 20, "prep_time_min": 4, "total_time_min": 24, "yield_servings": 1}'::jsonb where id='39fad4a6-d996-4d11-9931-adea68b9135c' and user_id is null;

-- Carnivore Halibut Egg Plate
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat gently so the fish does not dry out.", "storage": "Keeps up to 1 day refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Season the halibut with sea salt and black pepper and pan-sear, about 4 minutes per side, until it flakes.", "type": "cook", "active": false, "appliance": "stovetop", "duration_min": 8, "ingredient_refs": ["halibut, atlantic, raw", "sea salt", "black pepper, ground"]}, {"n": 2, "temp": null, "text": "Fry the eggs in the same pan and plate with the halibut.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 4, "ingredient_refs": ["egg, whole, raw"]}], "title": "Cook"}], "make_ahead": "Best cooked fresh.", "cook_time_min": 12, "prep_time_min": 3, "total_time_min": 15, "yield_servings": 1}'::jsonb where id='889c41e9-92a2-4bdc-93fa-0cb93d117042' and user_id is null;

-- Carnivore Hard Boiled Eggs and Bacon
update recipes set recipe_kind='assembly', instructions='{"reheat": "Serve cold or warm the bacon.", "storage": "Keeps up to 3 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Peel and halve the hard-boiled eggs and plate with the bacon.", "type": "prep", "active": true, "appliance": null, "duration_min": 2, "ingredient_refs": ["egg, whole, hard-boiled", "bacon, cured, pan-fried"]}, {"n": 2, "temp": null, "text": "Season with sea salt.", "type": "assemble", "active": true, "appliance": null, "duration_min": 1, "ingredient_refs": ["sea salt"]}], "title": "Assemble"}], "make_ahead": "Boil the eggs and cook the bacon ahead.", "cook_time_min": 0, "prep_time_min": 3, "total_time_min": 3, "yield_servings": 1}'::jsonb where id='d0bb76c8-4ac3-4d54-8f98-703d721198fd' and user_id is null;

-- Carnivore Lamb Egg Skillet
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat the meats; add fresh eggs.", "storage": "Keeps up to 3 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Season the lamb and sear 3-4 minutes per side; brown the ground beef alongside. Slice the lamb.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 10, "ingredient_refs": ["lamb, rib chop, lean, raw", "ground beef, 90% lean, raw"]}, {"n": 2, "temp": null, "text": "Crack the eggs into the skillet and cook to your liking; season with sea salt and black pepper.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 4, "ingredient_refs": ["egg, whole, raw", "sea salt", "black pepper, ground"]}], "title": "Cook"}], "make_ahead": "Cook the meats ahead; add fresh eggs.", "cook_time_min": 14, "prep_time_min": 3, "total_time_min": 17, "yield_servings": 1}'::jsonb where id='6416d467-87e4-457b-955f-16f75e0cffa5' and user_id is null;

-- Carnivore Pork Chop and Eggs
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat the pork; add fresh eggs.", "storage": "Keeps up to 3 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Season the pork chop with sea salt and black pepper and pan-sear, about 4 minutes per side, until cooked through.", "type": "cook", "active": false, "appliance": "stovetop", "duration_min": 10, "ingredient_refs": ["pork chop, lean, raw", "sea salt", "black pepper, ground"]}, {"n": 2, "temp": null, "text": "Whisk the eggs with the heavy cream and softly scramble in the same pan; plate with the pork.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 4, "ingredient_refs": ["egg, whole, raw", "heavy cream"]}], "title": "Cook"}], "make_ahead": "Cook the pork ahead; scramble eggs fresh.", "cook_time_min": 14, "prep_time_min": 3, "total_time_min": 17, "yield_servings": 1}'::jsonb where id='2f261161-9360-4f2b-86f0-90e7045220c3' and user_id is null;

-- Carnivore Shrimp and Egg Scramble
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat gently; eggs are best fresh.", "storage": "Keeps up to 1 day refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Saute the shrimp in a little butter or oil until pink, about 3 minutes; remove and roughly chop.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 3, "ingredient_refs": ["shrimp, raw"]}, {"n": 2, "temp": null, "text": "Whisk the eggs with the heavy cream, softly scramble, and fold the shrimp back in; season with sea salt and black pepper.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 5, "ingredient_refs": ["egg, whole, raw", "heavy cream", "sea salt", "black pepper, ground"]}], "title": "Cook"}], "make_ahead": "Best cooked fresh.", "cook_time_min": 8, "prep_time_min": 3, "total_time_min": 11, "yield_servings": 1}'::jsonb where id='f560a90c-8e84-44e1-8c46-dc03c69f3d81' and user_id is null;

-- Carnivore Sirloin and Eggs Breakfast
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat the steak; add fresh eggs.", "storage": "Keeps up to 3 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Season the sirloin with sea salt and black pepper and sear, 3-4 minutes per side for medium; rest and slice.", "type": "cook", "active": false, "appliance": "stovetop", "duration_min": 10, "ingredient_refs": ["beef, sirloin steak, lean, raw", "sea salt", "black pepper, ground"]}, {"n": 2, "temp": null, "text": "Fry the eggs in the same pan and plate with the steak.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 4, "ingredient_refs": ["egg, whole, raw"]}], "title": "Cook"}], "make_ahead": "Cook the steak ahead; fry eggs fresh.", "cook_time_min": 14, "prep_time_min": 3, "total_time_min": 17, "yield_servings": 1}'::jsonb where id='87873be7-395a-4bc7-90df-958cfc1e12f9' and user_id is null;

-- Carnivore Smoked Salmon Egg Plate
update recipes set recipe_kind='cooked', instructions='{"reheat": "Serve fresh.", "storage": "Keeps up to 1 day refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Whisk the eggs and softly scramble in a little butter; season with sea salt and black pepper.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 5, "ingredient_refs": ["egg, whole, raw", "sea salt", "black pepper, ground"]}, {"n": 2, "temp": null, "text": "Plate with the smoked salmon and a spoonful of cream cheese.", "type": "assemble", "active": true, "appliance": null, "duration_min": 1, "ingredient_refs": ["smoked salmon", "cream cheese"]}], "title": "Cook and plate"}], "make_ahead": "Best cooked fresh.", "cook_time_min": 6, "prep_time_min": 3, "total_time_min": 9, "yield_servings": 1}'::jsonb where id='b7f3eb8f-0cbc-4be0-81fb-0e6954867e3e' and user_id is null;

-- Carnivore Turkey Egg White Skillet
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat the turkey; add fresh eggs.", "storage": "Keeps up to 3 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Dice the turkey breast and cook in a skillet with a splash of beef broth over medium until done, about 9 minutes.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 9, "ingredient_refs": ["turkey breast, raw", "beef broth"]}, {"n": 2, "temp": null, "text": "Push aside and scramble the eggs in the same skillet; season with sea salt and black pepper.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 5, "ingredient_refs": ["egg, whole, raw", "sea salt", "black pepper, ground"]}], "title": "Cook"}], "make_ahead": "Cook the turkey ahead; scramble eggs fresh.", "cook_time_min": 14, "prep_time_min": 3, "total_time_min": 17, "yield_servings": 1}'::jsonb where id='b747b22f-b7a0-49f4-aa25-e57ff4cf781a' and user_id is null;

-- Egg White Avocado Snack
update recipes set recipe_kind='assembly', instructions='{"reheat": "Serve cold.", "storage": "Best fresh; avocado browns over time.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Peel and halve the hard-boiled eggs.", "type": "prep", "active": true, "appliance": null, "duration_min": 1, "ingredient_refs": ["egg, whole, hard-boiled"]}, {"n": 2, "temp": null, "text": "Mash the avocado with lemon juice, sea salt, and black pepper and spoon alongside or over the eggs.", "type": "assemble", "active": true, "appliance": null, "duration_min": 3, "ingredient_refs": ["avocado, raw", "lemon juice, raw", "sea salt", "black pepper, ground"]}], "title": "Assemble"}], "make_ahead": "Boil the eggs ahead; mash the avocado fresh.", "cook_time_min": 0, "prep_time_min": 4, "total_time_min": 4, "yield_servings": 1}'::jsonb where id='8f5053fe-68e3-43c8-9ced-991972d6e2fd' and user_id is null;

-- Greek Yogurt with Walnuts and Honey
update recipes set recipe_kind='assembly', instructions='{"reheat": "Serve cold.", "storage": "Keeps up to 2 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Spoon the Greek yogurt into a bowl.", "type": "prep", "active": true, "appliance": null, "duration_min": 1, "ingredient_refs": ["greek yogurt, plain, nonfat"]}, {"n": 2, "temp": null, "text": "Top with the walnuts and blueberries and drizzle with honey.", "type": "assemble", "active": true, "appliance": null, "duration_min": 2, "ingredient_refs": ["walnuts, raw", "blueberries, raw", "honey"]}], "title": "Assemble"}], "make_ahead": "Assemble fresh or the night before.", "cook_time_min": 0, "prep_time_min": 3, "total_time_min": 3, "yield_servings": 1}'::jsonb where id='f22dfcee-32ae-40e7-902e-af3c21f05b86' and user_id is null;

commit;
