-- ============================================================================
-- seed-cooking-guides-mains-1.sql — authored cooking guides, MAINS archetype (batch 1, 15 recipes)
-- ----------------------------------------------------------------------------
-- Git source of truth for content authored directly in the DB (instructions jsonb + recipe_kind
-- per recipe id). Content UPDATEs only — NOT schema. Idempotent (matches by id); re-runnable.
-- Same pattern + schema as the other seed-cooking-guides-*.sql files.
--
-- Regenerate from the live DB (swap the id-prefix filter for the batch):
--   select string_agg(format('-- %s', name) || E'\n' ||
--     format('update recipes set recipe_kind=%L, instructions=%L::jsonb where id=%L and user_id is null;',
--       recipe_kind, instructions::text, id::text), E'\n\n' order by name)
--   from recipes where user_id is null and instructions is not null and id::text like any(array['3e83de61%', ...]);
--
-- Progress: 206 / 299 cooking guides authored (69%) — salads 26 + smoothies 6 + wraps 5 + soups 15 + bowls 77 + originals 5 + breakfast 57 + mains 15 (batch 1).
-- ============================================================================

begin;

-- Almond Butter and Banana
update recipes set recipe_kind='assembly', instructions='{"reheat": "Serve fresh.", "storage": "Eat immediately; banana browns over time.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Slice the banana onto a plate.", "type": "prep", "active": true, "appliance": null, "duration_min": 1, "ingredient_refs": ["banana, raw"]}, {"n": 2, "temp": null, "text": "Spread or drizzle the almond butter over the banana.", "type": "assemble", "active": true, "appliance": null, "duration_min": 1, "ingredient_refs": ["almond butter"]}], "title": "Assemble"}], "make_ahead": "Best fresh.", "cook_time_min": 0, "prep_time_min": 2, "total_time_min": 2, "yield_servings": 1}'::jsonb where id='3e83de61-2606-4ec7-b65c-dfde677c6d29' and user_id is null;

-- Beef and Broccoli with Rice
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat in a pan.", "storage": "Keeps up to 3 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Slice the sirloin thin and mince the garlic. Whisk the soy sauce, sesame oil, and cornstarch with a splash of water into a sauce.", "type": "prep", "active": true, "appliance": null, "duration_min": 6, "ingredient_refs": ["beef, sirloin steak, lean, raw", "garlic, raw", "soy sauce", "sesame oil", "cornstarch"]}], "title": "Prep"}, {"steps": [{"n": 2, "temp": null, "text": "Sear the beef in a hot pan until browned, about 4 minutes, then remove. Stir-fry the broccoli with the garlic until tender-crisp, about 5 minutes.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 9, "ingredient_refs": ["broccoli, raw"]}, {"n": 3, "temp": null, "text": "Return the beef, pour in the sauce, and toss until glossy and thickened, about 2 minutes. Serve over the brown rice.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 3, "ingredient_refs": ["brown rice, cooked"]}], "title": "Stir-fry"}], "make_ahead": "Cook the rice ahead; stir-fry fresh.", "cook_time_min": 12, "prep_time_min": 8, "total_time_min": 20, "yield_servings": 1}'::jsonb where id='21ddc19a-ff17-4c57-b0b9-ac5661b83ef0' and user_id is null;

-- Carnivore Beef Liver and Bacon
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat very gently.", "storage": "Keeps up to 1 day refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Crisp the bacon in a pan, then set aside, leaving the fat.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 4, "ingredient_refs": ["bacon, cured, pan-fried"]}, {"n": 2, "temp": null, "text": "Pat the liver dry, season with sea salt and black pepper, and sear in the bacon fat, about 2 minutes per side (keep it just pink inside); deglaze with a splash of beef broth.", "type": "cook", "active": false, "appliance": "stovetop", "duration_min": 8, "ingredient_refs": ["beef liver, raw", "sea salt", "black pepper, ground", "beef broth"]}], "title": "Cook"}], "make_ahead": "Best cooked fresh; liver toughens when overcooked or reheated.", "cook_time_min": 12, "prep_time_min": 3, "total_time_min": 15, "yield_servings": 1}'::jsonb where id='06387462-4bd1-4bde-bfff-2ae66fadfee4' and user_id is null;

-- Carnivore Beef Liver and Bacon Plate
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat very gently.", "storage": "Keeps up to 1 day refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Crisp the bacon in a pan and set aside, leaving the fat.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 4, "ingredient_refs": ["bacon, cured, pan-fried"]}, {"n": 2, "temp": null, "text": "Season the liver with sea salt and black pepper and sear in the bacon fat, about 2 minutes per side, keeping it just pink inside. Plate with the bacon.", "type": "cook", "active": false, "appliance": "stovetop", "duration_min": 6, "ingredient_refs": ["beef liver, raw", "sea salt", "black pepper, ground"]}], "title": "Cook"}], "make_ahead": "Best cooked fresh.", "cook_time_min": 10, "prep_time_min": 3, "total_time_min": 13, "yield_servings": 1}'::jsonb where id='73e3a60f-b8c9-493f-b3d4-c28cad46a89f' and user_id is null;

-- Carnivore Beef Liver Bacon Dinner
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat very gently.", "storage": "Keeps up to 1 day refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Crisp the bacon and set aside, leaving the fat.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 4, "ingredient_refs": ["bacon, cured, pan-fried"]}, {"n": 2, "temp": null, "text": "Season the liver with sea salt and black pepper, sear in the bacon fat about 2 minutes per side, and deglaze with a splash of beef broth. Plate with the bacon.", "type": "cook", "active": false, "appliance": "stovetop", "duration_min": 8, "ingredient_refs": ["beef liver, raw", "sea salt", "black pepper, ground", "beef broth"]}], "title": "Cook"}], "make_ahead": "Best cooked fresh.", "cook_time_min": 12, "prep_time_min": 3, "total_time_min": 15, "yield_servings": 1}'::jsonb where id='ea8c1eeb-12b5-4d00-893b-951988b83dee' and user_id is null;

-- Carnivore Ground Beef Snack Patties
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat in a pan or microwave.", "storage": "Keeps up to 3 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Form the ground beef into small patties and season with sea salt and black pepper.", "type": "prep", "active": true, "appliance": null, "duration_min": 3, "ingredient_refs": ["ground beef, 80% lean, raw", "sea salt", "black pepper, ground"]}, {"n": 2, "temp": null, "text": "Pan-fry over medium-high, about 3 minutes per side, until browned and cooked through.", "type": "cook", "active": false, "appliance": "stovetop", "duration_min": 10, "ingredient_refs": []}], "title": "Cook"}], "make_ahead": "Make up to 3 days ahead; great protein snack.", "cook_time_min": 10, "prep_time_min": 3, "total_time_min": 13, "yield_servings": 1}'::jsonb where id='ef909012-e3b1-4398-a3f6-5ba2cbe90ecf' and user_id is null;

-- Carnivore Ground Turkey Patties
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat in a pan or microwave.", "storage": "Keeps up to 3 days refrigerated or 2 months frozen.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Mix the ground turkey with the egg, sea salt, and black pepper and form into patties.", "type": "prep", "active": true, "appliance": null, "duration_min": 5, "ingredient_refs": ["ground turkey, raw", "egg, whole, raw", "sea salt", "black pepper, ground"]}, {"n": 2, "temp": null, "text": "Pan-fry over medium, about 4 minutes per side, until cooked through.", "type": "cook", "active": false, "appliance": "stovetop", "duration_min": 10, "ingredient_refs": []}], "title": "Cook"}], "make_ahead": "Make up to 3 days ahead; great for meal prep.", "cook_time_min": 10, "prep_time_min": 5, "total_time_min": 15, "yield_servings": 1}'::jsonb where id='bc67de15-c079-41cd-877d-ae033d3dd123' and user_id is null;

-- Carnivore Ground Turkey Snack Bites
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat in a pan or microwave.", "storage": "Keeps up to 3 days refrigerated or 2 months frozen.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Season the ground turkey with sea salt and black pepper and roll into small bite-sized balls.", "type": "prep", "active": true, "appliance": null, "duration_min": 4, "ingredient_refs": ["ground turkey, raw", "sea salt", "black pepper, ground"]}, {"n": 2, "temp": null, "text": "Pan-fry over medium, turning, until browned and cooked through, about 10 minutes.", "type": "cook", "active": false, "appliance": "stovetop", "duration_min": 10, "ingredient_refs": []}], "title": "Cook"}], "make_ahead": "Make up to 3 days ahead; great protein snack.", "cook_time_min": 10, "prep_time_min": 4, "total_time_min": 14, "yield_servings": 1}'::jsonb where id='eaf21e9f-00b7-4cbf-98cd-497f4d9a2067' and user_id is null;

-- Carnivore Halibut Dinner
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat gently so the fish does not dry out.", "storage": "Keeps up to 1 day refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Season the halibut with sea salt and black pepper.", "type": "prep", "active": true, "appliance": null, "duration_min": 2, "ingredient_refs": ["halibut, atlantic, raw", "sea salt", "black pepper, ground"]}, {"n": 2, "temp": null, "text": "Pan-sear in a little butter about 4 minutes per side, then swirl the heavy cream into the pan to make a light sauce and spoon over.", "type": "cook", "active": false, "appliance": "stovetop", "duration_min": 9, "ingredient_refs": ["heavy cream"]}], "title": "Cook"}], "make_ahead": "Best cooked fresh.", "cook_time_min": 9, "prep_time_min": 3, "total_time_min": 12, "yield_servings": 1}'::jsonb where id='a80fe7d7-f3ff-4e96-935d-82b492d00b98' and user_id is null;

-- Carnivore Halibut Lunch Plate
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat gently so the fish does not dry out.", "storage": "Keeps up to 1 day refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Season the halibut with sea salt and black pepper.", "type": "prep", "active": true, "appliance": null, "duration_min": 2, "ingredient_refs": ["halibut, atlantic, raw", "sea salt", "black pepper, ground"]}, {"n": 2, "temp": null, "text": "Pan-sear in a little butter about 4 minutes per side, then finish with a spoonful of heavy cream from the pan.", "type": "cook", "active": false, "appliance": "stovetop", "duration_min": 9, "ingredient_refs": ["heavy cream"]}], "title": "Cook"}], "make_ahead": "Best cooked fresh.", "cook_time_min": 9, "prep_time_min": 3, "total_time_min": 12, "yield_servings": 1}'::jsonb where id='7998ddb0-3586-44ca-a366-049dce5e5200' and user_id is null;

-- Carnivore Lamb Chop Lunch Plate
update recipes set recipe_kind='cooked', instructions='{"reheat": "Serve cold or gently warmed.", "storage": "Keeps up to 2 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Season the lamb chop with sea salt and black pepper.", "type": "prep", "active": true, "appliance": null, "duration_min": 2, "ingredient_refs": ["lamb, rib chop, lean, raw", "sea salt", "black pepper, ground"]}, {"n": 2, "temp": null, "text": "Sear in a hot pan 3-4 minutes per side for medium; rest 3 minutes before serving.", "type": "cook", "active": false, "appliance": "stovetop", "duration_min": 9, "ingredient_refs": []}], "title": "Cook"}], "make_ahead": "Best cooked fresh; can be cooked up to 2 days ahead.", "cook_time_min": 11, "prep_time_min": 3, "total_time_min": 14, "yield_servings": 1}'::jsonb where id='7937e4a2-d1c9-4750-a1a6-e18adc4f717b' and user_id is null;

-- Carnivore Lamb Rack Dinner Plate
update recipes set recipe_kind='cooked', instructions='{"reheat": "Serve cold or gently warmed.", "storage": "Keeps up to 2 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Season the lamb with sea salt and black pepper.", "type": "prep", "active": true, "appliance": null, "duration_min": 2, "ingredient_refs": ["lamb, rib chop, lean, raw", "sea salt", "black pepper, ground"]}, {"n": 2, "temp": null, "text": "Sear in a hot pan to brown all over, about 8 minutes total for medium; rest 5 minutes before serving.", "type": "cook", "active": false, "appliance": "stovetop", "duration_min": 12, "ingredient_refs": []}], "title": "Cook"}], "make_ahead": "Best cooked fresh.", "cook_time_min": 14, "prep_time_min": 3, "total_time_min": 17, "yield_servings": 1}'::jsonb where id='fd949c1a-5336-4d6d-9ab0-d7161e986a02' and user_id is null;

-- Carnivore NY Strip Steak Dinner
update recipes set recipe_kind='cooked', instructions='{"reheat": "Serve cold or gently warmed.", "storage": "Keeps up to 3 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Season the steak generously with sea salt and black pepper.", "type": "prep", "active": true, "appliance": null, "duration_min": 2, "ingredient_refs": ["beef, sirloin steak, lean, raw", "sea salt", "black pepper, ground"]}, {"n": 2, "temp": null, "text": "Sear in a hot pan 3-4 minutes per side for medium, deglaze with a splash of beef broth for a quick jus, and rest 5 minutes before slicing.", "type": "cook", "active": false, "appliance": "stovetop", "duration_min": 10, "ingredient_refs": ["beef broth"]}], "title": "Cook"}], "make_ahead": "Best cooked fresh.", "cook_time_min": 12, "prep_time_min": 3, "total_time_min": 15, "yield_servings": 1}'::jsonb where id='61ca67fd-f3cd-410e-908a-c0fcf3414a41' and user_id is null;

-- Carnivore Pork Chop Dinner
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat gently.", "storage": "Keeps up to 3 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Season the pork chop with sea salt and black pepper.", "type": "prep", "active": true, "appliance": null, "duration_min": 2, "ingredient_refs": ["pork chop, lean, raw", "sea salt", "black pepper, ground"]}, {"n": 2, "temp": null, "text": "Pan-sear about 4 minutes per side until cooked through, then swirl the heavy cream into the pan to make a light sauce and spoon over.", "type": "cook", "active": false, "appliance": "stovetop", "duration_min": 10, "ingredient_refs": ["heavy cream"]}], "title": "Cook"}], "make_ahead": "Cook up to 3 days ahead.", "cook_time_min": 12, "prep_time_min": 3, "total_time_min": 15, "yield_servings": 1}'::jsonb where id='cb822b7a-70dc-4a55-835f-e049040ab53e' and user_id is null;

-- Carnivore Pork Rind Cream Cheese Snack
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat gently.", "storage": "Keeps up to 3 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Season the pork chop with sea salt and black pepper and pan-sear about 4 minutes per side until cooked through; slice.", "type": "cook", "active": false, "appliance": "stovetop", "duration_min": 10, "ingredient_refs": ["pork chop, lean, raw", "sea salt", "black pepper, ground"]}, {"n": 2, "temp": null, "text": "Serve with the cream cheese for dipping or spreading.", "type": "assemble", "active": true, "appliance": null, "duration_min": 2, "ingredient_refs": ["cream cheese"]}], "title": "Cook"}], "make_ahead": "Cook the pork ahead.", "cook_time_min": 12, "prep_time_min": 3, "total_time_min": 15, "yield_servings": 1}'::jsonb where id='9f2cfd1e-5abf-4bd4-81de-9f69f7babb25' and user_id is null;

commit;
