-- ============================================================================
-- seed-cooking-guides-mains-3.sql — authored cooking guides, MAINS archetype (batch 3, 15 recipes)
-- ----------------------------------------------------------------------------
-- Git source of truth for content authored directly in the DB (instructions jsonb + recipe_kind
-- per recipe id). Content UPDATEs only — NOT schema. Idempotent (matches by id); re-runnable.
-- Same pattern + schema as the other seed-cooking-guides-*.sql files.
--
-- Regenerate from the live DB (swap the id-prefix filter for the batch):
--   select string_agg(format('-- %s', name) || E'\n' ||
--     format('update recipes set recipe_kind=%L, instructions=%L::jsonb where id=%L and user_id is null;',
--       recipe_kind, instructions::text, id::text), E'\n\n' order by name)
--   from recipes where user_id is null and instructions is not null and id::text like any(array['1a285fc5%', ...]);
--
-- Progress: 236 / 299 cooking guides authored (79%) — salads 26 + smoothies 6 + wraps 5 + soups 15 + bowls 77 + originals 5 + breakfast 57 + mains 45 (batches 1-3).
-- ============================================================================

begin;

-- Halibut with Asparagus and Lemon
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat gently so the fish does not dry out.", "storage": "Keeps up to 1 day refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Mince the garlic. Trim the asparagus and roast or pan-saute in olive oil with the garlic until tender-crisp, about 8 minutes.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 8, "ingredient_refs": ["garlic, raw", "asparagus, raw", "olive oil"]}, {"n": 2, "temp": null, "text": "Season the halibut with sea salt and pan-sear about 4 minutes per side until it flakes; finish with lemon juice.", "type": "cook", "active": false, "appliance": "stovetop", "duration_min": 7, "ingredient_refs": ["halibut, atlantic, raw", "lemon juice, raw"]}], "title": "Cook"}], "make_ahead": "Best cooked fresh.", "cook_time_min": 15, "prep_time_min": 5, "total_time_min": 20, "yield_servings": 1}'::jsonb where id='1a285fc5-2ce7-469f-af53-f6662fc459f8' and user_id is null;

-- Keto Almond Butter Celery Sticks
update recipes set recipe_kind='assembly', instructions='{"reheat": "Serve cold.", "storage": "Keeps up to 2 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Cut the celery into sticks.", "type": "prep", "active": true, "appliance": null, "duration_min": 2, "ingredient_refs": ["celery, raw"]}, {"n": 2, "temp": null, "text": "Fill the grooves with almond butter and sprinkle with sea salt.", "type": "assemble", "active": true, "appliance": null, "duration_min": 2, "ingredient_refs": ["almond butter", "sea salt"]}], "title": "Assemble"}], "make_ahead": "Assemble fresh; cut celery ahead.", "cook_time_min": 0, "prep_time_min": 4, "total_time_min": 4, "yield_servings": 1}'::jsonb where id='4965dc37-5ce1-433a-afb7-ce2fbb01f1a7' and user_id is null;

-- Keto Avocado Cream Cheese Bites
update recipes set recipe_kind='assembly', instructions='{"reheat": "Serve cold.", "storage": "Keeps up to 1 day refrigerated with lemon to slow browning.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Halve the avocado and mash with the cream cheese, lemon juice, sea salt, and black pepper.", "type": "prep", "active": true, "appliance": null, "duration_min": 4, "ingredient_refs": ["avocado, raw", "cream cheese", "lemon juice, raw", "sea salt", "black pepper, ground"]}, {"n": 2, "temp": null, "text": "Spoon into bite-sized portions or scoop back into the avocado skin to serve.", "type": "assemble", "active": true, "appliance": null, "duration_min": 2, "ingredient_refs": []}], "title": "Assemble"}], "make_ahead": "Best fresh; avocado browns over time.", "cook_time_min": 0, "prep_time_min": 6, "total_time_min": 6, "yield_servings": 1}'::jsonb where id='02e519eb-c24e-4928-9ee8-de63d09d0ee0' and user_id is null;

-- Keto Avocado Tuna Lettuce Cups
update recipes set recipe_kind='assembly', instructions='{"reheat": "Serve cold.", "storage": "Keeps up to 1 day refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Drain the tuna and mash with the avocado, lemon juice, dijon mustard, and sea salt.", "type": "prep", "active": true, "appliance": null, "duration_min": 4, "ingredient_refs": ["tuna, canned in water, drained", "avocado, raw", "lemon juice, raw", "dijon mustard", "sea salt"]}, {"n": 2, "temp": null, "text": "Spoon into the romaine leaves to serve as cups.", "type": "assemble", "active": true, "appliance": null, "duration_min": 3, "ingredient_refs": ["romaine lettuce"]}], "title": "Assemble"}], "make_ahead": "Make the tuna salad up to 1 day ahead; fill fresh.", "cook_time_min": 0, "prep_time_min": 7, "total_time_min": 7, "yield_servings": 1}'::jsonb where id='74a63103-473b-4568-9863-71ea7fd145e2' and user_id is null;

-- Keto Beef Meatballs with Zucchini Noodles
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat the meatballs; toss with fresh zucchini.", "storage": "Keeps up to 3 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Mince the garlic and mix into the ground beef with the egg and parmesan; roll into meatballs.", "type": "prep", "active": true, "appliance": null, "duration_min": 8, "ingredient_refs": ["garlic, raw", "ground beef, 80% lean, raw", "egg, whole, raw", "parmesan cheese, shredded"]}, {"n": 2, "temp": null, "text": "Brown the meatballs in olive oil, turning, until cooked through, about 12 minutes.", "type": "cook", "active": false, "appliance": "stovetop", "duration_min": 12, "ingredient_refs": ["olive oil"]}], "title": "Make the meatballs"}, {"steps": [{"n": 3, "temp": null, "text": "Spiralize the zucchini into noodles and toss in the pan to soften, about 3 minutes; serve with the meatballs.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 3, "ingredient_refs": ["zucchini, raw"]}], "title": "Finish"}], "make_ahead": "Make the meatballs up to 3 days ahead; cook the zucchini fresh.", "cook_time_min": 18, "prep_time_min": 10, "total_time_min": 28, "yield_servings": 1}'::jsonb where id='53b901a9-d58d-487c-93a9-ace022525162' and user_id is null;

-- Keto Beef Zucchini Lasagna
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat in the oven or microwave.", "storage": "Keeps up to 3 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Brown the ground beef, breaking it up, about 7 minutes; add the diced tomatoes and italian seasoning and simmer 8 minutes. Season with sea salt.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 15, "ingredient_refs": ["ground beef, 80% lean, raw", "tomato products, canned, diced", "italian seasoning", "sea salt"]}], "title": "Make the sauce"}, {"steps": [{"n": 2, "temp": null, "text": "Heat the oven to 190°C. Slice the zucchini lengthwise into planks. Layer zucchini, meat sauce, ricotta, and mozzarella, repeating and finishing with mozzarella.", "type": "prep", "active": true, "appliance": null, "duration_min": 8, "ingredient_refs": ["zucchini, raw", "ricotta cheese, whole milk", "mozzarella cheese"]}, {"n": 3, "temp": {"unit": "C", "value": 190}, "text": "Bake until bubbling and golden, about 20 minutes; rest 5 minutes before serving.", "type": "cook", "active": false, "appliance": "oven", "duration_min": 20, "ingredient_refs": []}], "title": "Layer and bake"}], "make_ahead": "Assemble up to 1 day ahead and bake fresh; or bake and reheat.", "cook_time_min": 35, "prep_time_min": 15, "total_time_min": 50, "yield_servings": 1}'::jsonb where id='8a331325-44a1-4786-b421-6eed2f1ba059' and user_id is null;

-- Keto Cauliflower Fried Rice
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat in a pan.", "storage": "Keeps up to 3 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Pulse the cauliflower into rice. Mince the garlic. Crisp the chopped bacon in a pan, then add the garlic and cauliflower rice and stir-fry in sesame oil until tender, about 8 minutes.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 10, "ingredient_refs": ["cauliflower, raw", "garlic, raw", "bacon, cured, pan-fried", "sesame oil"]}, {"n": 2, "temp": null, "text": "Push aside, scramble the egg in the pan, then toss everything together with soy sauce.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 4, "ingredient_refs": ["egg, whole, raw", "soy sauce"]}], "title": "Cook"}], "make_ahead": "Great for meal prep; make up to 3 days ahead.", "cook_time_min": 14, "prep_time_min": 6, "total_time_min": 20, "yield_servings": 1}'::jsonb where id='6021f7c4-4210-4d08-9680-c4fdc103566d' and user_id is null;

-- Keto Cheddar Beef Stuffed Peppers
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat in the oven or microwave.", "storage": "Keeps up to 3 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Dice the onion and saute until soft, about 3 minutes; add the ground beef and brown, about 7 minutes. Season with sea salt and black pepper.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 10, "ingredient_refs": ["onions, raw", "ground beef, 80% lean, raw", "sea salt", "black pepper, ground"]}], "title": "Make the filling"}, {"steps": [{"n": 2, "temp": null, "text": "Heat the oven to 190°C. Halve and seed the bell peppers, fill with the beef, and top with cheddar.", "type": "prep", "active": true, "appliance": null, "duration_min": 4, "ingredient_refs": ["bell peppers, raw", "cheddar cheese"]}, {"n": 3, "temp": {"unit": "C", "value": 190}, "text": "Bake until the peppers are tender and the cheese is melted, about 22 minutes.", "type": "cook", "active": false, "appliance": "oven", "duration_min": 22, "ingredient_refs": []}], "title": "Stuff and bake"}], "make_ahead": "Stuff up to 1 day ahead and bake fresh.", "cook_time_min": 32, "prep_time_min": 8, "total_time_min": 40, "yield_servings": 1}'::jsonb where id='22e51f6a-2a3b-40c1-ada6-87d279e7ffa9' and user_id is null;

-- Keto Cheese Almond Snack Plate
update recipes set recipe_kind='assembly', instructions='{"reheat": "Serve cold.", "storage": "Keeps up to 2 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Cube the cheddar and slice the cucumber.", "type": "prep", "active": true, "appliance": null, "duration_min": 3, "ingredient_refs": ["cheddar cheese", "cucumber, raw"]}, {"n": 2, "temp": null, "text": "Arrange on a plate with the almonds and sprinkle with sea salt.", "type": "assemble", "active": true, "appliance": null, "duration_min": 2, "ingredient_refs": ["almonds, raw", "sea salt"]}], "title": "Assemble"}], "make_ahead": "Assemble in minutes; pack ahead for a snack.", "cook_time_min": 0, "prep_time_min": 5, "total_time_min": 5, "yield_servings": 1}'::jsonb where id='3329e8f6-7a40-43b8-bead-0b7f3386cd0b' and user_id is null;

-- Keto Chicken Parmesan Style
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat in the oven.", "storage": "Keeps up to 3 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Season the chicken with sea salt and italian seasoning and pan-sear in olive oil until golden, about 5 minutes per side.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 10, "ingredient_refs": ["chicken breast, broilers or fryers, raw", "sea salt", "italian seasoning", "olive oil"]}], "title": "Cook the chicken"}, {"steps": [{"n": 2, "temp": {"unit": "C", "value": 190}, "text": "Heat the oven to 190°C. Spoon the diced tomatoes over the chicken, top with mozzarella and parmesan, and bake until the cheese melts and the chicken is cooked through, about 14 minutes.", "type": "cook", "active": false, "appliance": "oven", "duration_min": 14, "ingredient_refs": ["tomato products, canned, diced", "mozzarella cheese", "parmesan cheese"]}], "title": "Sauce and melt"}], "make_ahead": "Best baked fresh; components can be prepped ahead.", "cook_time_min": 24, "prep_time_min": 6, "total_time_min": 30, "yield_servings": 1}'::jsonb where id='e4627bc6-0d34-43be-b6b3-96dfafe0223f' and user_id is null;

-- Keto Chicken Thigh Asparagus Plate
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat gently.", "storage": "Keeps up to 3 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Mince the garlic. Trim the asparagus and saute in olive oil with the garlic until tender-crisp, about 8 minutes; finish with lemon juice.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 8, "ingredient_refs": ["garlic, raw", "asparagus, raw", "olive oil", "lemon juice, raw"]}, {"n": 2, "temp": {"unit": "C", "value": 74}, "text": "Season the chicken with sea salt and pan-sear until golden and cooked through, about 5-6 minutes per side (74°C internal).", "type": "cook", "active": false, "appliance": "stovetop", "duration_min": 10, "ingredient_refs": ["chicken breast, broilers or fryers, raw", "sea salt"]}], "title": "Cook"}], "make_ahead": "Cook up to 3 days ahead; great for meal prep.", "cook_time_min": 18, "prep_time_min": 5, "total_time_min": 23, "yield_servings": 1}'::jsonb where id='06978a1e-dc74-4d1f-ad91-39a38d22f405' and user_id is null;

-- Keto Cod Parmesan Crust Dinner
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat in the oven or air fryer to keep the crust crisp.", "storage": "Keeps up to 1 day refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Mix the parmesan and almond flour with sea salt and black pepper and press onto the cod to form a crust.", "type": "prep", "active": true, "appliance": null, "duration_min": 5, "ingredient_refs": ["parmesan cheese", "almond flour", "sea salt", "black pepper, ground", "cod, atlantic, raw"]}, {"n": 2, "temp": null, "text": "Pan-fry in olive oil about 4 minutes per side until the crust is golden and the fish flakes.", "type": "cook", "active": false, "appliance": "stovetop", "duration_min": 10, "ingredient_refs": ["olive oil"]}], "title": "Cook"}], "make_ahead": "Best cooked fresh.", "cook_time_min": 14, "prep_time_min": 6, "total_time_min": 20, "yield_servings": 1}'::jsonb where id='d8e839dd-84f0-4f43-a3f4-1adce5b3b776' and user_id is null;

-- Keto Halibut Herb Butter Dinner
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat gently so the fish does not dry out.", "storage": "Keeps up to 1 day refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Mince the garlic and warm it with olive oil, lemon juice, and rosemary into a herb oil.", "type": "prep", "active": true, "appliance": null, "duration_min": 3, "ingredient_refs": ["garlic, raw", "olive oil", "lemon juice, raw", "rosemary, fresh"]}, {"n": 2, "temp": null, "text": "Season the halibut with sea salt and pan-sear about 4 minutes per side until it flakes; spoon the herb oil over.", "type": "cook", "active": false, "appliance": "stovetop", "duration_min": 9, "ingredient_refs": ["halibut, atlantic, raw", "sea salt"]}], "title": "Cook"}], "make_ahead": "Best cooked fresh.", "cook_time_min": 12, "prep_time_min": 5, "total_time_min": 17, "yield_servings": 1}'::jsonb where id='f89c3082-5fbd-4ce7-bf74-4857e0cc2bbc' and user_id is null;

-- Keto Lamb Cauliflower Mash Plate
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat the mash; gently warm the lamb.", "storage": "Keeps up to 3 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Cut the cauliflower into florets and steam until very tender, about 12 minutes; mash with the heavy cream and sea salt until smooth.", "type": "cook", "active": false, "appliance": "stovetop", "duration_min": 14, "ingredient_refs": ["cauliflower, raw", "heavy cream", "sea salt"]}], "title": "Make the mash"}, {"steps": [{"n": 2, "temp": null, "text": "Season the lamb with sea salt and rosemary and sear in olive oil 3-4 minutes per side for medium; rest and serve over the mash.", "type": "cook", "active": false, "appliance": "stovetop", "duration_min": 10, "ingredient_refs": ["lamb, rib chop, lean, raw", "rosemary, fresh", "olive oil"]}], "title": "Cook the lamb"}], "make_ahead": "Make the mash up to 3 days ahead; cook the lamb fresh.", "cook_time_min": 24, "prep_time_min": 6, "total_time_min": 30, "yield_servings": 1}'::jsonb where id='49fa64c5-c569-4967-8f66-e6fb087bc7dd' and user_id is null;

-- Keto Mozzarella Stuffed Meatballs
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat in the oven or microwave.", "storage": "Keeps up to 3 days refrigerated or 2 months frozen.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Mix the ground beef with the egg, almond flour, italian seasoning, and sea salt. Cube the mozzarella.", "type": "prep", "active": true, "appliance": null, "duration_min": 8, "ingredient_refs": ["ground beef, 80% lean, raw", "egg, whole, raw", "almond flour", "italian seasoning", "sea salt", "mozzarella cheese"]}, {"n": 2, "temp": null, "text": "Wrap each meatball around a cube of mozzarella, sealing well, then pan-fry over medium, turning, until browned and cooked through, about 16 minutes.", "type": "cook", "active": false, "appliance": "stovetop", "duration_min": 16, "ingredient_refs": []}], "title": "Make and cook the meatballs"}], "make_ahead": "Make up to 3 days ahead; reheats well.", "cook_time_min": 16, "prep_time_min": 12, "total_time_min": 28, "yield_servings": 1}'::jsonb where id='e9b4bab2-9341-43d3-9536-1282d3b3189c' and user_id is null;

commit;
