-- ============================================================================
-- seed-cooking-guides-smoothies-wraps.sql — authored cooking guides (11 recipes)
--   6 SMOOTHIES/SHAKES + 5 WRAPS
-- ----------------------------------------------------------------------------
-- Git source of truth for content authored directly in the DB (instructions jsonb + recipe_kind
-- per recipe id). Content UPDATEs only — NOT schema. Idempotent (matches by id); re-runnable.
-- Same pattern + schema as scripts/reclassify-diet-tags.sql / seed-cooking-guides-salads.sql.
--
-- Regenerate from the live DB (swap the id-prefix filter for the batch):
--   select string_agg(format('-- %s', name) || E'\n' ||
--     format('update recipes set recipe_kind=%L, instructions=%L::jsonb where id=%L and user_id is null;',
--       recipe_kind, instructions::text, id::text), E'\n\n' order by name)
--   from recipes where user_id is null and id::text like any(array['ac85e83e%', ...]);
--
-- Progress: 42 / 299 cooking guides authored (salads 26 + smoothies 6 + wraps 5 + originals).
-- ============================================================================

begin;

-- ── SMOOTHIES & SHAKES (6) ──────────────────────────────────────────────────

-- Paleo Coconut Mango Smoothie Bowl
update recipes set recipe_kind='assembly', instructions='{"reheat": "Serve cold.", "storage": "Eat immediately.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Blend the mango, banana, coconut milk, and pineapple until thick and smooth.", "type": "prep", "active": true, "appliance": "blender", "duration_min": 3, "ingredient_refs": ["mango, raw", "banana, raw", "coconut milk", "pineapple, raw"]}, {"n": 2, "temp": null, "text": "Pour into a bowl and top with the hemp seeds and chia seeds.", "type": "assemble", "active": true, "appliance": null, "duration_min": 3, "ingredient_refs": ["hemp seeds, hulled", "chia seeds"]}], "title": "Blend and top"}], "make_ahead": "Freeze the fruit ahead for a thicker bowl.", "cook_time_min": 0, "prep_time_min": 6, "total_time_min": 6, "yield_servings": 1}'::jsonb where id='2bac3d04-c0be-47ed-ac64-b59d92c03067' and user_id is null;

-- Protein Shake with Oats
update recipes set recipe_kind='assembly', instructions='{"reheat": "Serve cold.", "storage": "Drink immediately; refrigerate up to 1 day and re-blend.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Add the whey protein, milk, rolled oats, and banana to a blender.", "type": "prep", "active": true, "appliance": null, "duration_min": 2, "ingredient_refs": ["whey protein powder", "whole milk", "rolled oats", "banana, raw"]}, {"n": 2, "temp": null, "text": "Blend until smooth and creamy, about 60 seconds. Add a little water or ice to loosen if needed.", "type": "assemble", "active": true, "appliance": "blender", "duration_min": 2, "ingredient_refs": []}], "title": "Blend"}], "make_ahead": "Best blended fresh; soak the oats in the milk overnight for a smoother texture.", "cook_time_min": 0, "prep_time_min": 5, "total_time_min": 5, "yield_servings": 1}'::jsonb where id='ac85e83e-3fb1-4e2b-b118-572c50b731c6' and user_id is null;

-- Vegan Cashew Berry Smoothie
update recipes set recipe_kind='assembly', instructions='{"reheat": "Serve cold.", "storage": "Drink immediately; refrigerate up to 1 day and re-blend.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Add the cashews, blueberries, banana, coconut milk, and plant protein to a blender.", "type": "prep", "active": true, "appliance": null, "duration_min": 2, "ingredient_refs": ["cashews, raw", "blueberries, raw", "banana, raw", "coconut milk", "protein powder, plant-based"]}, {"n": 2, "temp": null, "text": "Blend until completely smooth, about 60 seconds, adding water or ice to reach the texture you like.", "type": "assemble", "active": true, "appliance": "blender", "duration_min": 2, "ingredient_refs": []}], "title": "Blend"}], "make_ahead": "Soak the cashews for a smoother blend.", "cook_time_min": 0, "prep_time_min": 5, "total_time_min": 5, "yield_servings": 1}'::jsonb where id='ad666ae6-b4b7-4da0-bfc4-233c3ee1456b' and user_id is null;

-- Vegan Flaxseed Blueberry Smoothie Bowl
update recipes set recipe_kind='assembly', instructions='{"reheat": "Serve cold.", "storage": "Eat immediately.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Blend the blueberries, banana, ground flaxseed, plant protein, and coconut milk until thick and smooth.", "type": "prep", "active": true, "appliance": "blender", "duration_min": 3, "ingredient_refs": ["blueberries, raw", "banana, raw", "flaxseed, ground", "protein powder, plant-based", "coconut milk"]}, {"n": 2, "temp": null, "text": "Pour into a bowl and top with the hemp seeds.", "type": "assemble", "active": true, "appliance": null, "duration_min": 3, "ingredient_refs": ["hemp seeds, hulled"]}], "title": "Blend and top"}], "make_ahead": "Freeze the fruit ahead for a thicker bowl.", "cook_time_min": 0, "prep_time_min": 6, "total_time_min": 6, "yield_servings": 1}'::jsonb where id='31006413-ba86-4206-8273-2d22a59d3975' and user_id is null;

-- Vegan Hemp Seed Protein Smoothie
update recipes set recipe_kind='assembly', instructions='{"reheat": "Serve cold.", "storage": "Drink immediately; refrigerate up to 1 day and re-blend.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Add the hemp seeds, banana, blueberries, plant protein, coconut milk, and chia seeds to a blender.", "type": "prep", "active": true, "appliance": null, "duration_min": 2, "ingredient_refs": ["hemp seeds, hulled", "banana, raw", "blueberries, raw", "protein powder, plant-based", "coconut milk", "chia seeds"]}, {"n": 2, "temp": null, "text": "Blend until smooth, about 60 seconds. Let it sit a minute so the chia thickens slightly.", "type": "assemble", "active": true, "appliance": "blender", "duration_min": 2, "ingredient_refs": []}], "title": "Blend"}], "make_ahead": "Best fresh.", "cook_time_min": 0, "prep_time_min": 5, "total_time_min": 5, "yield_servings": 1}'::jsonb where id='20f7b50f-a8ee-416e-b98d-dfeabd69c4ce' and user_id is null;

-- Whey Protein Berry Shake
update recipes set recipe_kind='assembly', instructions='{"reheat": "Serve cold.", "storage": "Drink immediately; refrigerate up to 1 day and re-blend.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Add the whey protein, blueberries, banana, milk, and chia seeds to a blender.", "type": "prep", "active": true, "appliance": null, "duration_min": 2, "ingredient_refs": ["whey protein powder", "blueberries, raw", "banana, raw", "whole milk", "chia seeds"]}, {"n": 2, "temp": null, "text": "Blend until smooth, about 45 seconds, adding ice for a thicker shake.", "type": "assemble", "active": true, "appliance": "blender", "duration_min": 2, "ingredient_refs": []}], "title": "Blend"}], "make_ahead": "Best fresh.", "cook_time_min": 0, "prep_time_min": 4, "total_time_min": 4, "yield_servings": 1}'::jsonb where id='0415931f-94d5-4d7f-b919-fd431e28d9d9' and user_id is null;

-- ── WRAPS (5) ───────────────────────────────────────────────────────────────

-- Paleo Beef Lettuce Wrap
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat the beef in a pan or microwave before filling.", "storage": "Store the beef up to 3 days refrigerated; fill the lettuce fresh.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Dice the onion. Brown the ground beef with the onion in a little olive oil over medium-high, 6-7 minutes, breaking it up as it cooks.", "type": "cook", "active": false, "appliance": "stovetop", "duration_min": 7, "ingredient_refs": ["ground beef, 90% lean, raw", "onions, raw", "olive oil"]}, {"n": 2, "temp": null, "text": "Season with cumin and a pinch of salt and stir through.", "type": "prep", "active": true, "appliance": null, "duration_min": 1, "ingredient_refs": ["cumin, ground"]}], "title": "Cook the beef"}, {"steps": [{"n": 3, "temp": null, "text": "Spoon the beef into romaine leaves and top with sliced avocado and salsa.", "type": "assemble", "active": true, "appliance": null, "duration_min": 5, "ingredient_refs": ["romaine lettuce", "avocado, raw", "salsa, ready-to-serve"]}], "title": "Fill the wraps"}], "make_ahead": "Cook the beef up to 3 days ahead.", "cook_time_min": 8, "prep_time_min": 5, "total_time_min": 13, "yield_servings": 1}'::jsonb where id='13f32de3-da29-4481-be7c-21858195ebcd' and user_id is null;

-- Pescatarian Salmon Caesar Wrap
update recipes set recipe_kind='cooked', instructions='{"reheat": "Serve cold or gently warm the salmon.", "storage": "Store components separate; roll fresh so the tortilla stays firm.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Season the salmon and pan-sear in a little olive oil, about 4 minutes per side, until it flakes; flake into pieces.", "type": "cook", "active": false, "appliance": "stovetop", "duration_min": 10, "ingredient_refs": ["salmon, atlantic, farmed, raw", "olive oil"]}], "title": "Cook the salmon"}, {"steps": [{"n": 2, "temp": null, "text": "Whisk the lemon juice, dijon mustard, and a little olive oil into a quick Caesar-style dressing; toss with the chopped romaine and parmesan.", "type": "prep", "active": true, "appliance": null, "duration_min": 3, "ingredient_refs": ["lemon juice, raw", "dijon mustard", "olive oil", "romaine lettuce", "parmesan cheese"]}, {"n": 3, "temp": null, "text": "Pile the romaine and salmon onto the flour tortilla and roll up tightly.", "type": "assemble", "active": true, "appliance": null, "duration_min": 2, "ingredient_refs": ["flour tortilla, large", "salmon, atlantic, farmed, raw"]}], "title": "Build the wrap"}], "make_ahead": "Cook the salmon up to 2 days ahead.", "cook_time_min": 10, "prep_time_min": 5, "total_time_min": 15, "yield_servings": 1}'::jsonb where id='6f6c804a-5964-4339-8180-fbe28af551e1' and user_id is null;

-- Vegan Chickpea Spinach Wrap
update recipes set recipe_kind='assembly', instructions='{"reheat": "Serve cold.", "storage": "Store the mash separate; roll fresh.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Drain the chickpeas and lightly mash with the lemon juice, cumin, and a pinch of salt.", "type": "prep", "active": true, "appliance": null, "duration_min": 4, "ingredient_refs": ["chickpeas, mature seeds, canned, drained", "lemon juice, raw", "cumin, ground", "sea salt"]}, {"n": 2, "temp": null, "text": "Spread the chickpea mash on the tortilla, layer with spinach and sliced avocado, and roll up tightly.", "type": "assemble", "active": true, "appliance": null, "duration_min": 3, "ingredient_refs": ["flour tortilla, large", "spinach, raw", "avocado, raw"]}], "title": "Build the wrap"}], "make_ahead": "Make the chickpea mash up to 2 days ahead.", "cook_time_min": 0, "prep_time_min": 7, "total_time_min": 7, "yield_servings": 1}'::jsonb where id='f78a904e-2df2-45bf-9c39-b9518ce986b6' and user_id is null;

-- Vegan Tempeh Avocado Wrap
update recipes set recipe_kind='cooked', instructions='{"reheat": "Serve cold or warm the tempeh.", "storage": "Store the tempeh separate; roll fresh.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Slice the tempeh and pan-fry in the sesame oil over medium, 3-4 minutes per side, brushing with soy sauce until golden.", "type": "cook", "active": false, "appliance": "stovetop", "duration_min": 8, "ingredient_refs": ["tempeh", "sesame oil", "soy sauce"]}], "title": "Cook the tempeh"}, {"steps": [{"n": 2, "temp": null, "text": "Layer the spinach and sliced avocado on the tortilla, add the tempeh, and roll up tightly.", "type": "assemble", "active": true, "appliance": null, "duration_min": 3, "ingredient_refs": ["spinach, raw", "avocado, raw", "flour tortilla, large", "tempeh"]}], "title": "Build the wrap"}], "make_ahead": "Cook the tempeh up to 3 days ahead.", "cook_time_min": 8, "prep_time_min": 4, "total_time_min": 12, "yield_servings": 1}'::jsonb where id='d60c504e-d551-427c-9939-82e96783bf89' and user_id is null;

-- Vegan Tofu Veggie Breakfast Wrap
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat the scramble before filling.", "storage": "Store the scramble up to 3 days refrigerated; fill fresh.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Crumble the tofu and saute with the sliced bell peppers in olive oil over medium-high, 6-7 minutes; season with cumin.", "type": "cook", "active": false, "appliance": "stovetop", "duration_min": 7, "ingredient_refs": ["tofu, firm, raw", "bell peppers, raw", "olive oil", "cumin, ground"]}, {"n": 2, "temp": null, "text": "Add the spinach and cook until just wilted.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 1, "ingredient_refs": ["spinach, raw"]}], "title": "Cook the tofu"}, {"steps": [{"n": 3, "temp": null, "text": "Spoon the tofu scramble onto the corn tortilla, add salsa, and fold.", "type": "assemble", "active": true, "appliance": null, "duration_min": 2, "ingredient_refs": ["corn tortilla", "salsa, ready-to-serve"]}], "title": "Build the wrap"}], "make_ahead": "Cook the tofu scramble up to 3 days ahead.", "cook_time_min": 8, "prep_time_min": 4, "total_time_min": 12, "yield_servings": 1}'::jsonb where id='4148fb69-ae43-4707-997b-3c36cd007faa' and user_id is null;

commit;
