-- ============================================================================
-- seed-cooking-guides-mains-5.sql — authored cooking guides, MAINS archetype (batch 5, 15 recipes)
-- ----------------------------------------------------------------------------
-- Git source of truth for content authored directly in the DB (instructions jsonb + recipe_kind
-- per recipe id). Content UPDATEs only — NOT schema. Idempotent (matches by id); re-runnable.
-- Same pattern + schema as the other seed-cooking-guides-*.sql files.
--
-- Regenerate from the live DB (swap the id-prefix filter for the batch):
--   select string_agg(format('-- %s', name) || E'\n' ||
--     format('update recipes set recipe_kind=%L, instructions=%L::jsonb where id=%L and user_id is null;',
--       recipe_kind, instructions::text, id::text), E'\n\n' order by name)
--   from recipes where user_id is null and instructions is not null and id::text like any(array['1435d0fe%', ...]);
--
-- Progress: 266 / 299 cooking guides authored (89%) — salads 26 + smoothies 6 + wraps 5 + soups 15 + bowls 77 + originals 5 + breakfast 57 + mains 75 (batches 1-5).
-- ============================================================================

begin;

-- Mahi-Mahi with Pineapple Salsa
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat the fish gently; add salsa fresh.", "storage": "Keeps up to 1 day refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Dice the pineapple and bell peppers and toss with lemon juice for a fresh salsa.", "type": "prep", "active": true, "appliance": null, "duration_min": 6, "ingredient_refs": ["pineapple, raw", "bell peppers, raw", "lemon juice, raw"]}], "title": "Make the salsa"}, {"steps": [{"n": 2, "temp": null, "text": "Season the mahi-mahi and pan-sear in olive oil about 4 minutes per side until it flakes; top with the pineapple salsa.", "type": "cook", "active": false, "appliance": "stovetop", "duration_min": 10, "ingredient_refs": ["mahi-mahi, raw", "olive oil"]}], "title": "Cook the fish"}], "make_ahead": "Make the salsa a few hours ahead; cook the fish fresh.", "cook_time_min": 10, "prep_time_min": 8, "total_time_min": 18, "yield_servings": 1}'::jsonb where id='1435d0fe-a7db-4b05-99f0-f0868a26e31a' and user_id is null;

-- Mediterranean Baked Cod with Tomatoes
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat gently so the fish does not dry out.", "storage": "Keeps up to 1 day refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Heat the oven to 200°C. Mince the garlic and dice the tomatoes; toss with olive oil, lemon juice, and italian seasoning.", "type": "prep", "active": true, "appliance": null, "duration_min": 6, "ingredient_refs": ["garlic, raw", "tomatoes, raw", "olive oil", "lemon juice, raw", "italian seasoning"]}, {"n": 2, "temp": {"unit": "C", "value": 200}, "text": "Set the cod in a baking dish, spoon the tomatoes over, and bake until the fish flakes, about 18 minutes.", "type": "cook", "active": false, "appliance": "oven", "duration_min": 18, "ingredient_refs": ["cod, atlantic, raw"]}], "title": "Bake"}], "make_ahead": "Best baked fresh.", "cook_time_min": 18, "prep_time_min": 6, "total_time_min": 24, "yield_servings": 1}'::jsonb where id='3758d05b-659b-49e5-9b63-a5c8a66ff7f3' and user_id is null;

-- Mediterranean Baked Salmon Capers
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat gently so the fish does not dry out.", "storage": "Keeps up to 2 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Heat the oven to 200°C. Mince the garlic and halve the cherry tomatoes; toss with olive oil, lemon juice, sea salt, and italian seasoning.", "type": "prep", "active": true, "appliance": null, "duration_min": 6, "ingredient_refs": ["garlic, raw", "tomatoes, cherry", "olive oil", "lemon juice, raw", "sea salt", "italian seasoning"]}, {"n": 2, "temp": {"unit": "C", "value": 200}, "text": "Set the salmon in a baking dish, scatter the tomatoes around, and bake until the salmon flakes, about 16 minutes.", "type": "cook", "active": false, "appliance": "oven", "duration_min": 16, "ingredient_refs": ["salmon, atlantic, farmed, raw"]}], "title": "Bake"}], "make_ahead": "Best baked fresh.", "cook_time_min": 16, "prep_time_min": 6, "total_time_min": 22, "yield_servings": 1}'::jsonb where id='47a8d58a-5cca-4aaf-8b1e-7a7ef9179387' and user_id is null;

-- Mediterranean Chicken Vegetable Bake
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat in the oven or microwave.", "storage": "Keeps up to 3 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Heat the oven to 200°C. Mince the garlic. Cube the zucchini and bell peppers and halve the cherry tomatoes; toss with olive oil, garlic, and italian seasoning.", "type": "prep", "active": true, "appliance": null, "duration_min": 8, "ingredient_refs": ["garlic, raw", "zucchini, raw", "bell peppers, raw", "tomatoes, cherry", "olive oil", "italian seasoning"]}, {"n": 2, "temp": {"unit": "C", "value": 200}, "text": "Add the diced chicken to the tray and bake, tossing once, until the chicken is cooked and the vegetables are tender, about 25 minutes.", "type": "cook", "active": false, "appliance": "oven", "duration_min": 25, "ingredient_refs": ["chicken breast, broilers or fryers, raw"]}], "title": "Bake"}], "make_ahead": "Great for meal prep; make up to 3 days ahead.", "cook_time_min": 27, "prep_time_min": 8, "total_time_min": 35, "yield_servings": 1}'::jsonb where id='57e1dc3a-534c-49f6-a4d6-095bf1bf20a0' and user_id is null;

-- Mediterranean Cod Tomato Caper Sauce
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat gently so the fish does not overcook.", "storage": "Keeps up to 2 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Mince the garlic and saute in olive oil until fragrant; add the diced tomatoes, lemon juice, italian seasoning, and sea salt and simmer 8 minutes.", "type": "cook", "active": false, "appliance": "stovetop", "duration_min": 10, "ingredient_refs": ["garlic, raw", "olive oil", "tomato products, canned, diced", "lemon juice, raw", "italian seasoning", "sea salt"]}], "title": "Make the sauce"}, {"steps": [{"n": 2, "temp": null, "text": "Nestle the cod into the sauce, cover, and simmer gently until it flakes, about 10 minutes.", "type": "cook", "active": false, "appliance": "stovetop", "duration_min": 10, "ingredient_refs": ["cod, atlantic, raw"]}], "title": "Cook the cod"}], "make_ahead": "Make the sauce up to 3 days ahead; cook the fish fresh.", "cook_time_min": 20, "prep_time_min": 5, "total_time_min": 25, "yield_servings": 1}'::jsonb where id='0d144cbb-549e-4d85-824d-b53fbf88b53e' and user_id is null;

-- Mediterranean Lamb Vegetable Tagine
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat gently on the stovetop.", "storage": "Keeps up to 4 days refrigerated or 3 months frozen.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Dice the onion. Season the lamb and sear in olive oil with the onion until browned, about 6 minutes; stir in the cumin.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 6, "ingredient_refs": ["onions, raw", "lamb, rib chop, lean, raw", "olive oil", "cumin, ground"]}], "title": "Brown"}, {"steps": [{"n": 2, "temp": null, "text": "Add the carrots, zucchini, and diced tomatoes; cover and simmer gently until the lamb is tender and the sauce is rich, about 44 minutes.", "type": "cook", "active": false, "appliance": "stovetop", "duration_min": 44, "ingredient_refs": ["carrots, raw", "zucchini, raw", "tomato products, canned, diced"]}], "title": "Simmer"}], "make_ahead": "Tastes even better the next day; make up to 4 days ahead.", "cook_time_min": 50, "prep_time_min": 10, "total_time_min": 60, "yield_servings": 1}'::jsonb where id='df8045c4-b437-42d7-8087-fe0a2b4d9f51' and user_id is null;

-- Mediterranean Lemon Herb Chicken
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat gently or serve cold sliced.", "storage": "Keeps up to 3 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Mince the garlic and mix with lemon juice, olive oil, italian seasoning, and sea salt; coat the chicken and let it sit a few minutes.", "type": "prep", "active": true, "appliance": null, "duration_min": 5, "ingredient_refs": ["garlic, raw", "lemon juice, raw", "olive oil", "italian seasoning", "sea salt", "chicken breast, broilers or fryers, raw"]}, {"n": 2, "temp": {"unit": "C", "value": 74}, "text": "Pan-sear the chicken until golden and cooked through, about 6 minutes per side (74°C internal); rest and slice.", "type": "cook", "active": false, "appliance": "stovetop", "duration_min": 13, "ingredient_refs": []}], "title": "Cook"}], "make_ahead": "Marinate up to 1 day ahead; great for meal prep.", "cook_time_min": 13, "prep_time_min": 5, "total_time_min": 18, "yield_servings": 1}'::jsonb where id='25c3ddd7-101e-4beb-8889-ab278d059b58' and user_id is null;

-- Mediterranean Shrimp Quinoa Skillet
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat in a pan or microwave.", "storage": "Keeps up to 2 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Mince the garlic and saute the shrimp in olive oil with the garlic until pink, about 3 minutes; add the halved cherry tomatoes and spinach to wilt.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 6, "ingredient_refs": ["garlic, raw", "shrimp, raw", "olive oil", "tomatoes, cherry", "spinach, raw"]}, {"n": 2, "temp": null, "text": "Stir in the cooked quinoa to warm through and finish with lemon juice.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 4, "ingredient_refs": ["quinoa, cooked", "lemon juice, raw"]}], "title": "Cook"}], "make_ahead": "Cook the quinoa ahead; the skillet comes together fast.", "cook_time_min": 10, "prep_time_min": 5, "total_time_min": 15, "yield_servings": 1}'::jsonb where id='bfd3d7ec-5ad3-430b-b10a-b35d30b93975' and user_id is null;

-- Paleo Almond-Crusted Chicken Breast
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat in the oven to keep the crust crisp.", "storage": "Keeps up to 3 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Finely chop the almonds and mince the garlic; mix with rosemary and press onto the chicken to form a crust.", "type": "prep", "active": true, "appliance": null, "duration_min": 6, "ingredient_refs": ["almonds, raw", "garlic, raw", "rosemary, fresh", "chicken breast, broilers or fryers, raw"]}, {"n": 2, "temp": {"unit": "C", "value": 74}, "text": "Pan-fry in olive oil about 6-7 minutes per side until the crust is golden and the chicken is cooked through (74°C internal).", "type": "cook", "active": false, "appliance": "stovetop", "duration_min": 14, "ingredient_refs": ["olive oil"]}], "title": "Cook"}], "make_ahead": "Best cooked fresh; crust the chicken ahead.", "cook_time_min": 14, "prep_time_min": 6, "total_time_min": 20, "yield_servings": 1}'::jsonb where id='266ca929-38e2-406b-a9ce-15ec273ee24c' and user_id is null;

-- Paleo Banana Walnut Snack
update recipes set recipe_kind='assembly', instructions='{"reheat": "Serve fresh.", "storage": "Eat immediately; banana browns over time.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Slice the banana onto a plate.", "type": "prep", "active": true, "appliance": null, "duration_min": 1, "ingredient_refs": ["banana, raw"]}, {"n": 2, "temp": null, "text": "Drizzle with almond butter, scatter with walnuts, and dust with cinnamon.", "type": "assemble", "active": true, "appliance": null, "duration_min": 3, "ingredient_refs": ["almond butter", "walnuts, raw", "cinnamon, ground"]}], "title": "Assemble"}], "make_ahead": "Best fresh.", "cook_time_min": 0, "prep_time_min": 4, "total_time_min": 4, "yield_servings": 1}'::jsonb where id='a8097cdc-cd32-4ba8-8ed6-b6a67d345b66' and user_id is null;

-- Paleo Chicken Breast Roasted Beets
update recipes set recipe_kind='cooked', instructions='{"reheat": "Serve cold or gently warmed.", "storage": "Keeps up to 3 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": {"unit": "C", "value": 200}, "text": "Heat the oven to 200°C. Peel and cube the beets, toss with olive oil and sea salt, and roast until tender, about 25 minutes.", "type": "cook", "active": false, "appliance": "oven", "duration_min": 25, "ingredient_refs": ["beets, raw", "olive oil", "sea salt"]}], "title": "Roast the beets"}, {"steps": [{"n": 2, "temp": null, "text": "Pan-sear the seasoned chicken until cooked through, about 6 minutes per side; slice and serve over the mixed greens with the beets, dressed with balsamic vinegar.", "type": "cook", "active": false, "appliance": "stovetop", "duration_min": 2, "ingredient_refs": ["chicken breast, broilers or fryers, raw", "mixed greens", "balsamic vinegar"]}], "title": "Cook the chicken and plate"}], "make_ahead": "Roast the beets and cook the chicken ahead; assemble fresh.", "cook_time_min": 27, "prep_time_min": 6, "total_time_min": 33, "yield_servings": 1}'::jsonb where id='ca1729ad-b135-40df-b35a-e4c2fbbbd974' and user_id is null;

-- Paleo Ground Beef Sweet Potato Shepherd Pie
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat in the oven or microwave.", "storage": "Keeps up to 3 days refrigerated or 3 months frozen.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Cube the sweet potato and boil until soft, about 12 minutes; mash and set aside.", "type": "cook", "active": false, "appliance": "stovetop", "duration_min": 12, "ingredient_refs": ["sweet potato, raw"]}], "title": "Make the mash"}, {"steps": [{"n": 2, "temp": null, "text": "Dice the onion and carrots and saute in olive oil until soft, about 5 minutes; add the ground beef and brown, then season with paprika and sea salt.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 11, "ingredient_refs": ["onions, raw", "carrots, raw", "olive oil", "ground beef, 90% lean, raw", "paprika", "sea salt"]}, {"n": 3, "temp": {"unit": "C", "value": 200}, "text": "Heat the oven to 200°C. Spoon the beef into a dish, spread the sweet potato mash over, and bake until golden, about 15 minutes.", "type": "cook", "active": false, "appliance": "oven", "duration_min": 15, "ingredient_refs": []}], "title": "Make the filling and bake"}], "make_ahead": "Assemble up to 1 day ahead and bake fresh; freezes well.", "cook_time_min": 38, "prep_time_min": 10, "total_time_min": 48, "yield_servings": 1}'::jsonb where id='dd946ed3-521b-4b5b-aeaa-4ab8103d20df' and user_id is null;

-- Paleo Ground Turkey Vegetable Skillet
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat in a pan or microwave.", "storage": "Keeps up to 3 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Dice the onion, bell peppers, and zucchini; saute in olive oil until softened, about 5 minutes.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 5, "ingredient_refs": ["onions, raw", "bell peppers, raw", "zucchini, raw", "olive oil"]}, {"n": 2, "temp": null, "text": "Add the ground turkey and brown, breaking it up, about 9 minutes; season with cumin and sea salt.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 9, "ingredient_refs": ["ground turkey, raw", "cumin, ground", "sea salt"]}], "title": "Cook"}], "make_ahead": "Great for meal prep; make up to 3 days ahead.", "cook_time_min": 14, "prep_time_min": 6, "total_time_min": 20, "yield_servings": 1}'::jsonb where id='16f44300-a36f-4623-9b8e-c6ef1e0bac0d' and user_id is null;

-- Paleo Lamb Roasted Vegetable Plate
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat the vegetables; gently warm the lamb.", "storage": "Keeps up to 3 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": {"unit": "C", "value": 220}, "text": "Heat the oven to 220°C. Cube the zucchini and bell peppers, toss with olive oil, rosemary, and sea salt, and roast until tender and charred at the edges, about 22 minutes.", "type": "cook", "active": false, "appliance": "oven", "duration_min": 22, "ingredient_refs": ["zucchini, raw", "bell peppers, raw", "olive oil", "rosemary, fresh", "sea salt"]}], "title": "Roast the vegetables"}, {"steps": [{"n": 2, "temp": null, "text": "Season the lamb and sear 3-4 minutes per side for medium; rest and serve with the roasted vegetables.", "type": "cook", "active": false, "appliance": "stovetop", "duration_min": 5, "ingredient_refs": ["lamb, rib chop, lean, raw"]}], "title": "Cook the lamb"}], "make_ahead": "Roast the vegetables ahead; cook the lamb fresh.", "cook_time_min": 27, "prep_time_min": 6, "total_time_min": 33, "yield_servings": 1}'::jsonb where id='fa90113c-3720-4950-b287-275e66c96db8' and user_id is null;

-- Paleo Mango Coconut Bites
update recipes set recipe_kind='assembly', instructions='{"reheat": "Serve cold.", "storage": "Keeps up to 3 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Dice the mango and stir the chia seeds into the coconut milk.", "type": "prep", "active": true, "appliance": null, "duration_min": 3, "ingredient_refs": ["mango, raw", "chia seeds", "coconut milk"]}, {"n": 2, "temp": null, "text": "Fold in the mango, scatter with hemp seeds, and dust with cinnamon; let it sit a few minutes to thicken.", "type": "assemble", "active": true, "appliance": null, "duration_min": 2, "ingredient_refs": ["hemp seeds, hulled", "cinnamon, ground"]}], "title": "Assemble"}], "make_ahead": "Make ahead; the chia thickens as it sits.", "cook_time_min": 0, "prep_time_min": 5, "total_time_min": 5, "yield_servings": 1}'::jsonb where id='b72bd2f5-dd3d-4151-9eea-b66a287fd401' and user_id is null;

commit;
