-- ============================================================================
-- seed-cooking-guides-bowls-4.sql — authored cooking guides, BOWLS archetype (batch 4 of N, 15 recipes)
-- ----------------------------------------------------------------------------
-- Git source of truth for content authored directly in the DB (instructions jsonb + recipe_kind
-- per recipe id). Content UPDATEs only — NOT schema. Idempotent (matches by id); re-runnable.
-- Same pattern + schema as the other seed-cooking-guides-*.sql files.
--
-- Bowls are captured across numbered batches (bowls-1..N). This is batch 4; ~17 remain (bowls-5 finishes).
--
-- Regenerate from the live DB (swap the id-prefix filter for the batch):
--   select string_agg(format('-- %s', name) || E'\n' ||
--     format('update recipes set recipe_kind=%L, instructions=%L::jsonb where id=%L and user_id is null;',
--       recipe_kind, instructions::text, id::text), E'\n\n' order by name)
--   from recipes where user_id is null and id::text like any(array['f8382fd4%', ...]);
--
-- Progress: 117 / 299 cooking guides authored (39%) — salads 26 + smoothies 6 + wraps 5 + soups 15 + bowls 60 (batches 1-4).
-- ============================================================================

begin;

-- Pescatarian Salmon Oat Bowl
update recipes set recipe_kind='cooked', instructions='{"reheat": "Serve the salmon warm or cold.", "storage": "Keeps up to 2 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Season the salmon with sea salt and pan-sear in a little olive oil, about 4 minutes per side, until it flakes.", "type": "cook", "active": false, "appliance": "stovetop", "duration_min": 10, "ingredient_refs": ["salmon, atlantic, farmed, raw", "sea salt", "olive oil"]}], "title": "Cook the salmon"}, {"steps": [{"n": 2, "temp": null, "text": "Prepare the oats as a savory base with a little water, add to a bowl with sliced avocado, and top with the salmon and lemon juice.", "type": "assemble", "active": true, "appliance": null, "duration_min": 5, "ingredient_refs": ["rolled oats", "avocado, raw", "lemon juice, raw"]}], "title": "Assemble"}], "make_ahead": "Cook the salmon ahead; prepare the oats fresh.", "cook_time_min": 10, "prep_time_min": 5, "total_time_min": 15, "yield_servings": 1}'::jsonb where id='f8382fd4-7301-4686-be66-2056425b7007' and user_id is null;

-- Pescatarian Shrimp Black Bean Rice Bowl
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat gently.", "storage": "Keeps up to 2 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Saute the shrimp in a little olive oil over medium-high, 2-3 minutes per side, until pink; season with cumin.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 6, "ingredient_refs": ["shrimp, raw", "olive oil", "cumin, ground"]}], "title": "Cook the shrimp"}, {"steps": [{"n": 2, "temp": null, "text": "Add the brown rice to a bowl with the black beans and sliced avocado, top with the shrimp and salsa.", "type": "assemble", "active": true, "appliance": null, "duration_min": 4, "ingredient_refs": ["brown rice, cooked", "black beans, canned, drained", "avocado, raw", "salsa, ready-to-serve"]}], "title": "Assemble"}], "make_ahead": "Cook the rice ahead; cook the shrimp fresh.", "cook_time_min": 8, "prep_time_min": 5, "total_time_min": 13, "yield_servings": 1}'::jsonb where id='3e751168-4715-4e61-a8e0-a14d9344e679' and user_id is null;

-- Pescatarian Shrimp Edamame Bowl
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat gently.", "storage": "Keeps up to 2 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Grate a little ginger and saute the shrimp in sesame oil with the ginger, 2-3 minutes per side, until pink; splash with soy sauce.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 6, "ingredient_refs": ["ginger root, raw", "shrimp, raw", "sesame oil", "soy sauce"]}], "title": "Cook the shrimp"}, {"steps": [{"n": 2, "temp": null, "text": "Add the brown rice and edamame to a bowl and top with the shrimp.", "type": "assemble", "active": true, "appliance": null, "duration_min": 2, "ingredient_refs": ["brown rice, cooked", "edamame, frozen, prepared"]}], "title": "Assemble"}], "make_ahead": "Cook the rice and edamame ahead; cook the shrimp fresh.", "cook_time_min": 8, "prep_time_min": 5, "total_time_min": 13, "yield_servings": 1}'::jsonb where id='8dc93fdf-683b-423e-8b3e-bbd96eba4e6e' and user_id is null;

-- Pescatarian Shrimp Quinoa Mediterranean Bowl
update recipes set recipe_kind='cooked', instructions='{"reheat": "Serve cold or gently warmed.", "storage": "Keeps up to 2 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Saute the shrimp in a little olive oil over medium-high, 2-3 minutes per side, until pink.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 6, "ingredient_refs": ["shrimp, raw", "olive oil"]}], "title": "Cook the shrimp"}, {"steps": [{"n": 2, "temp": null, "text": "Add the quinoa to a bowl with the halved cherry tomatoes, diced cucumber, and crumbled feta.", "type": "prep", "active": true, "appliance": null, "duration_min": 3, "ingredient_refs": ["quinoa, cooked", "tomatoes, cherry", "cucumber, raw", "feta cheese"]}, {"n": 3, "temp": null, "text": "Top with the shrimp and dress with the remaining olive oil and lemon juice.", "type": "assemble", "active": true, "appliance": null, "duration_min": 1, "ingredient_refs": ["olive oil", "lemon juice, raw"]}], "title": "Assemble"}], "make_ahead": "Cook the quinoa ahead; cook the shrimp fresh.", "cook_time_min": 8, "prep_time_min": 5, "total_time_min": 13, "yield_servings": 1}'::jsonb where id='77747655-b99f-49b3-8892-827858dbb81c' and user_id is null;

-- Pescatarian Smoked Salmon Grain Bowl
update recipes set recipe_kind='assembly', instructions='{"reheat": "Serve cold.", "storage": "Keeps up to 2 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Add the quinoa to a bowl with the arugula and sliced cucumber.", "type": "prep", "active": true, "appliance": null, "duration_min": 3, "ingredient_refs": ["quinoa, cooked", "arugula, raw", "cucumber, raw"]}, {"n": 2, "temp": null, "text": "Drape over the smoked salmon and dress with olive oil and lemon juice.", "type": "assemble", "active": true, "appliance": null, "duration_min": 3, "ingredient_refs": ["smoked salmon", "olive oil", "lemon juice, raw"]}], "title": "Assemble"}], "make_ahead": "Cook the quinoa ahead; assemble fresh.", "cook_time_min": 0, "prep_time_min": 6, "total_time_min": 6, "yield_servings": 1}'::jsonb where id='bbe1e162-d381-4182-9bd9-22ad69e70902' and user_id is null;

-- Pescatarian Tilapia Brown Rice Power Bowl
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat gently.", "storage": "Keeps up to 2 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Cut the broccoli into florets and steam until tender-crisp, about 5 minutes.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 5, "ingredient_refs": ["broccoli, raw"]}, {"n": 2, "temp": null, "text": "Season the tilapia with sea salt and pan-sear in sesame oil, about 3 minutes per side, until it flakes; splash with soy sauce.", "type": "cook", "active": false, "appliance": "stovetop", "duration_min": 7, "ingredient_refs": ["tilapia, raw", "sea salt", "sesame oil", "soy sauce"]}], "title": "Cook"}, {"steps": [{"n": 3, "temp": null, "text": "Add the brown rice to a bowl with the broccoli and tilapia.", "type": "assemble", "active": true, "appliance": null, "duration_min": 2, "ingredient_refs": ["brown rice, cooked"]}], "title": "Assemble"}], "make_ahead": "Cook the rice ahead; cook the fish fresh.", "cook_time_min": 12, "prep_time_min": 5, "total_time_min": 17, "yield_servings": 1}'::jsonb where id='bc29ed52-df6c-42f9-afd5-1276054102cc' and user_id is null;

-- Pescatarian Tilapia Taco Bowl
update recipes set recipe_kind='cooked', instructions='{"reheat": "Serve the fish warm or cold.", "storage": "Keeps up to 1 day refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Season the tilapia with cumin and pan-sear in a little olive oil, about 3 minutes per side, until it flakes; break into chunks.", "type": "cook", "active": false, "appliance": "stovetop", "duration_min": 6, "ingredient_refs": ["tilapia, raw", "cumin, ground", "olive oil"]}], "title": "Cook the tilapia"}, {"steps": [{"n": 2, "temp": null, "text": "Add the brown rice to a bowl with the black beans and sliced avocado, top with the tilapia and salsa.", "type": "assemble", "active": true, "appliance": null, "duration_min": 4, "ingredient_refs": ["brown rice, cooked", "black beans, canned, drained", "avocado, raw", "salsa, ready-to-serve"]}], "title": "Assemble"}], "make_ahead": "Cook the rice ahead; cook the fish fresh.", "cook_time_min": 8, "prep_time_min": 5, "total_time_min": 13, "yield_servings": 1}'::jsonb where id='b46c5fe3-48b0-4d79-b816-5e6275a710f2' and user_id is null;

-- Pescatarian Tuna Avocado Breakfast Bowl
update recipes set recipe_kind='cooked', instructions='{"reheat": "Serve cold with a fresh egg.", "storage": "Keeps up to 1 day refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Fry or soft-boil the egg to your liking.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 5, "ingredient_refs": ["egg, whole, raw"]}], "title": "Cook the egg"}, {"steps": [{"n": 2, "temp": null, "text": "Add the mixed greens to a bowl, drain and flake in the tuna, and add the sliced avocado.", "type": "prep", "active": true, "appliance": null, "duration_min": 3, "ingredient_refs": ["mixed greens", "tuna, canned in water, drained", "avocado, raw"]}, {"n": 3, "temp": null, "text": "Top with the egg, dress with olive oil and lemon juice, and season with sea salt.", "type": "assemble", "active": true, "appliance": null, "duration_min": 2, "ingredient_refs": ["olive oil", "lemon juice, raw", "sea salt"]}], "title": "Assemble"}], "make_ahead": "Best fresh; the egg can be pre-boiled.", "cook_time_min": 5, "prep_time_min": 5, "total_time_min": 10, "yield_servings": 1}'::jsonb where id='cd8a3b01-a062-4dea-81eb-6a6e65f8d46d' and user_id is null;

-- Pescatarian Tuna Brown Rice Bowl
update recipes set recipe_kind='assembly', instructions='{"reheat": "Serve cold or at room temperature.", "storage": "Keeps up to 1 day refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Add the brown rice to a bowl and drain and flake in the tuna.", "type": "prep", "active": true, "appliance": null, "duration_min": 2, "ingredient_refs": ["brown rice, cooked", "tuna, canned in water, drained"]}, {"n": 2, "temp": null, "text": "Dice the avocado and cucumber and add to the bowl.", "type": "prep", "active": true, "appliance": null, "duration_min": 3, "ingredient_refs": ["avocado, raw", "cucumber, raw"]}, {"n": 3, "temp": null, "text": "Whisk the soy sauce, sesame oil, and lemon juice and drizzle over.", "type": "assemble", "active": true, "appliance": null, "duration_min": 2, "ingredient_refs": ["soy sauce", "sesame oil", "lemon juice, raw"]}], "title": "Assemble"}], "make_ahead": "Cook the rice ahead; assemble fresh.", "cook_time_min": 0, "prep_time_min": 7, "total_time_min": 7, "yield_servings": 1}'::jsonb where id='1aef5258-bd1f-449b-a8ab-f03337a0bd7e' and user_id is null;

-- Pescatarian Tuna Zucchini Noodle Bowl
update recipes set recipe_kind='assembly', instructions='{"reheat": "Serve cold.", "storage": "Keeps up to 1 day refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Mince the garlic. Spiralize or julienne the zucchini into noodles and toss with the garlic, olive oil, lemon juice, and sea salt.", "type": "prep", "active": true, "appliance": null, "duration_min": 5, "ingredient_refs": ["garlic, raw", "zucchini, raw", "olive oil", "lemon juice, raw", "sea salt"]}, {"n": 2, "temp": null, "text": "Drain and flake in the tuna and top with sliced avocado.", "type": "assemble", "active": true, "appliance": null, "duration_min": 3, "ingredient_refs": ["tuna, canned in water, drained", "avocado, raw"]}], "title": "Assemble"}], "make_ahead": "Best fresh so the zucchini stays firm.", "cook_time_min": 0, "prep_time_min": 8, "total_time_min": 8, "yield_servings": 1}'::jsonb where id='a125a6e2-607d-4871-b653-e9558d033224' and user_id is null;

-- Salmon and Quinoa Buddha Bowl
update recipes set recipe_kind='cooked', instructions='{"reheat": "Serve cold or gently warm the salmon.", "storage": "Keeps up to 2 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Pan-sear the seasoned salmon in a little olive oil, about 4 minutes per side, until it flakes.", "type": "cook", "active": false, "appliance": "stovetop", "duration_min": 10, "ingredient_refs": ["salmon, atlantic, farmed, raw", "olive oil"]}], "title": "Cook the salmon"}, {"steps": [{"n": 2, "temp": null, "text": "Add the quinoa to a bowl with the spinach and sliced avocado, top with the salmon, and dress with lemon juice.", "type": "assemble", "active": true, "appliance": null, "duration_min": 5, "ingredient_refs": ["quinoa, cooked", "spinach, raw", "avocado, raw", "lemon juice, raw"]}], "title": "Assemble"}], "make_ahead": "Cook the quinoa and salmon ahead.", "cook_time_min": 10, "prep_time_min": 5, "total_time_min": 15, "yield_servings": 1}'::jsonb where id='e2ae2343-ac73-4bd8-b09a-cc358d58c8aa' and user_id is null;

-- Shrimp and Avocado Grain Bowl
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat gently.", "storage": "Keeps up to 2 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Saute the shrimp in a little olive oil over medium-high, 2-3 minutes per side, until pink.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 6, "ingredient_refs": ["shrimp, raw", "olive oil"]}], "title": "Cook the shrimp"}, {"steps": [{"n": 2, "temp": null, "text": "Add the brown rice to a bowl with the mixed greens and sliced avocado, top with the shrimp, and dress with lemon juice.", "type": "assemble", "active": true, "appliance": null, "duration_min": 4, "ingredient_refs": ["brown rice, cooked", "mixed greens", "avocado, raw", "lemon juice, raw"]}], "title": "Assemble"}], "make_ahead": "Cook the rice ahead; cook the shrimp fresh.", "cook_time_min": 8, "prep_time_min": 5, "total_time_min": 13, "yield_servings": 1}'::jsonb where id='19979722-a370-4995-bd47-002f7197f159' and user_id is null;

-- Vegan Berry Chia Overnight Bowl
update recipes set recipe_kind='assembly', instructions='{"reheat": "Serve cold.", "storage": "Keeps up to 3 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Stir the chia seeds into the coconut milk with the vanilla and maple syrup.", "type": "prep", "active": true, "appliance": null, "duration_min": 3, "ingredient_refs": ["chia seeds", "coconut milk", "vanilla extract", "maple syrup"]}, {"n": 2, "temp": null, "text": "Refrigerate overnight (or at least 2 hours), then top with the blueberries and strawberries.", "type": "assemble", "active": true, "appliance": null, "duration_min": 2, "ingredient_refs": ["blueberries, raw", "strawberries, raw"]}], "title": "Assemble"}], "make_ahead": "Made ahead by design; prepare the night before.", "cook_time_min": 0, "prep_time_min": 5, "total_time_min": 5, "yield_servings": 1}'::jsonb where id='594ccf6b-4b54-4b99-b6d6-6d706b95b596' and user_id is null;

-- Vegan Black Bean Breakfast Bowl
update recipes set recipe_kind='assembly', instructions='{"reheat": "Serve cold or warm the beans.", "storage": "Keeps up to 2 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Drain the black beans and warm them through if you like; add to a bowl with the spinach.", "type": "prep", "active": true, "appliance": null, "duration_min": 2, "ingredient_refs": ["black beans, canned, drained", "spinach, raw"]}, {"n": 2, "temp": null, "text": "Dice the avocado and tomatoes and add; season with cumin.", "type": "prep", "active": true, "appliance": null, "duration_min": 3, "ingredient_refs": ["avocado, raw", "tomatoes, raw", "cumin, ground"]}, {"n": 3, "temp": null, "text": "Dress with olive oil and lemon juice and toss.", "type": "assemble", "active": true, "appliance": null, "duration_min": 2, "ingredient_refs": ["olive oil", "lemon juice, raw"]}], "title": "Assemble"}], "make_ahead": "Keeps well; make up to 2 days ahead.", "cook_time_min": 0, "prep_time_min": 7, "total_time_min": 7, "yield_servings": 1}'::jsonb where id='2246f77c-a7b0-4884-8a87-09b4c11b01b2' and user_id is null;

-- Vegan Black Bean Enchilada Bowl
update recipes set recipe_kind='cooked', instructions='{"reheat": "Microwave 2 minutes.", "storage": "Keeps up to 4 days refrigerated or 3 months frozen.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Dice the bell peppers and saute in olive oil until soft, about 5 minutes; stir in the cumin.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 5, "ingredient_refs": ["bell peppers, raw", "olive oil", "cumin, ground"]}, {"n": 2, "temp": null, "text": "Add the black beans and diced tomatoes, season with sea salt, and simmer until saucy, about 10 minutes.", "type": "cook", "active": false, "appliance": "stovetop", "duration_min": 10, "ingredient_refs": ["black beans, canned, drained", "tomato products, canned, diced", "sea salt"]}], "title": "Cook"}, {"steps": [{"n": 3, "temp": null, "text": "Spoon over the brown rice to serve.", "type": "assemble", "active": true, "appliance": null, "duration_min": 1, "ingredient_refs": ["brown rice, cooked"]}], "title": "Assemble"}], "make_ahead": "Great for meal prep; make up to 4 days ahead.", "cook_time_min": 16, "prep_time_min": 6, "total_time_min": 22, "yield_servings": 1}'::jsonb where id='a33031f3-633e-4760-8981-03e48e4b2447' and user_id is null;

commit;
