-- ============================================================================
-- seed-cooking-guides-breakfast-4.sql — authored cooking guides, BREAKFAST archetype (batch 4, FINAL, 12 recipes)
-- ----------------------------------------------------------------------------
-- Git source of truth for content authored directly in the DB (instructions jsonb + recipe_kind
-- per recipe id). Content UPDATEs only — NOT schema. Idempotent (matches by id); re-runnable.
-- Same pattern + schema as the other seed-cooking-guides-*.sql files.
--
-- FINAL breakfast batch — completes the breakfast archetype (57 total across batches 1-4).
--
-- Regenerate from the live DB (swap the id-prefix filter for the batch):
--   select string_agg(format('-- %s', name) || E'\n' ||
--     format('update recipes set recipe_kind=%L, instructions=%L::jsonb where id=%L and user_id is null;',
--       recipe_kind, instructions::text, id::text), E'\n\n' order by name)
--   from recipes where user_id is null and instructions is not null and id::text like any(array['865b64c5%', ...]);
--
-- Progress: 191 / 299 cooking guides authored (64%) — salads 26 + smoothies 6 + wraps 5 + soups 15 + bowls 77 + originals 5 + breakfast 57 (batches 1-4).
-- ============================================================================

begin;

-- Paleo Bacon Butternut Squash Hash
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat the hash; add fresh eggs.", "storage": "Keeps up to 3 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Cube the butternut squash and dice the onion; saute in olive oil with the rosemary until the squash is tender, about 12 minutes.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 12, "ingredient_refs": ["butternut squash, raw", "onions, raw", "olive oil", "rosemary, fresh"]}, {"n": 2, "temp": null, "text": "Add the chopped bacon to crisp, then make wells, crack in the eggs, cover, and cook until set, about 5 minutes. Season with sea salt.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 8, "ingredient_refs": ["bacon, cured, pan-fried", "egg, whole, raw", "sea salt"]}], "title": "Cook the hash"}], "make_ahead": "Make the hash ahead; add eggs fresh.", "cook_time_min": 20, "prep_time_min": 6, "total_time_min": 26, "yield_servings": 1}'::jsonb where id='865b64c5-b88a-4665-b7ea-ce04b3ef61fc' and user_id is null;

-- Smoked Salmon Cucumber Breakfast Plate
update recipes set recipe_kind='assembly', instructions='{"reheat": "Serve cold.", "storage": "Keeps up to 1 day refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Slice the cucumber and spread with cream cheese.", "type": "prep", "active": true, "appliance": null, "duration_min": 3, "ingredient_refs": ["cucumber, raw", "cream cheese"]}, {"n": 2, "temp": null, "text": "Drape over the smoked salmon, finish with lemon juice, and season with sea salt and black pepper.", "type": "assemble", "active": true, "appliance": null, "duration_min": 3, "ingredient_refs": ["smoked salmon", "lemon juice, raw", "sea salt", "black pepper, ground"]}], "title": "Assemble"}], "make_ahead": "Assemble fresh; slice cucumber ahead.", "cook_time_min": 0, "prep_time_min": 6, "total_time_min": 6, "yield_servings": 1}'::jsonb where id='4ffc6e7f-84b7-44e2-b454-b0aacc5a1c99' and user_id is null;

-- Smoked Salmon Spinach Scramble
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat gently; eggs are best fresh.", "storage": "Keeps up to 1 day refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Wilt the spinach in olive oil over medium, about 2 minutes.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 2, "ingredient_refs": ["spinach, raw", "olive oil"]}, {"n": 2, "temp": null, "text": "Whisk the eggs, pour in, and softly scramble; as they set, fold in the cream cheese and flaked smoked salmon.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 5, "ingredient_refs": ["egg, whole, raw", "cream cheese", "smoked salmon"]}], "title": "Cook"}], "make_ahead": "Best cooked fresh.", "cook_time_min": 7, "prep_time_min": 3, "total_time_min": 10, "yield_servings": 1}'::jsonb where id='619b78d9-a3f7-452b-a38c-2f0943814300' and user_id is null;

-- Three-Egg Veggie Omelette
update recipes set recipe_kind='cooked', instructions='{"reheat": "Serve fresh.", "storage": "Keeps up to 1 day refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Dice the bell peppers and slice the mushrooms; saute in olive oil until softened, about 4 minutes, then add the spinach to wilt.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 5, "ingredient_refs": ["bell peppers, raw", "mushrooms, portobello, raw", "olive oil", "spinach, raw"]}, {"n": 2, "temp": null, "text": "Whisk the eggs, pour over the vegetables, and cook without stirring; when nearly set, fold into an omelette.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 4, "ingredient_refs": ["egg, whole, raw"]}], "title": "Cook"}], "make_ahead": "Best cooked fresh.", "cook_time_min": 9, "prep_time_min": 5, "total_time_min": 14, "yield_servings": 1}'::jsonb where id='87f0693f-5d0a-4174-87e7-1afc96227014' and user_id is null;

-- Vegan Almond Banana Protein Pancakes
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat in a pan or toaster.", "storage": "Keeps up to 2 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Mash the banana and mix with the almond flour, ground flaxseed, coconut milk, and cinnamon into a batter; let it sit 2 minutes to thicken.", "type": "prep", "active": true, "appliance": null, "duration_min": 5, "ingredient_refs": ["banana, raw", "almond flour", "flaxseed, ground", "coconut milk", "cinnamon, ground"]}, {"n": 2, "temp": null, "text": "Melt a little coconut oil in a pan and cook small pancakes over medium, about 2-3 minutes per side, until golden.", "type": "cook", "active": false, "appliance": "stovetop", "duration_min": 10, "ingredient_refs": ["coconut oil"]}], "title": "Make the batter and cook"}], "make_ahead": "Cook fresh; batter is best used right away.", "cook_time_min": 10, "prep_time_min": 6, "total_time_min": 16, "yield_servings": 1}'::jsonb where id='aeec5c62-a20e-4193-964d-0c45ed21e5ca' and user_id is null;

-- Vegan Black Bean Hummus Veggies
update recipes set recipe_kind='assembly', instructions='{"reheat": "Serve cold.", "storage": "Keeps up to 2 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Drain the black beans and mash lightly with lemon juice and cumin.", "type": "prep", "active": true, "appliance": null, "duration_min": 3, "ingredient_refs": ["black beans, canned, drained", "lemon juice, raw", "cumin, ground"]}, {"n": 2, "temp": null, "text": "Plate the bean mash with the hummus and cut the carrots and cucumber into sticks for dipping.", "type": "assemble", "active": true, "appliance": null, "duration_min": 3, "ingredient_refs": ["hummus, commercial", "carrots, raw", "cucumber, raw"]}], "title": "Assemble"}], "make_ahead": "Make the bean mash up to 2 days ahead.", "cook_time_min": 0, "prep_time_min": 6, "total_time_min": 6, "yield_servings": 1}'::jsonb where id='44d50dc8-4bea-4ecb-bbf7-db4575fee4f9' and user_id is null;

-- Vegan Chia Berry Pudding
update recipes set recipe_kind='assembly', instructions='{"reheat": "Serve cold.", "storage": "Keeps up to 3 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Whisk the chia seeds into the coconut milk with the maple syrup and vanilla.", "type": "prep", "active": true, "appliance": null, "duration_min": 3, "ingredient_refs": ["chia seeds", "coconut milk", "maple syrup", "vanilla extract"]}, {"n": 2, "temp": null, "text": "Refrigerate overnight (or at least 2 hours), then top with the blueberries.", "type": "assemble", "active": true, "appliance": null, "duration_min": 2, "ingredient_refs": ["blueberries, raw"]}], "title": "Assemble"}], "make_ahead": "Made ahead by design; prepare the night before.", "cook_time_min": 0, "prep_time_min": 5, "total_time_min": 5, "yield_servings": 1}'::jsonb where id='cd31b998-4463-471e-9599-f6e7e0c730d6' and user_id is null;

-- Vegan Chia Pudding
update recipes set recipe_kind='assembly', instructions='{"reheat": "Serve cold.", "storage": "Keeps up to 3 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Whisk the chia seeds into the coconut milk with the maple syrup.", "type": "prep", "active": true, "appliance": null, "duration_min": 3, "ingredient_refs": ["chia seeds", "coconut milk", "maple syrup"]}, {"n": 2, "temp": null, "text": "Refrigerate overnight (or at least 2 hours), then top with the sliced strawberries.", "type": "assemble", "active": true, "appliance": null, "duration_min": 2, "ingredient_refs": ["strawberries, raw"]}], "title": "Assemble"}], "make_ahead": "Made ahead by design; prepare the night before.", "cook_time_min": 0, "prep_time_min": 5, "total_time_min": 5, "yield_servings": 1}'::jsonb where id='08ddcb71-4aba-4dcc-a5cf-297bf275ea4c' and user_id is null;

-- Vegan Coconut Oatmeal with Mango
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat with a splash of coconut milk.", "storage": "Keeps up to 2 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Simmer the rolled oats with the coconut milk until creamy, about 6 minutes.", "type": "cook", "active": false, "appliance": "stovetop", "duration_min": 6, "ingredient_refs": ["rolled oats", "coconut milk"]}, {"n": 2, "temp": null, "text": "Stir in the chia seeds, maple syrup, and cinnamon, then top with the diced mango.", "type": "assemble", "active": true, "appliance": null, "duration_min": 2, "ingredient_refs": ["chia seeds", "maple syrup", "cinnamon, ground", "mango, raw"]}], "title": "Cook"}], "make_ahead": "Cook fresh, or make as overnight oats.", "cook_time_min": 8, "prep_time_min": 3, "total_time_min": 11, "yield_servings": 1}'::jsonb where id='ae3c9b60-3125-4211-b5e4-50d0684d2d0c' and user_id is null;

-- Vegan Overnight Oats with Chia
update recipes set recipe_kind='assembly', instructions='{"reheat": "Serve cold.", "storage": "Keeps up to 3 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Stir the rolled oats and chia seeds into the coconut milk with the maple syrup and almond butter.", "type": "prep", "active": true, "appliance": null, "duration_min": 4, "ingredient_refs": ["rolled oats", "chia seeds", "coconut milk", "maple syrup", "almond butter"]}, {"n": 2, "temp": null, "text": "Refrigerate overnight, then top with the blueberries before eating.", "type": "assemble", "active": true, "appliance": null, "duration_min": 1, "ingredient_refs": ["blueberries, raw"]}], "title": "Assemble"}], "make_ahead": "Made ahead by design; prepare the night before.", "cook_time_min": 0, "prep_time_min": 5, "total_time_min": 5, "yield_servings": 1}'::jsonb where id='f8b54f6f-adb2-4187-8af3-08bfcf4afc0f' and user_id is null;

-- Vegan Tempeh Breakfast Skillet
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat in a pan or microwave.", "storage": "Keeps up to 3 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Dice the onion and bell peppers and cube the tempeh; saute in olive oil until the tempeh is golden and the vegetables soften, about 9 minutes. Stir in the cumin and soy sauce.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 10, "ingredient_refs": ["onions, raw", "bell peppers, raw", "tempeh", "olive oil", "cumin, ground", "soy sauce"]}, {"n": 2, "temp": null, "text": "Add the spinach and cook until wilted, about 3 minutes.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 3, "ingredient_refs": ["spinach, raw"]}], "title": "Cook"}], "make_ahead": "Great for meal prep; make up to 3 days ahead.", "cook_time_min": 13, "prep_time_min": 5, "total_time_min": 18, "yield_servings": 1}'::jsonb where id='32909e65-62b6-4c70-aeba-148816634ea8' and user_id is null;

-- Vegan Tofu Scramble
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat in a pan or microwave.", "storage": "Keeps up to 3 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Dice the onion and bell peppers and saute in olive oil until soft, about 4 minutes.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 4, "ingredient_refs": ["onions, raw", "bell peppers, raw", "olive oil"]}, {"n": 2, "temp": null, "text": "Crumble in the tofu and cook, stirring, about 5 minutes; season with cumin and nutritional yeast for a savory, egg-like flavor.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 5, "ingredient_refs": ["tofu, firm, raw", "cumin, ground", "nutritional yeast"]}, {"n": 3, "temp": null, "text": "Add the spinach and cook until wilted, about 2 minutes.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 2, "ingredient_refs": ["spinach, raw"]}], "title": "Cook"}], "make_ahead": "Great for meal prep; make up to 3 days ahead.", "cook_time_min": 11, "prep_time_min": 5, "total_time_min": 16, "yield_servings": 1}'::jsonb where id='d942160a-7614-42ec-8a2d-b774cae39aaf' and user_id is null;

commit;
