-- ============================================================================
-- seed-cooking-guides-breakfast-3.sql — authored cooking guides, BREAKFAST archetype (batch 3, 15 recipes)
-- ----------------------------------------------------------------------------
-- Git source of truth for content authored directly in the DB (instructions jsonb + recipe_kind
-- per recipe id). Content UPDATEs only — NOT schema. Idempotent (matches by id); re-runnable.
-- Same pattern + schema as the other seed-cooking-guides-*.sql files.
--
-- Regenerate from the live DB (swap the id-prefix filter for the batch):
--   select string_agg(format('-- %s', name) || E'\n' ||
--     format('update recipes set recipe_kind=%L, instructions=%L::jsonb where id=%L and user_id is null;',
--       recipe_kind, instructions::text, id::text), E'\n\n' order by name)
--   from recipes where user_id is null and instructions is not null and id::text like any(array['c215f022%', ...]);
--
-- Progress: 179 / 299 cooking guides authored (60%) — salads 26 + smoothies 6 + wraps 5 + soups 15 + bowls 77 + originals 5 + breakfast 45 (batches 1-3).
-- ============================================================================

begin;

-- Mediterranean Feta Tomato Scramble
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat gently; eggs are best fresh.", "storage": "Keeps up to 1 day refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Dice the tomatoes and saute in olive oil with the italian seasoning until softened, about 3 minutes.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 3, "ingredient_refs": ["tomatoes, raw", "olive oil", "italian seasoning"]}, {"n": 2, "temp": null, "text": "Whisk the eggs, pour in, and softly scramble; crumble in the feta and season with sea salt.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 5, "ingredient_refs": ["egg, whole, raw", "feta cheese", "sea salt"]}], "title": "Cook"}], "make_ahead": "Best cooked fresh.", "cook_time_min": 8, "prep_time_min": 4, "total_time_min": 12, "yield_servings": 1}'::jsonb where id='c215f022-e60a-4cc9-9975-e3ffafe1995a' and user_id is null;

-- Mediterranean Olive Omelette
update recipes set recipe_kind='cooked', instructions='{"reheat": "Serve fresh.", "storage": "Keeps up to 1 day refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Wilt the spinach and halved cherry tomatoes in olive oil, about 2 minutes.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 2, "ingredient_refs": ["spinach, raw", "tomatoes, cherry", "olive oil"]}, {"n": 2, "temp": null, "text": "Whisk the eggs, pour into the pan, and cook without stirring; when nearly set, crumble the feta over one half and fold into an omelette. Season with sea salt.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 6, "ingredient_refs": ["egg, whole, raw", "feta cheese", "sea salt"]}], "title": "Cook"}], "make_ahead": "Best cooked fresh.", "cook_time_min": 8, "prep_time_min": 5, "total_time_min": 13, "yield_servings": 1}'::jsonb where id='24074a10-0037-4afd-aa74-550a659fe495' and user_id is null;

-- Mediterranean Shakshuka Style Eggs
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat the sauce and poach fresh eggs.", "storage": "Store the sauce up to 3 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Dice the onion and bell peppers and saute in olive oil until soft, about 5 minutes; stir in the cumin and paprika.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 5, "ingredient_refs": ["onions, raw", "bell peppers, raw", "olive oil", "cumin, ground", "paprika"]}, {"n": 2, "temp": null, "text": "Add the diced tomatoes and simmer into a thick sauce, about 8 minutes; season with sea salt.", "type": "cook", "active": false, "appliance": "stovetop", "duration_min": 8, "ingredient_refs": ["tomato products, canned, diced", "sea salt"]}], "title": "Build the sauce"}, {"steps": [{"n": 3, "temp": null, "text": "Make wells in the sauce, crack in the eggs, cover, and cook until the whites set, about 6 minutes.", "type": "cook", "active": false, "appliance": "stovetop", "duration_min": 6, "ingredient_refs": ["egg, whole, raw"]}], "title": "Poach the eggs"}], "make_ahead": "Make the sauce up to 3 days ahead; poach the eggs fresh.", "cook_time_min": 19, "prep_time_min": 6, "total_time_min": 25, "yield_servings": 1}'::jsonb where id='3a3dd3f4-2808-4a8c-bc68-b51302f89245' and user_id is null;

-- Oatmeal with Banana and Whey
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat with a splash of milk.", "storage": "Keeps up to 2 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Simmer the rolled oats with the milk until creamy, about 6 minutes.", "type": "cook", "active": false, "appliance": "stovetop", "duration_min": 6, "ingredient_refs": ["rolled oats", "whole milk"]}, {"n": 2, "temp": null, "text": "Off the heat, stir in the whey protein until smooth and top with the sliced banana.", "type": "assemble", "active": true, "appliance": null, "duration_min": 2, "ingredient_refs": ["whey protein powder", "banana, raw"]}], "title": "Cook"}], "make_ahead": "Cook fresh, or make overnight oats and stir in protein before eating.", "cook_time_min": 7, "prep_time_min": 3, "total_time_min": 10, "yield_servings": 1}'::jsonb where id='0c8035b2-8174-49f9-88d8-c34f63b8e24b' and user_id is null;

-- Paleo Beef Veggie Breakfast Hash
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat in a pan or microwave.", "storage": "Keeps up to 3 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Cube the sweet potato and dice the onion; saute in olive oil over medium until the sweet potato is tender, about 12 minutes.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 12, "ingredient_refs": ["sweet potato, raw", "onions, raw", "olive oil"]}, {"n": 2, "temp": null, "text": "Add the ground beef and brown, breaking it up, about 7 minutes; season with sea salt and black pepper.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 7, "ingredient_refs": ["ground beef, 90% lean, raw", "sea salt", "black pepper, ground"]}, {"n": 3, "temp": null, "text": "Stir in the kale until wilted, about 3 minutes.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 3, "ingredient_refs": ["kale, raw"]}], "title": "Cook the hash"}], "make_ahead": "Great for meal prep; make up to 3 days ahead.", "cook_time_min": 22, "prep_time_min": 6, "total_time_min": 28, "yield_servings": 1}'::jsonb where id='2dc09098-0996-4cfc-8cbf-73cdef30049c' and user_id is null;

-- Paleo Egg and Asparagus Plate
update recipes set recipe_kind='cooked', instructions='{"reheat": "Serve fresh.", "storage": "Keeps up to 1 day refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Trim the asparagus and saute in olive oil until tender-crisp, about 6 minutes; season with sea salt and black pepper.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 6, "ingredient_refs": ["asparagus, raw", "olive oil", "sea salt", "black pepper, ground"]}, {"n": 2, "temp": null, "text": "Fry the eggs in the same pan and plate with the asparagus; finish with a squeeze of lemon juice.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 5, "ingredient_refs": ["egg, whole, raw", "lemon juice, raw"]}], "title": "Cook"}], "make_ahead": "Best cooked fresh.", "cook_time_min": 11, "prep_time_min": 4, "total_time_min": 15, "yield_servings": 1}'::jsonb where id='0a1a748f-a37d-4087-a9e9-4fa57afc68d5' and user_id is null;

-- Paleo Egg and Sweet Potato Hash
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat the hash; add fresh eggs.", "storage": "Keeps up to 3 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Cube the sweet potato, dice the onion and bell peppers; saute in olive oil with the paprika until the sweet potato is tender, about 13 minutes. Season with sea salt.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 13, "ingredient_refs": ["sweet potato, raw", "onions, raw", "bell peppers, raw", "olive oil", "paprika", "sea salt"]}, {"n": 2, "temp": null, "text": "Make wells, crack in the eggs, cover, and cook until the whites set, about 5 minutes.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 5, "ingredient_refs": ["egg, whole, raw"]}], "title": "Cook the hash"}], "make_ahead": "Make the hash ahead; add eggs fresh.", "cook_time_min": 18, "prep_time_min": 6, "total_time_min": 24, "yield_servings": 1}'::jsonb where id='a693e18b-bd52-470a-aacd-cfcfb458b701' and user_id is null;

-- Paleo Turkey Veggie Scramble
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat the base; add fresh eggs.", "storage": "Keeps up to 3 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Dice the onion and saute in olive oil until soft, about 3 minutes; add the ground turkey and brown, about 6 minutes.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 9, "ingredient_refs": ["onions, raw", "olive oil", "ground turkey, raw"]}, {"n": 2, "temp": null, "text": "Add the spinach to wilt, then whisk the eggs, pour in, and softly scramble; season with sea salt.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 3, "ingredient_refs": ["spinach, raw", "egg, whole, raw", "sea salt"]}], "title": "Cook"}], "make_ahead": "Cook the turkey base ahead; scramble eggs fresh.", "cook_time_min": 12, "prep_time_min": 4, "total_time_min": 16, "yield_servings": 1}'::jsonb where id='5c5ece35-b469-406b-a51c-bec1ef24b027' and user_id is null;

-- Pescatarian Cod Egg White Omelette
update recipes set recipe_kind='cooked', instructions='{"reheat": "Serve fresh.", "storage": "Keeps up to 1 day refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Season the cod and pan-sear in olive oil, about 3 minutes per side, until it flakes; break into pieces.", "type": "cook", "active": false, "appliance": "stovetop", "duration_min": 6, "ingredient_refs": ["cod, atlantic, raw", "olive oil"]}, {"n": 2, "temp": null, "text": "Wilt the spinach, then pour in the whisked eggs and cook into an omelette; fold the cod inside and season with sea salt and black pepper.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 5, "ingredient_refs": ["spinach, raw", "egg, whole, raw", "sea salt", "black pepper, ground"]}], "title": "Cook"}], "make_ahead": "Best cooked fresh.", "cook_time_min": 11, "prep_time_min": 4, "total_time_min": 15, "yield_servings": 1}'::jsonb where id='136590b1-2339-471c-bcbc-b502850c1d67' and user_id is null;

-- Pescatarian Mahi Mahi Breakfast Plate
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat the fish gently; add fresh eggs.", "storage": "Keeps up to 1 day refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Season the mahi-mahi and pan-sear in olive oil, about 4 minutes per side, until it flakes.", "type": "cook", "active": false, "appliance": "stovetop", "duration_min": 8, "ingredient_refs": ["mahi-mahi, raw", "olive oil"]}, {"n": 2, "temp": null, "text": "Fry the eggs in the same pan. Plate with the fish and sliced avocado and finish with lemon juice and sea salt.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 4, "ingredient_refs": ["egg, whole, raw", "avocado, raw", "lemon juice, raw", "sea salt"]}], "title": "Cook"}], "make_ahead": "Best cooked fresh.", "cook_time_min": 12, "prep_time_min": 4, "total_time_min": 16, "yield_servings": 1}'::jsonb where id='7b9b7781-8b12-418a-8627-92a4a57e7c36' and user_id is null;

-- Pescatarian Shrimp Egg Scramble
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat gently; eggs are best fresh.", "storage": "Keeps up to 1 day refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Mince the garlic and saute the shrimp in olive oil with the garlic until pink, about 3 minutes; remove and chop.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 4, "ingredient_refs": ["garlic, raw", "shrimp, raw", "olive oil"]}, {"n": 2, "temp": null, "text": "Wilt the spinach, pour in the whisked eggs, softly scramble, and fold the shrimp back in; season with sea salt.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 5, "ingredient_refs": ["spinach, raw", "egg, whole, raw", "sea salt"]}], "title": "Cook"}], "make_ahead": "Best cooked fresh.", "cook_time_min": 9, "prep_time_min": 4, "total_time_min": 13, "yield_servings": 1}'::jsonb where id='993dc525-e5a2-44de-8b4d-6b246894eb65' and user_id is null;

-- Pescatarian Tilapia Veggie Scramble
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat gently; eggs are best fresh.", "storage": "Keeps up to 1 day refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Season the tilapia and pan-sear in olive oil, about 3 minutes per side, until it flakes; break into pieces.", "type": "cook", "active": false, "appliance": "stovetop", "duration_min": 6, "ingredient_refs": ["tilapia, raw", "olive oil"]}, {"n": 2, "temp": null, "text": "Dice the bell peppers and saute briefly, add the spinach to wilt, then pour in the whisked eggs and softly scramble with the fish. Season with sea salt.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 5, "ingredient_refs": ["bell peppers, raw", "spinach, raw", "egg, whole, raw", "sea salt"]}], "title": "Cook"}], "make_ahead": "Best cooked fresh.", "cook_time_min": 11, "prep_time_min": 5, "total_time_min": 16, "yield_servings": 1}'::jsonb where id='8d81adc3-e091-499a-93d7-6df546d298aa' and user_id is null;

-- Protein Pancakes
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat in a toaster or pan.", "storage": "Keeps up to 2 days refrigerated or 1 month frozen.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Blend the banana, eggs, whey protein, rolled oats, and milk into a smooth batter.", "type": "prep", "active": true, "appliance": "blender", "duration_min": 4, "ingredient_refs": ["banana, raw", "egg, whole, raw", "whey protein powder", "rolled oats", "whole milk"]}, {"n": 2, "temp": null, "text": "Cook small pancakes in a lightly greased pan over medium, about 2 minutes per side, until golden.", "type": "cook", "active": false, "appliance": "stovetop", "duration_min": 10, "ingredient_refs": []}], "title": "Make the batter and cook"}], "make_ahead": "Batter can be made ahead; cook fresh. Cooked pancakes freeze well.", "cook_time_min": 10, "prep_time_min": 5, "total_time_min": 15, "yield_servings": 1}'::jsonb where id='ae872e24-049d-4b4d-93a6-c5e23d0a1f71' and user_id is null;

-- Scrambled Eggs with Spinach
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat gently; eggs are best fresh.", "storage": "Keeps up to 1 day refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Wilt the spinach in olive oil over medium, about 2 minutes.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 2, "ingredient_refs": ["spinach, raw", "olive oil"]}, {"n": 2, "temp": null, "text": "Whisk the eggs, pour in, and softly scramble; fold in the cheddar and season with salt.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 4, "ingredient_refs": ["egg, whole, raw", "cheddar cheese", "salt"]}], "title": "Cook"}], "make_ahead": "Best cooked fresh.", "cook_time_min": 6, "prep_time_min": 2, "total_time_min": 8, "yield_servings": 1}'::jsonb where id='0681c146-a73e-4023-ab96-9915b2aba805' and user_id is null;

-- Smoked Salmon Avocado Toast
update recipes set recipe_kind='cooked', instructions='{"reheat": "Serve fresh.", "storage": "Best eaten immediately.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Toast the bread and fry or poach the egg.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 6, "ingredient_refs": ["whole wheat bread", "egg, whole, raw"]}, {"n": 2, "temp": null, "text": "Mash the avocado onto the toast with lemon juice, drape over the smoked salmon, and top with the egg.", "type": "assemble", "active": true, "appliance": null, "duration_min": 3, "ingredient_refs": ["avocado, raw", "lemon juice, raw", "smoked salmon"]}], "title": "Cook and assemble"}], "make_ahead": "Best fresh so the toast stays crisp.", "cook_time_min": 6, "prep_time_min": 4, "total_time_min": 10, "yield_servings": 1}'::jsonb where id='d5401e44-5cdd-41d7-b502-d379431a928d' and user_id is null;

commit;
