-- ============================================================================
-- seed-cooking-guides-bowls-5.sql — authored cooking guides, BOWLS archetype (batch 5, FINAL, 17 recipes)
-- ----------------------------------------------------------------------------
-- Git source of truth for content authored directly in the DB (instructions jsonb + recipe_kind
-- per recipe id). Content UPDATEs only — NOT schema. Idempotent (matches by id); re-runnable.
-- Same pattern + schema as the other seed-cooking-guides-*.sql files.
--
-- FINAL bowls batch — completes the bowls archetype (77 total across bowls-1..5; 0 remain).
--
-- Regenerate from the live DB (swap the id-prefix filter for the batch):
--   select string_agg(format('-- %s', name) || E'\n' ||
--     format('update recipes set recipe_kind=%L, instructions=%L::jsonb where id=%L and user_id is null;',
--       recipe_kind, instructions::text, id::text), E'\n\n' order by name)
--   from recipes where user_id is null and id::text like any(array['abb7b7a8%', ...]);
--
-- Progress: 134 / 299 cooking guides authored (45%) — salads 26 + smoothies 6 + wraps 5 + soups 15 + bowls 77 (batches 1-5) + 5 originals.
-- ============================================================================

begin;

-- Vegan Black Bean Quinoa Lunch Bowl
update recipes set recipe_kind='assembly', instructions='{"reheat": "Serve cold or at room temperature.", "storage": "Keeps up to 3 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Add the quinoa and drained black beans to a bowl.", "type": "prep", "active": true, "appliance": null, "duration_min": 2, "ingredient_refs": ["quinoa, cooked", "black beans, canned, drained"]}, {"n": 2, "temp": null, "text": "Dice the avocado and halve the cherry tomatoes; add and season with cumin.", "type": "prep", "active": true, "appliance": null, "duration_min": 2, "ingredient_refs": ["avocado, raw", "tomatoes, cherry", "cumin, ground"]}, {"n": 3, "temp": null, "text": "Dress with olive oil and lemon juice and toss.", "type": "assemble", "active": true, "appliance": null, "duration_min": 2, "ingredient_refs": ["olive oil", "lemon juice, raw"]}], "title": "Assemble"}], "make_ahead": "Cook the quinoa ahead; great for meal prep.", "cook_time_min": 0, "prep_time_min": 6, "total_time_min": 6, "yield_servings": 1}'::jsonb where id='abb7b7a8-06e8-4b53-87f0-369c70e710fb' and user_id is null;

-- Vegan Black Bean Sweet Potato Bowl
update recipes set recipe_kind='cooked', instructions='{"reheat": "Microwave 2 minutes.", "storage": "Keeps up to 4 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": {"unit": "C", "value": 220}, "text": "Heat the oven to 220°C. Cube the sweet potato, toss with olive oil and cumin, and roast until tender, about 20 minutes.", "type": "cook", "active": false, "appliance": "oven", "duration_min": 20, "ingredient_refs": ["sweet potato, raw", "olive oil", "cumin, ground"]}], "title": "Roast"}, {"steps": [{"n": 2, "temp": null, "text": "Dice and saute the onion until soft, about 3 minutes, and warm the black beans.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 4, "ingredient_refs": ["onions, raw", "black beans, canned, drained"]}, {"n": 3, "temp": null, "text": "Build the bowl with the brown rice, sweet potato, beans, and onion, and top with salsa.", "type": "assemble", "active": true, "appliance": null, "duration_min": 2, "ingredient_refs": ["brown rice, cooked", "salsa, ready-to-serve"]}], "title": "Assemble"}], "make_ahead": "Great for meal prep; make up to 4 days ahead.", "cook_time_min": 24, "prep_time_min": 6, "total_time_min": 30, "yield_servings": 1}'::jsonb where id='84b9ba36-ad6c-4ae3-982e-47f2d0d8a3fb' and user_id is null;

-- Vegan Black Bean Sweet Potato Burrito Bowl
update recipes set recipe_kind='cooked', instructions='{"reheat": "Microwave 2 minutes.", "storage": "Keeps up to 4 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": {"unit": "C", "value": 220}, "text": "Heat the oven to 220°C. Cube the sweet potato, toss with olive oil, cumin, and sea salt, and roast until tender, about 20 minutes.", "type": "cook", "active": false, "appliance": "oven", "duration_min": 20, "ingredient_refs": ["sweet potato, raw", "olive oil", "cumin, ground", "sea salt"]}], "title": "Roast"}, {"steps": [{"n": 2, "temp": null, "text": "Warm the black beans, then build the bowl with the brown rice, sweet potato, and beans and top with salsa.", "type": "assemble", "active": true, "appliance": null, "duration_min": 4, "ingredient_refs": ["black beans, canned, drained", "brown rice, cooked", "salsa, ready-to-serve"]}], "title": "Assemble"}], "make_ahead": "Great for meal prep; make up to 4 days ahead.", "cook_time_min": 22, "prep_time_min": 6, "total_time_min": 28, "yield_servings": 1}'::jsonb where id='b2511e8d-569d-4668-ab5a-deafbfbc6cc1' and user_id is null;

-- Vegan Chickpea Quinoa Buddha Bowl
update recipes set recipe_kind='assembly', instructions='{"reheat": "Serve cold or at room temperature.", "storage": "Keeps up to 3 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Add the quinoa and drained chickpeas to a bowl with the spinach.", "type": "prep", "active": true, "appliance": null, "duration_min": 2, "ingredient_refs": ["quinoa, cooked", "chickpeas, mature seeds, canned, drained", "spinach, raw"]}, {"n": 2, "temp": null, "text": "Add the sliced avocado. Thin the tahini with lemon juice and a little water into a dressing.", "type": "prep", "active": true, "appliance": null, "duration_min": 2, "ingredient_refs": ["avocado, raw", "tahini", "lemon juice, raw"]}, {"n": 3, "temp": null, "text": "Drizzle the tahini dressing over and serve.", "type": "assemble", "active": true, "appliance": null, "duration_min": 2, "ingredient_refs": []}], "title": "Assemble"}], "make_ahead": "Cook the quinoa ahead; keep dressing separate.", "cook_time_min": 0, "prep_time_min": 6, "total_time_min": 6, "yield_servings": 1}'::jsonb where id='e8fcbf1f-eb2d-4897-9d6c-6e3cdb662c7a' and user_id is null;

-- Vegan Edamame Spinach Quinoa Bowl
update recipes set recipe_kind='assembly', instructions='{"reheat": "Serve cold or at room temperature.", "storage": "Keeps up to 3 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Add the quinoa and edamame to a bowl with the spinach.", "type": "prep", "active": true, "appliance": null, "duration_min": 3, "ingredient_refs": ["quinoa, cooked", "edamame, frozen, prepared", "spinach, raw"]}, {"n": 2, "temp": null, "text": "Add the sliced avocado and dress with sesame oil and soy sauce.", "type": "assemble", "active": true, "appliance": null, "duration_min": 3, "ingredient_refs": ["avocado, raw", "sesame oil", "soy sauce"]}], "title": "Assemble"}], "make_ahead": "Cook the quinoa and edamame ahead.", "cook_time_min": 0, "prep_time_min": 6, "total_time_min": 6, "yield_servings": 1}'::jsonb where id='488cf978-bcc5-4a3c-9da9-9c2c5e4f17fa' and user_id is null;

-- Vegan Edamame Tofu Rice Bowl
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat in a pan to re-crisp the tofu.", "storage": "Keeps up to 3 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Grate a little ginger. Cube the tofu and pan-fry in sesame oil with the ginger until golden, about 8 minutes; splash with soy sauce.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 10, "ingredient_refs": ["ginger root, raw", "tofu, firm, raw", "sesame oil", "soy sauce"]}], "title": "Cook the tofu"}, {"steps": [{"n": 2, "temp": null, "text": "Add the brown rice and edamame to a bowl and top with the tofu.", "type": "assemble", "active": true, "appliance": null, "duration_min": 2, "ingredient_refs": ["brown rice, cooked", "edamame, frozen, prepared"]}], "title": "Assemble"}], "make_ahead": "Cook the rice and edamame ahead; crisp the tofu fresh.", "cook_time_min": 10, "prep_time_min": 5, "total_time_min": 15, "yield_servings": 1}'::jsonb where id='d897d39e-86a7-451a-8cee-70beb65bc925' and user_id is null;

-- Vegan Kale Tahini Buddha Bowl
update recipes set recipe_kind='assembly', instructions='{"reheat": "Serve cold or at room temperature.", "storage": "Keeps up to 3 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Mince the garlic. Massage the kale with olive oil, lemon juice, and the garlic until softened.", "type": "prep", "active": true, "appliance": null, "duration_min": 3, "ingredient_refs": ["garlic, raw", "kale, raw", "olive oil", "lemon juice, raw"]}, {"n": 2, "temp": null, "text": "Add the quinoa and drained chickpeas to the bowl.", "type": "prep", "active": true, "appliance": null, "duration_min": 2, "ingredient_refs": ["quinoa, cooked", "chickpeas, mature seeds, canned, drained"]}, {"n": 3, "temp": null, "text": "Thin the tahini with a little water and drizzle over.", "type": "assemble", "active": true, "appliance": null, "duration_min": 2, "ingredient_refs": ["tahini"]}], "title": "Assemble"}], "make_ahead": "Cook the quinoa ahead; keeps well once massaged.", "cook_time_min": 0, "prep_time_min": 7, "total_time_min": 7, "yield_servings": 1}'::jsonb where id='c01d0803-ffcd-4ecd-af82-f39c4427dafa' and user_id is null;

-- Vegan Kidney Bean Veggie Bowl
update recipes set recipe_kind='assembly', instructions='{"reheat": "Serve cold or at room temperature.", "storage": "Keeps up to 3 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Mince the garlic. Massage the kale with olive oil, lemon juice, garlic, and sea salt until softened.", "type": "prep", "active": true, "appliance": null, "duration_min": 4, "ingredient_refs": ["garlic, raw", "kale, raw", "olive oil", "lemon juice, raw", "sea salt"]}, {"n": 2, "temp": null, "text": "Add the brown rice and drained kidney beans to the bowl and toss.", "type": "assemble", "active": true, "appliance": null, "duration_min": 3, "ingredient_refs": ["brown rice, cooked", "kidney beans, canned, drained"]}], "title": "Assemble"}], "make_ahead": "Cook the rice ahead; great for meal prep.", "cook_time_min": 0, "prep_time_min": 7, "total_time_min": 7, "yield_servings": 1}'::jsonb where id='5b77241d-2b36-420e-b9e2-f297ffa57ee3' and user_id is null;

-- Vegan Lentil and Quinoa Bowl
update recipes set recipe_kind='assembly', instructions='{"reheat": "Serve cold or at room temperature.", "storage": "Keeps up to 3 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Add the cooked lentils and quinoa to a bowl with the spinach.", "type": "prep", "active": true, "appliance": null, "duration_min": 2, "ingredient_refs": ["lentils, mature seeds, cooked, boiled", "quinoa, cooked", "spinach, raw"]}, {"n": 2, "temp": null, "text": "Dice the tomatoes and add; season with cumin.", "type": "prep", "active": true, "appliance": null, "duration_min": 2, "ingredient_refs": ["tomatoes, raw", "cumin, ground"]}, {"n": 3, "temp": null, "text": "Dress with olive oil and lemon juice and toss.", "type": "assemble", "active": true, "appliance": null, "duration_min": 2, "ingredient_refs": ["olive oil", "lemon juice, raw"]}], "title": "Assemble"}], "make_ahead": "Cook the lentils and quinoa ahead; great for meal prep.", "cook_time_min": 0, "prep_time_min": 6, "total_time_min": 6, "yield_servings": 1}'::jsonb where id='15db70d9-bc9c-4af7-8909-145101905184' and user_id is null;

-- Vegan Lentil Avocado Power Bowl
update recipes set recipe_kind='assembly', instructions='{"reheat": "Serve cold or at room temperature.", "storage": "Keeps up to 3 days refrigerated; add avocado fresh.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Add the cooked lentils to a bowl with the spinach.", "type": "prep", "active": true, "appliance": null, "duration_min": 2, "ingredient_refs": ["lentils, mature seeds, cooked, boiled", "spinach, raw"]}, {"n": 2, "temp": null, "text": "Dice the avocado and halve the cherry tomatoes; add and season with cumin.", "type": "prep", "active": true, "appliance": null, "duration_min": 2, "ingredient_refs": ["avocado, raw", "tomatoes, cherry", "cumin, ground"]}, {"n": 3, "temp": null, "text": "Dress with olive oil and lemon juice and toss.", "type": "assemble", "active": true, "appliance": null, "duration_min": 2, "ingredient_refs": ["olive oil", "lemon juice, raw"]}], "title": "Assemble"}], "make_ahead": "Cook the lentils ahead; great for meal prep.", "cook_time_min": 0, "prep_time_min": 6, "total_time_min": 6, "yield_servings": 1}'::jsonb where id='bbae0d2b-0e04-419f-bd7f-b03c114b787a' and user_id is null;

-- Vegan Quinoa Breakfast Bowl
update recipes set recipe_kind='assembly', instructions='{"reheat": "Serve warm or cold.", "storage": "Keeps up to 3 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Warm the quinoa if you like and add to a bowl.", "type": "prep", "active": true, "appliance": null, "duration_min": 2, "ingredient_refs": ["quinoa, cooked"]}, {"n": 2, "temp": null, "text": "Swirl in the almond butter and maple syrup, top with blueberries and chia seeds, and dust with cinnamon.", "type": "assemble", "active": true, "appliance": null, "duration_min": 3, "ingredient_refs": ["almond butter", "maple syrup", "blueberries, raw", "chia seeds", "cinnamon, ground"]}], "title": "Assemble"}], "make_ahead": "Cook the quinoa ahead; assemble in minutes.", "cook_time_min": 0, "prep_time_min": 5, "total_time_min": 5, "yield_servings": 1}'::jsonb where id='482e2790-9b87-419b-8ece-91c00ff2c74e' and user_id is null;

-- Vegan Savory Oat Bowl with Spinach
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat with a splash of water.", "storage": "Keeps up to 1 day refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Simmer the rolled oats with water until creamy, about 6 minutes.", "type": "cook", "active": false, "appliance": "stovetop", "duration_min": 6, "ingredient_refs": ["rolled oats"]}, {"n": 2, "temp": null, "text": "Stir in the spinach until wilted, then fold in the nutritional yeast and olive oil; season with sea salt and black pepper.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 4, "ingredient_refs": ["spinach, raw", "nutritional yeast", "olive oil", "sea salt", "black pepper, ground"]}], "title": "Cook"}], "make_ahead": "Best fresh.", "cook_time_min": 10, "prep_time_min": 4, "total_time_min": 14, "yield_servings": 1}'::jsonb where id='fd473713-1556-40c1-bf9f-b7ae0b21ba8f' and user_id is null;

-- Vegan Tempeh Brown Rice Bowl
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat in a pan.", "storage": "Keeps up to 3 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Mince the garlic. Cube the tempeh and pan-fry in sesame oil with the garlic until golden, about 8 minutes; splash with soy sauce.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 8, "ingredient_refs": ["garlic, raw", "tempeh", "sesame oil", "soy sauce"]}, {"n": 2, "temp": null, "text": "Add the broccoli florets and stir-fry until tender-crisp, about 5 minutes.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 5, "ingredient_refs": ["broccoli, raw"]}], "title": "Cook"}, {"steps": [{"n": 3, "temp": null, "text": "Serve over the brown rice.", "type": "assemble", "active": true, "appliance": null, "duration_min": 1, "ingredient_refs": ["brown rice, cooked"]}], "title": "Assemble"}], "make_ahead": "Cook the rice ahead; stir-fry fresh.", "cook_time_min": 13, "prep_time_min": 5, "total_time_min": 18, "yield_servings": 1}'::jsonb where id='9e9b728a-a541-4659-b1fb-0bbcb4872279' and user_id is null;

-- Vegan Tempeh Buddha Bowl Tahini
update recipes set recipe_kind='cooked', instructions='{"reheat": "Serve cold or reheat the tempeh.", "storage": "Keeps up to 3 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Cube the tempeh and pan-fry in sesame oil until golden, about 8 minutes.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 8, "ingredient_refs": ["tempeh", "sesame oil"]}], "title": "Cook the tempeh"}, {"steps": [{"n": 2, "temp": null, "text": "Grate the carrot and massage the kale a little. Add the quinoa, kale, and carrot to a bowl with the tempeh.", "type": "prep", "active": true, "appliance": null, "duration_min": 3, "ingredient_refs": ["carrots, raw", "kale, raw", "quinoa, cooked"]}, {"n": 3, "temp": null, "text": "Thin the tahini with lemon juice and drizzle over.", "type": "assemble", "active": true, "appliance": null, "duration_min": 2, "ingredient_refs": ["tahini", "lemon juice, raw"]}], "title": "Assemble"}], "make_ahead": "Cook the quinoa and tempeh ahead; keep dressing separate.", "cook_time_min": 10, "prep_time_min": 6, "total_time_min": 16, "yield_servings": 1}'::jsonb where id='6993cbcf-842b-4036-8cde-8adcc72efa91' and user_id is null;

-- Vegan Tempeh Stir Fry Bowl
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat in a pan.", "storage": "Keeps up to 3 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Grate the ginger and mince the garlic. Cube the tempeh and stir-fry in sesame oil with the ginger and garlic until golden, about 8 minutes.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 8, "ingredient_refs": ["ginger root, raw", "garlic, raw", "tempeh", "sesame oil"]}, {"n": 2, "temp": null, "text": "Add the broccoli and stir-fry until tender-crisp, about 5 minutes; splash with soy sauce.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 5, "ingredient_refs": ["broccoli, raw", "soy sauce"]}], "title": "Cook"}, {"steps": [{"n": 3, "temp": null, "text": "Serve over the brown rice.", "type": "assemble", "active": true, "appliance": null, "duration_min": 1, "ingredient_refs": ["brown rice, cooked"]}], "title": "Assemble"}], "make_ahead": "Cook the rice ahead; stir-fry fresh.", "cook_time_min": 13, "prep_time_min": 5, "total_time_min": 18, "yield_servings": 1}'::jsonb where id='46b9de19-4a64-4958-adfb-bee827f3a2ba' and user_id is null;

-- Vegan Tempeh Thai Peanut Bowl
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat in a pan with a splash of water.", "storage": "Keeps up to 3 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Grate the ginger. Cube the tempeh and stir-fry in sesame oil with the ginger until golden, about 8 minutes.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 8, "ingredient_refs": ["ginger root, raw", "tempeh", "sesame oil"]}, {"n": 2, "temp": null, "text": "Add the broccoli and stir-fry until tender-crisp, about 5 minutes.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 5, "ingredient_refs": ["broccoli, raw"]}], "title": "Cook"}, {"steps": [{"n": 3, "temp": null, "text": "Whisk the peanut butter with soy sauce and a little warm water into a sauce, toss through, and serve over the brown rice.", "type": "assemble", "active": true, "appliance": null, "duration_min": 3, "ingredient_refs": ["peanut butter, smooth", "soy sauce", "brown rice, cooked"]}], "title": "Sauce and serve"}], "make_ahead": "Cook the rice ahead; make the sauce ahead too.", "cook_time_min": 13, "prep_time_min": 6, "total_time_min": 19, "yield_servings": 1}'::jsonb where id='0497f46b-03d3-4436-bcbf-50213289d49c' and user_id is null;

-- Vegan Tofu Peanut Rice Bowl
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat the tofu in a pan to re-crisp.", "storage": "Keeps up to 3 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Grate the ginger. Cube the tofu and pan-fry in sesame oil with the ginger until golden and crisp, about 8 minutes.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 8, "ingredient_refs": ["ginger root, raw", "tofu, firm, raw", "sesame oil"]}], "title": "Cook the tofu"}, {"steps": [{"n": 2, "temp": null, "text": "Whisk the peanut butter with soy sauce and a little warm water into a sauce. Add the brown rice and sliced cucumber to a bowl, top with the tofu, and drizzle with the sauce.", "type": "assemble", "active": true, "appliance": null, "duration_min": 4, "ingredient_refs": ["peanut butter, smooth", "soy sauce", "brown rice, cooked", "cucumber, raw"]}], "title": "Sauce and serve"}], "make_ahead": "Cook the rice ahead; crisp the tofu fresh.", "cook_time_min": 10, "prep_time_min": 6, "total_time_min": 16, "yield_servings": 1}'::jsonb where id='eadf69ad-58c8-4e45-a1d6-6769ada2922a' and user_id is null;

commit;
