-- ============================================================================
-- seed-cooking-guides-bowls-3.sql — authored cooking guides, BOWLS archetype (batch 3 of N, 15 recipes)
-- ----------------------------------------------------------------------------
-- Git source of truth for content authored directly in the DB (instructions jsonb + recipe_kind
-- per recipe id). Content UPDATEs only — NOT schema. Idempotent (matches by id); re-runnable.
-- Same pattern + schema as the other seed-cooking-guides-*.sql files.
--
-- Bowls are captured across numbered batches (bowls-1..N). This is batch 3; ~32 remain.
--
-- Regenerate from the live DB (swap the id-prefix filter for the batch):
--   select string_agg(format('-- %s', name) || E'\n' ||
--     format('update recipes set recipe_kind=%L, instructions=%L::jsonb where id=%L and user_id is null;',
--       recipe_kind, instructions::text, id::text), E'\n\n' order by name)
--   from recipes where user_id is null and id::text like any(array['e49fc091%', ...]);
--
-- Progress: 102 / 299 cooking guides authored (34%) — salads 26 + smoothies 6 + wraps 5 + soups 15 + bowls 45 (batches 1-3).
-- ============================================================================

begin;

-- Paleo Almond Coconut Breakfast Bowl
update recipes set recipe_kind='assembly', instructions='{"reheat": "Serve cold.", "storage": "Keeps up to 2 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Pour the coconut milk into a bowl and stir in the chia seeds.", "type": "prep", "active": true, "appliance": null, "duration_min": 2, "ingredient_refs": ["coconut milk", "chia seeds"]}, {"n": 2, "temp": null, "text": "Slice the banana and strawberries over the top, scatter with almonds, and dust with cinnamon.", "type": "assemble", "active": true, "appliance": null, "duration_min": 3, "ingredient_refs": ["banana, raw", "strawberries, raw", "almonds, raw", "cinnamon, ground"]}], "title": "Assemble"}], "make_ahead": "Let it sit 10 minutes so the chia thickens, or make overnight.", "cook_time_min": 0, "prep_time_min": 5, "total_time_min": 5, "yield_servings": 1}'::jsonb where id='e49fc091-1408-4409-8724-9c72dd89192b' and user_id is null;

-- Paleo Apple Almond Butter Bowl
update recipes set recipe_kind='assembly', instructions='{"reheat": "Serve cold.", "storage": "Keeps up to 1 day refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Core and dice the apple into a bowl.", "type": "prep", "active": true, "appliance": null, "duration_min": 2, "ingredient_refs": ["apples, raw"]}, {"n": 2, "temp": null, "text": "Swirl in the almond butter, scatter with walnuts, and dust with cinnamon.", "type": "assemble", "active": true, "appliance": null, "duration_min": 2, "ingredient_refs": ["almond butter", "walnuts, raw", "cinnamon, ground"]}], "title": "Assemble"}], "make_ahead": "Best fresh so the apple stays crisp.", "cook_time_min": 0, "prep_time_min": 4, "total_time_min": 4, "yield_servings": 1}'::jsonb where id='50cc0d57-8502-4238-a0fb-4229ab6ceef5' and user_id is null;

-- Paleo Chicken Butternut Squash Bowl
update recipes set recipe_kind='cooked', instructions='{"reheat": "Microwave 2 minutes or reheat in the oven.", "storage": "Keeps up to 3 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": {"unit": "C", "value": 220}, "text": "Heat the oven to 220°C. Cube the butternut squash, toss with olive oil, cinnamon, and sea salt, and roast 20 minutes.", "type": "cook", "active": false, "appliance": "oven", "duration_min": 20, "ingredient_refs": ["butternut squash, raw", "olive oil", "cinnamon, ground", "sea salt"]}], "title": "Roast"}, {"steps": [{"n": 2, "temp": null, "text": "Meanwhile, cook the diced chicken in a little olive oil over medium-high until done, about 8 minutes.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 8, "ingredient_refs": ["chicken breast, broilers or fryers, raw"]}, {"n": 3, "temp": null, "text": "Wilt the spinach in the pan, then combine everything in a bowl.", "type": "assemble", "active": true, "appliance": null, "duration_min": 2, "ingredient_refs": ["spinach, raw"]}], "title": "Cook the chicken"}], "make_ahead": "Great for meal prep; make up to 3 days ahead.", "cook_time_min": 25, "prep_time_min": 8, "total_time_min": 33, "yield_servings": 1}'::jsonb where id='233f6d83-9a23-4161-8a97-1549eb1214c6' and user_id is null;

-- Paleo Chicken Kale Sweet Potato Bowl
update recipes set recipe_kind='cooked', instructions='{"reheat": "Microwave 2 minutes.", "storage": "Keeps up to 3 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": {"unit": "C", "value": 220}, "text": "Heat the oven to 220°C. Cube the sweet potato, toss with olive oil and sea salt, and roast 20 minutes.", "type": "cook", "active": false, "appliance": "oven", "duration_min": 20, "ingredient_refs": ["sweet potato, raw", "olive oil", "sea salt"]}], "title": "Roast"}, {"steps": [{"n": 2, "temp": null, "text": "Cook the diced chicken in a little olive oil over medium-high until done, about 8 minutes.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 8, "ingredient_refs": ["chicken breast, broilers or fryers, raw"]}, {"n": 3, "temp": null, "text": "Massage the kale with lemon juice, then build the bowl with the sweet potato, chicken, and kale.", "type": "assemble", "active": true, "appliance": null, "duration_min": 2, "ingredient_refs": ["kale, raw", "lemon juice, raw"]}], "title": "Cook the chicken"}], "make_ahead": "Great for meal prep; make up to 3 days ahead.", "cook_time_min": 25, "prep_time_min": 8, "total_time_min": 33, "yield_servings": 1}'::jsonb where id='abd88dc5-b3f3-47b5-ac39-a6cd70f2a096' and user_id is null;

-- Paleo Chicken Sweet Potato Bowl
update recipes set recipe_kind='cooked', instructions='{"reheat": "Microwave 2 minutes.", "storage": "Keeps up to 3 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": {"unit": "C", "value": 220}, "text": "Heat the oven to 220°C. Cube the sweet potato, toss with olive oil, paprika, and sea salt, and roast 20 minutes.", "type": "cook", "active": false, "appliance": "oven", "duration_min": 20, "ingredient_refs": ["sweet potato, raw", "olive oil", "paprika", "sea salt"]}], "title": "Roast"}, {"steps": [{"n": 2, "temp": null, "text": "Cook the diced chicken in a little olive oil over medium-high until done, about 8 minutes; wilt in the spinach.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 8, "ingredient_refs": ["chicken breast, broilers or fryers, raw", "spinach, raw"]}, {"n": 3, "temp": null, "text": "Combine the sweet potato, chicken, and spinach in a bowl.", "type": "assemble", "active": true, "appliance": null, "duration_min": 2, "ingredient_refs": []}], "title": "Cook the chicken"}], "make_ahead": "Great for meal prep; make up to 3 days ahead.", "cook_time_min": 25, "prep_time_min": 8, "total_time_min": 33, "yield_servings": 1}'::jsonb where id='7266a04e-dcfc-4343-80fd-9eaae933e6f7' and user_id is null;

-- Paleo Ground Turkey Zucchini Bowl
update recipes set recipe_kind='cooked', instructions='{"reheat": "Microwave 2 minutes.", "storage": "Keeps up to 3 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Dice the onion and mince the garlic; saute in olive oil until soft, about 3 minutes.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 3, "ingredient_refs": ["onions, raw", "garlic, raw", "olive oil"]}, {"n": 2, "temp": null, "text": "Add the ground turkey and brown, breaking it up, about 7 minutes; stir in the italian seasoning and sea salt.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 7, "ingredient_refs": ["ground turkey, raw", "italian seasoning", "sea salt"]}, {"n": 3, "temp": null, "text": "Add the diced zucchini and cook until just tender, about 4 minutes.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 4, "ingredient_refs": ["zucchini, raw"]}], "title": "Cook"}], "make_ahead": "Great for meal prep; make up to 3 days ahead.", "cook_time_min": 14, "prep_time_min": 6, "total_time_min": 20, "yield_servings": 1}'::jsonb where id='864b5101-7fed-46b9-bf70-6851a5d7d94e' and user_id is null;

-- Paleo Primal Breakfast Bowl
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat the beef; add a fresh egg.", "storage": "Keeps up to 3 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Mince the garlic and saute in olive oil, then add the ground beef and brown, breaking it up, about 7 minutes.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 8, "ingredient_refs": ["garlic, raw", "olive oil", "ground beef, 90% lean, raw"]}, {"n": 2, "temp": null, "text": "Add the chopped kale and cook until wilted, about 3 minutes.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 3, "ingredient_refs": ["kale, raw"]}, {"n": 3, "temp": null, "text": "Fry the egg and set it on top of the beef and kale.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 2, "ingredient_refs": ["egg, whole, raw"]}], "title": "Cook"}], "make_ahead": "Cook the beef and kale up to 3 days ahead; fry the egg fresh.", "cook_time_min": 13, "prep_time_min": 5, "total_time_min": 18, "yield_servings": 1}'::jsonb where id='603105a0-da7b-40de-b19f-17c11f9d119f' and user_id is null;

-- Paleo Salmon Avocado Breakfast Bowl
update recipes set recipe_kind='cooked', instructions='{"reheat": "Serve cold or gently warm the salmon.", "storage": "Keeps up to 2 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Season the salmon with sea salt and pan-sear in a little olive oil, about 4 minutes per side, until it flakes.", "type": "cook", "active": false, "appliance": "stovetop", "duration_min": 10, "ingredient_refs": ["salmon, atlantic, farmed, raw", "sea salt", "olive oil"]}], "title": "Cook the salmon"}, {"steps": [{"n": 2, "temp": null, "text": "Add the mixed greens and sliced avocado to a bowl, top with the salmon, and dress with lemon juice.", "type": "assemble", "active": true, "appliance": null, "duration_min": 4, "ingredient_refs": ["mixed greens", "avocado, raw", "lemon juice, raw"]}], "title": "Assemble"}], "make_ahead": "Cook the salmon up to 2 days ahead.", "cook_time_min": 10, "prep_time_min": 4, "total_time_min": 14, "yield_servings": 1}'::jsonb where id='ba028c81-74c5-41d4-99a0-f4b202f1e4a7' and user_id is null;

-- Paleo Sweet Potato Turkey Bowl
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat in the oven or air fryer.", "storage": "Keeps up to 3 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Heat the oven to 220°C. Mince the garlic. Cube the sweet potato and cut the broccoli into florets; toss with olive oil, garlic, and paprika.", "type": "prep", "active": true, "appliance": null, "duration_min": 6, "ingredient_refs": ["garlic, raw", "sweet potato, raw", "broccoli, raw", "olive oil", "paprika"]}, {"n": 2, "temp": {"unit": "C", "value": 220}, "text": "Add the diced turkey to the tray and roast everything until cooked through and golden, about 25 minutes.", "type": "cook", "active": false, "appliance": "oven", "duration_min": 25, "ingredient_refs": ["turkey breast, raw"]}], "title": "Roast"}], "make_ahead": "Great for meal prep; make up to 3 days ahead.", "cook_time_min": 27, "prep_time_min": 8, "total_time_min": 35, "yield_servings": 1}'::jsonb where id='1e617db7-2e45-493a-8b20-e7b785e26f72' and user_id is null;

-- Paleo Turkey Meatball Veggie Bowl
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat gently and toss with fresh zucchini.", "storage": "Keeps up to 3 days refrigerated or 3 months frozen.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Mix the ground turkey with italian seasoning and sea salt and roll into small meatballs; brown in olive oil, about 8 minutes.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 10, "ingredient_refs": ["ground turkey, raw", "italian seasoning", "sea salt", "olive oil"]}], "title": "Cook the meatballs"}, {"steps": [{"n": 2, "temp": null, "text": "Dice the onion and add with the diced tomatoes; simmer the meatballs in the sauce 8 minutes.", "type": "cook", "active": false, "appliance": "stovetop", "duration_min": 8, "ingredient_refs": ["onions, raw", "tomato products, canned, diced"]}, {"n": 3, "temp": null, "text": "Spiralize or dice the zucchini and toss through the hot sauce to soften.", "type": "assemble", "active": true, "appliance": null, "duration_min": 2, "ingredient_refs": ["zucchini, raw"]}], "title": "Sauce and finish"}], "make_ahead": "Make the meatballs and sauce up to 3 days ahead.", "cook_time_min": 18, "prep_time_min": 6, "total_time_min": 24, "yield_servings": 1}'::jsonb where id='a0e5ed55-9e42-46ec-beeb-ee12878ebcc6' and user_id is null;

-- Paleo Turkey Veggie Roasted Bowl
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat in the oven or air fryer.", "storage": "Keeps up to 3 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Heat the oven to 220°C. Cube the sweet potato and cut the broccoli into florets; toss with olive oil, paprika, and sea salt.", "type": "prep", "active": true, "appliance": null, "duration_min": 6, "ingredient_refs": ["sweet potato, raw", "broccoli, raw", "olive oil", "paprika", "sea salt"]}, {"n": 2, "temp": {"unit": "C", "value": 220}, "text": "Add the diced turkey to the tray and roast until cooked through and golden, about 25 minutes.", "type": "cook", "active": false, "appliance": "oven", "duration_min": 25, "ingredient_refs": ["turkey breast, raw"]}], "title": "Roast"}], "make_ahead": "Great for meal prep; make up to 3 days ahead.", "cook_time_min": 27, "prep_time_min": 8, "total_time_min": 35, "yield_servings": 1}'::jsonb where id='f9b5a37d-afb5-4124-aa53-b229a8b7030e' and user_id is null;

-- Pescatarian Cod Sweet Potato Fishcake Bowl
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat in a pan or oven to keep them crisp.", "storage": "Keeps up to 2 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Boil the sweet potato until soft, about 10 minutes, and mash. Finely dice the onion.", "type": "cook", "active": false, "appliance": "stovetop", "duration_min": 10, "ingredient_refs": ["sweet potato, raw", "onions, raw"]}, {"n": 2, "temp": null, "text": "Flake the raw cod and mix with the mash, onion, paprika, sea salt, and lemon juice; form into cakes.", "type": "prep", "active": true, "appliance": null, "duration_min": 5, "ingredient_refs": ["cod, atlantic, raw", "paprika", "sea salt", "lemon juice, raw"]}], "title": "Make the fishcakes"}, {"steps": [{"n": 3, "temp": null, "text": "Pan-fry the fishcakes in olive oil, about 4 minutes per side, until golden and cooked through.", "type": "cook", "active": false, "appliance": "stovetop", "duration_min": 10, "ingredient_refs": ["olive oil"]}], "title": "Cook"}], "make_ahead": "Form the cakes up to 1 day ahead and fry fresh.", "cook_time_min": 20, "prep_time_min": 10, "total_time_min": 30, "yield_servings": 1}'::jsonb where id='a617ca16-5090-453c-8241-69e5866390dc' and user_id is null;

-- Pescatarian Cod Taco Bowl
update recipes set recipe_kind='cooked', instructions='{"reheat": "Serve the cod warm or cold.", "storage": "Keeps up to 1 day refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Season the cod and pan-sear in a little olive oil, about 3-4 minutes per side, until it flakes; break into chunks.", "type": "cook", "active": false, "appliance": "stovetop", "duration_min": 8, "ingredient_refs": ["cod, atlantic, raw", "olive oil"]}], "title": "Cook the cod"}, {"steps": [{"n": 2, "temp": null, "text": "Add the brown rice to a bowl, shred the cabbage over it, and add the sliced avocado and cod.", "type": "assemble", "active": true, "appliance": null, "duration_min": 3, "ingredient_refs": ["brown rice, cooked", "cabbage, raw", "avocado, raw"]}, {"n": 3, "temp": null, "text": "Top with salsa and a squeeze of lemon juice.", "type": "assemble", "active": true, "appliance": null, "duration_min": 2, "ingredient_refs": ["salsa, ready-to-serve", "lemon juice, raw"]}], "title": "Assemble"}], "make_ahead": "Cook the rice ahead; cook the cod fresh.", "cook_time_min": 10, "prep_time_min": 5, "total_time_min": 15, "yield_servings": 1}'::jsonb where id='7f1f3576-8262-464f-8bc5-c08e62438ffe' and user_id is null;

-- Pescatarian Mahi Mahi Veggie Bowl
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat gently so the fish does not dry out.", "storage": "Keeps up to 2 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Mince the garlic. Cut the broccoli into florets and steam or blanch until tender-crisp, about 5 minutes.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 5, "ingredient_refs": ["garlic, raw", "broccoli, raw"]}, {"n": 2, "temp": null, "text": "Season the mahi-mahi with sea salt and pan-sear in olive oil with the garlic, about 4 minutes per side, until it flakes.", "type": "cook", "active": false, "appliance": "stovetop", "duration_min": 10, "ingredient_refs": ["mahi-mahi, raw", "sea salt", "olive oil"]}], "title": "Cook"}, {"steps": [{"n": 3, "temp": null, "text": "Add the quinoa to a bowl with the broccoli and mahi-mahi and finish with lemon juice.", "type": "assemble", "active": true, "appliance": null, "duration_min": 2, "ingredient_refs": ["quinoa, cooked", "lemon juice, raw"]}], "title": "Assemble"}], "make_ahead": "Cook the quinoa ahead; cook the fish fresh.", "cook_time_min": 15, "prep_time_min": 5, "total_time_min": 20, "yield_servings": 1}'::jsonb where id='742bd863-ce06-4eef-96ff-98f04baf883b' and user_id is null;

-- Pescatarian Salmon Lentil Bowl
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat gently.", "storage": "Keeps up to 2 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Season the salmon with sea salt and pan-sear in a little olive oil, about 4 minutes per side, until it flakes.", "type": "cook", "active": false, "appliance": "stovetop", "duration_min": 10, "ingredient_refs": ["salmon, atlantic, farmed, raw", "sea salt", "olive oil"]}], "title": "Cook the salmon"}, {"steps": [{"n": 2, "temp": null, "text": "Warm the cooked lentils and wilt in the spinach, then add to a bowl and top with the salmon and a squeeze of lemon juice.", "type": "assemble", "active": true, "appliance": null, "duration_min": 4, "ingredient_refs": ["lentils, mature seeds, cooked, boiled", "spinach, raw", "lemon juice, raw"]}], "title": "Assemble"}], "make_ahead": "Cook the lentils ahead; cook the salmon fresh.", "cook_time_min": 10, "prep_time_min": 4, "total_time_min": 14, "yield_servings": 1}'::jsonb where id='7382aa9a-1215-438c-8c0c-ca46e255562b' and user_id is null;

commit;
