-- ============================================================================
-- seed-cooking-guides-bowls-2.sql — authored cooking guides, BOWLS archetype (batch 2 of N, 15 recipes)
-- ----------------------------------------------------------------------------
-- Git source of truth for content authored directly in the DB (instructions jsonb + recipe_kind
-- per recipe id). Content UPDATEs only — NOT schema. Idempotent (matches by id); re-runnable.
-- Same pattern + schema as the other seed-cooking-guides-*.sql files.
--
-- Bowls are captured across numbered batches (bowls-1, bowls-2, ...). This is batch 2; ~47 remain.
--
-- Regenerate from the live DB (swap the id-prefix filter for the batch):
--   select string_agg(format('-- %s', name) || E'\n' ||
--     format('update recipes set recipe_kind=%L, instructions=%L::jsonb where id=%L and user_id is null;',
--       recipe_kind, instructions::text, id::text), E'\n\n' order by name)
--   from recipes where user_id is null and id::text like any(array['e90a3e4e%', ...]);
--
-- Progress: 87 / 299 cooking guides authored (29%) — salads 26 + smoothies 6 + wraps 5 + soups 15 + bowls 30 (batches 1-2).
-- ============================================================================

begin;

-- Hemp Seed Protein Snack Bowl
update recipes set recipe_kind='assembly', instructions='{"reheat": "Serve cold.", "storage": "Keeps up to 2 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Pour the coconut milk into a bowl and stir in the hemp seeds and chia seeds.", "type": "prep", "active": true, "appliance": null, "duration_min": 2, "ingredient_refs": ["coconut milk", "hemp seeds, hulled", "chia seeds"]}, {"n": 2, "temp": null, "text": "Top with the strawberries and blueberries.", "type": "assemble", "active": true, "appliance": null, "duration_min": 2, "ingredient_refs": ["strawberries, raw", "blueberries, raw"]}], "title": "Assemble"}], "make_ahead": "Let it sit 10 minutes so the chia thickens, or make overnight.", "cook_time_min": 0, "prep_time_min": 4, "total_time_min": 4, "yield_servings": 1}'::jsonb where id='e90a3e4e-a822-4294-af41-111211dd2aab' and user_id is null;

-- High-Protein Cottage Cheese Bowl
update recipes set recipe_kind='assembly', instructions='{"reheat": "Serve cold.", "storage": "Keeps up to 2 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Spoon the cottage cheese into a bowl.", "type": "prep", "active": true, "appliance": null, "duration_min": 1, "ingredient_refs": ["cottage cheese, lowfat"]}, {"n": 2, "temp": null, "text": "Top with the blueberries, hemp seeds, and chia seeds.", "type": "assemble", "active": true, "appliance": null, "duration_min": 3, "ingredient_refs": ["blueberries, raw", "hemp seeds, hulled", "chia seeds"]}], "title": "Assemble"}], "make_ahead": "Assemble fresh or the night before.", "cook_time_min": 0, "prep_time_min": 4, "total_time_min": 4, "yield_servings": 1}'::jsonb where id='6ac42f8f-042f-4a3e-903b-a6e6d78ea779' and user_id is null;

-- Keto Avocado Bacon Breakfast Bowl
update recipes set recipe_kind='cooked', instructions='{"reheat": "Add a fresh egg when serving.", "storage": "Best fresh.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Fry the egg to your liking and warm the bacon in a pan.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 6, "ingredient_refs": ["egg, whole, raw", "bacon, cured, pan-fried"]}, {"n": 2, "temp": null, "text": "Slice the avocado into a bowl, add the egg and bacon, and season with sea salt and black pepper.", "type": "assemble", "active": true, "appliance": null, "duration_min": 3, "ingredient_refs": ["avocado, raw", "sea salt", "black pepper, ground"]}], "title": "Cook and assemble"}], "make_ahead": "Cook the bacon ahead; fry the egg and slice the avocado fresh.", "cook_time_min": 8, "prep_time_min": 3, "total_time_min": 11, "yield_servings": 1}'::jsonb where id='98256f38-e975-4e08-9235-109d1d21a30c' and user_id is null;

-- Keto Beef Zucchini Noodle Bowl
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat the sauce and toss with the noodles.", "storage": "Store the sauce up to 4 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Mince the garlic and brown the ground beef with it in olive oil, about 7 minutes; stir in the italian seasoning.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 7, "ingredient_refs": ["garlic, raw", "ground beef, 90% lean, raw", "olive oil", "italian seasoning"]}, {"n": 2, "temp": null, "text": "Add the diced tomatoes and simmer 6 minutes; season with sea salt.", "type": "cook", "active": false, "appliance": "stovetop", "duration_min": 6, "ingredient_refs": ["tomato products, canned, diced", "sea salt"]}], "title": "Cook the sauce"}, {"steps": [{"n": 3, "temp": null, "text": "Spiralize or julienne the zucchini into noodles and toss with the hot beef sauce to soften.", "type": "assemble", "active": true, "appliance": null, "duration_min": 3, "ingredient_refs": ["zucchini, raw"]}], "title": "Assemble"}], "make_ahead": "Make the sauce up to 4 days ahead; toss with fresh zucchini noodles when serving.", "cook_time_min": 16, "prep_time_min": 6, "total_time_min": 22, "yield_servings": 1}'::jsonb where id='34a216cd-c4af-4f51-b9cf-4fcd7d6336ab' and user_id is null;

-- Keto Cottage Cheese Flaxseed Bowl
update recipes set recipe_kind='assembly', instructions='{"reheat": "Serve cold.", "storage": "Keeps up to 2 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Spoon the cottage cheese into a bowl and stir in the ground flaxseed.", "type": "prep", "active": true, "appliance": null, "duration_min": 2, "ingredient_refs": ["cottage cheese, lowfat", "flaxseed, ground"]}, {"n": 2, "temp": null, "text": "Top with the walnuts and a dusting of cinnamon.", "type": "assemble", "active": true, "appliance": null, "duration_min": 2, "ingredient_refs": ["walnuts, raw", "cinnamon, ground"]}], "title": "Assemble"}], "make_ahead": "Assemble fresh or the night before.", "cook_time_min": 0, "prep_time_min": 4, "total_time_min": 4, "yield_servings": 1}'::jsonb where id='de1501c6-83ff-4365-81a9-429d74d5445b' and user_id is null;

-- Keto Ground Beef Cauliflower Bowl
update recipes set recipe_kind='cooked', instructions='{"reheat": "Microwave 2 minutes.", "storage": "Keeps up to 3 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Dice the onion and saute in olive oil until soft, about 3 minutes.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 3, "ingredient_refs": ["onions, raw", "olive oil"]}, {"n": 2, "temp": null, "text": "Add the ground beef and brown, breaking it up, about 7 minutes.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 7, "ingredient_refs": ["ground beef, 80% lean, raw"]}, {"n": 3, "temp": null, "text": "Pulse the cauliflower into rice, add to the pan, and cook until tender, about 5 minutes.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 5, "ingredient_refs": ["cauliflower, raw"]}], "title": "Cook"}, {"steps": [{"n": 4, "temp": null, "text": "Stir the cheddar through to melt and serve.", "type": "assemble", "active": true, "appliance": null, "duration_min": 1, "ingredient_refs": ["cheddar cheese"]}], "title": "Finish"}], "make_ahead": "Keeps well for meal prep; make up to 3 days ahead.", "cook_time_min": 15, "prep_time_min": 5, "total_time_min": 20, "yield_servings": 1}'::jsonb where id='16537d8a-9383-493a-9645-91bcf064399e' and user_id is null;

-- Keto Ground Beef Taco Lettuce Bowl
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat the beef before assembling.", "storage": "Store the beef up to 3 days refrigerated; assemble fresh.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Brown the ground beef in a pan over medium-high, breaking it up, about 7 minutes; stir in the cumin and sea salt.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 8, "ingredient_refs": ["ground beef, 90% lean, raw", "cumin, ground", "sea salt"]}], "title": "Cook the beef"}, {"steps": [{"n": 2, "temp": null, "text": "Chop the romaine into a bowl, add the beef, and top with sliced avocado, cheddar, and salsa.", "type": "assemble", "active": true, "appliance": null, "duration_min": 5, "ingredient_refs": ["romaine lettuce", "avocado, raw", "cheddar cheese", "salsa, ready-to-serve"]}], "title": "Assemble"}], "make_ahead": "Cook the beef up to 3 days ahead.", "cook_time_min": 9, "prep_time_min": 5, "total_time_min": 14, "yield_servings": 1}'::jsonb where id='c94fc103-794a-40e8-9eb2-7f354800599e' and user_id is null;

-- Keto Shrimp Cauliflower Rice Bowl
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat gently so the shrimp stay tender.", "storage": "Keeps up to 2 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Pulse the cauliflower into rice. Mince the garlic and saute in olive oil until fragrant, then add the cauliflower rice and cook until tender, about 6 minutes.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 8, "ingredient_refs": ["cauliflower, raw", "garlic, raw", "olive oil"]}, {"n": 2, "temp": null, "text": "Push the rice aside and saute the shrimp until pink, 2-3 minutes per side; season with sea salt and lemon juice.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 6, "ingredient_refs": ["shrimp, raw", "sea salt", "lemon juice, raw"]}], "title": "Cook"}], "make_ahead": "Best cooked fresh; cauliflower rice can be prepped ahead.", "cook_time_min": 12, "prep_time_min": 5, "total_time_min": 17, "yield_servings": 1}'::jsonb where id='c1fda6ab-4395-44d3-92d7-d5ea26bbf08e' and user_id is null;

-- Mediterranean Chicken Eggplant Bowl
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat gently on the stovetop or microwave.", "storage": "Keeps up to 3 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Dice the eggplant and mince the garlic; saute in olive oil until the eggplant softens, about 6 minutes.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 6, "ingredient_refs": ["eggplant, raw", "garlic, raw", "olive oil"]}, {"n": 2, "temp": null, "text": "Add the diced chicken and italian seasoning and cook until the chicken is done, about 8 minutes.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 8, "ingredient_refs": ["chicken breast, broilers or fryers, raw", "italian seasoning"]}, {"n": 3, "temp": null, "text": "Add the diced tomatoes and simmer 4 minutes; season with sea salt.", "type": "cook", "active": false, "appliance": "stovetop", "duration_min": 4, "ingredient_refs": ["tomato products, canned, diced", "sea salt"]}], "title": "Cook"}], "make_ahead": "Great for meal prep; make up to 3 days ahead.", "cook_time_min": 18, "prep_time_min": 6, "total_time_min": 24, "yield_servings": 1}'::jsonb where id='0fe8d5e6-b04e-4358-8b58-97bd6a6890c1' and user_id is null;

-- Mediterranean Chickpea Breakfast Bowl
update recipes set recipe_kind='assembly', instructions='{"reheat": "Serve cold or at room temperature.", "storage": "Keeps up to 2 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Drain the chickpeas and add to a bowl with the spinach.", "type": "prep", "active": true, "appliance": null, "duration_min": 2, "ingredient_refs": ["chickpeas, mature seeds, canned, drained", "spinach, raw"]}, {"n": 2, "temp": null, "text": "Halve the cherry tomatoes and add; season with cumin and sea salt.", "type": "prep", "active": true, "appliance": null, "duration_min": 3, "ingredient_refs": ["tomatoes, cherry", "cumin, ground", "sea salt"]}, {"n": 3, "temp": null, "text": "Dress with olive oil and lemon juice and toss.", "type": "assemble", "active": true, "appliance": null, "duration_min": 2, "ingredient_refs": ["olive oil", "lemon juice, raw"]}], "title": "Assemble"}], "make_ahead": "Keeps well; make up to 2 days ahead.", "cook_time_min": 0, "prep_time_min": 7, "total_time_min": 7, "yield_servings": 1}'::jsonb where id='3d23c3d5-6edb-4415-90b4-80dbe9ada32d' and user_id is null;

-- Mediterranean Falafel Hummus Bowl
update recipes set recipe_kind='assembly', instructions='{"reheat": "Serve cold.", "storage": "Keeps up to 2 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Drain the chickpeas and add to a bowl; spoon the hummus alongside.", "type": "prep", "active": true, "appliance": null, "duration_min": 2, "ingredient_refs": ["chickpeas, mature seeds, canned, drained", "hummus, commercial"]}, {"n": 2, "temp": null, "text": "Dice the cucumber and halve the cherry tomatoes; add to the bowl and dust the chickpeas with paprika.", "type": "prep", "active": true, "appliance": null, "duration_min": 3, "ingredient_refs": ["cucumber, raw", "tomatoes, cherry", "paprika"]}, {"n": 3, "temp": null, "text": "Drizzle with olive oil and lemon juice.", "type": "assemble", "active": true, "appliance": null, "duration_min": 1, "ingredient_refs": ["olive oil", "lemon juice, raw"]}], "title": "Assemble"}], "make_ahead": "Assemble fresh, or prep components ahead.", "cook_time_min": 0, "prep_time_min": 6, "total_time_min": 6, "yield_servings": 1}'::jsonb where id='5681a355-a703-4c53-ac7a-79f26301a0ae' and user_id is null;

-- Mediterranean Greek Veggie Bowl
update recipes set recipe_kind='assembly', instructions='{"reheat": "Serve cold or at room temperature.", "storage": "Keeps up to 3 days refrigerated; great for meal prep.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Add the cooked quinoa to a bowl.", "type": "prep", "active": true, "appliance": null, "duration_min": 1, "ingredient_refs": ["quinoa, cooked"]}, {"n": 2, "temp": null, "text": "Dice the cucumber and halve the cherry tomatoes; add with a spoonful of hummus.", "type": "prep", "active": true, "appliance": null, "duration_min": 3, "ingredient_refs": ["cucumber, raw", "tomatoes, cherry", "hummus, commercial"]}, {"n": 3, "temp": null, "text": "Drizzle with olive oil and lemon juice.", "type": "assemble", "active": true, "appliance": null, "duration_min": 2, "ingredient_refs": ["olive oil", "lemon juice, raw"]}], "title": "Assemble"}], "make_ahead": "Cook the quinoa up to 3 days ahead.", "cook_time_min": 0, "prep_time_min": 6, "total_time_min": 6, "yield_servings": 1}'::jsonb where id='74dfc11e-1db0-4b99-adaa-0da7f6a9b463' and user_id is null;

-- Mediterranean Tofu Roasted Vegetable Bowl
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat in the oven or air fryer to re-crisp.", "storage": "Keeps up to 3 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Heat the oven to 220°C. Cube the tofu, eggplant, and zucchini and halve the cherry tomatoes; toss with olive oil, italian seasoning, and sea salt.", "type": "prep", "active": true, "appliance": null, "duration_min": 8, "ingredient_refs": ["tofu, firm, raw", "eggplant, raw", "zucchini, raw", "tomatoes, cherry", "olive oil", "italian seasoning", "sea salt"]}, {"n": 2, "temp": {"unit": "C", "value": 220}, "text": "Spread on a tray and roast until golden and tender, about 25 minutes, turning once.", "type": "cook", "active": false, "appliance": "oven", "duration_min": 25, "ingredient_refs": []}], "title": "Roast"}], "make_ahead": "Roast up to 3 days ahead; excellent for meal prep.", "cook_time_min": 25, "prep_time_min": 8, "total_time_min": 33, "yield_servings": 1}'::jsonb where id='5c538d5a-a974-42a6-b1e6-555bdfacc52b' and user_id is null;

-- Mediterranean Yogurt Fruit Bowl
update recipes set recipe_kind='assembly', instructions='{"reheat": "Serve cold.", "storage": "Keeps up to 2 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Spoon the Greek yogurt into a bowl.", "type": "prep", "active": true, "appliance": null, "duration_min": 1, "ingredient_refs": ["greek yogurt, plain, whole milk"]}, {"n": 2, "temp": null, "text": "Top with the strawberries, blueberries, and walnuts, drizzle with honey, and dust with cinnamon.", "type": "assemble", "active": true, "appliance": null, "duration_min": 3, "ingredient_refs": ["strawberries, raw", "blueberries, raw", "walnuts, raw", "honey", "cinnamon, ground"]}], "title": "Assemble"}], "make_ahead": "Assemble fresh or the night before.", "cook_time_min": 0, "prep_time_min": 4, "total_time_min": 4, "yield_servings": 1}'::jsonb where id='12865774-53be-4b34-b704-2e3d343c6721' and user_id is null;

-- Paleo Almond Butter Banana Bowl
update recipes set recipe_kind='assembly', instructions='{"reheat": "Serve cold.", "storage": "Keeps up to 1 day refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Slice the banana into a bowl and pour over the coconut milk.", "type": "prep", "active": true, "appliance": null, "duration_min": 2, "ingredient_refs": ["banana, raw", "coconut milk"]}, {"n": 2, "temp": null, "text": "Swirl in the almond butter, top with blueberries and chia seeds, and dust with cinnamon.", "type": "assemble", "active": true, "appliance": null, "duration_min": 3, "ingredient_refs": ["almond butter", "blueberries, raw", "chia seeds", "cinnamon, ground"]}], "title": "Assemble"}], "make_ahead": "Best fresh; let the chia sit a few minutes to thicken.", "cook_time_min": 0, "prep_time_min": 5, "total_time_min": 5, "yield_servings": 1}'::jsonb where id='727d7173-0d28-45f1-a4fa-7a64adc8f05a' and user_id is null;

commit;
