-- ============================================================================
-- seed-cooking-guides-mains-2.sql — authored cooking guides, MAINS archetype (batch 2, 15 recipes)
-- ----------------------------------------------------------------------------
-- Git source of truth for content authored directly in the DB (instructions jsonb + recipe_kind
-- per recipe id). Content UPDATEs only — NOT schema. Idempotent (matches by id); re-runnable.
-- Same pattern + schema as the other seed-cooking-guides-*.sql files.
--
-- Regenerate from the live DB (swap the id-prefix filter for the batch):
--   select string_agg(format('-- %s', name) || E'\n' ||
--     format('update recipes set recipe_kind=%L, instructions=%L::jsonb where id=%L and user_id is null;',
--       recipe_kind, instructions::text, id::text), E'\n\n' order by name)
--   from recipes where user_id is null and instructions is not null and id::text like any(array['a6b611b6%', ...]);
--
-- Progress: 221 / 299 cooking guides authored (74%) — salads 26 + smoothies 6 + wraps 5 + soups 15 + bowls 77 + originals 5 + breakfast 57 + mains 30 (batches 1-2).
-- ============================================================================

begin;

-- Carnivore Pork Tenderloin Dinner
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat gently.", "storage": "Keeps up to 3 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Season the pork tenderloin with sea salt and black pepper.", "type": "prep", "active": true, "appliance": null, "duration_min": 2, "ingredient_refs": ["pork tenderloin, raw", "sea salt", "black pepper, ground"]}, {"n": 2, "temp": {"unit": "C", "value": 63}, "text": "Sear all over, then cook through over medium about 15 minutes (63°C internal). Swirl the heavy cream into the pan for a light sauce; rest 5 minutes and slice.", "type": "cook", "active": false, "appliance": "stovetop", "duration_min": 18, "ingredient_refs": ["heavy cream"]}], "title": "Cook"}], "make_ahead": "Cook up to 3 days ahead.", "cook_time_min": 20, "prep_time_min": 3, "total_time_min": 23, "yield_servings": 1}'::jsonb where id='a6b611b6-9055-45ee-977a-2ce7d69b6dcd' and user_id is null;

-- Carnivore Pork Tenderloin Slices
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat gently.", "storage": "Keeps up to 3 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Season the pork tenderloin with sea salt and black pepper.", "type": "prep", "active": true, "appliance": null, "duration_min": 2, "ingredient_refs": ["pork tenderloin, raw", "sea salt", "black pepper, ground"]}, {"n": 2, "temp": {"unit": "C", "value": 63}, "text": "Sear all over, then cook through over medium about 15 minutes (63°C internal); rest 5 minutes and slice. Serve with the heavy cream spooned over.", "type": "cook", "active": false, "appliance": "stovetop", "duration_min": 17, "ingredient_refs": ["heavy cream"]}], "title": "Cook"}], "make_ahead": "Cook up to 3 days ahead.", "cook_time_min": 19, "prep_time_min": 3, "total_time_min": 22, "yield_servings": 1}'::jsonb where id='0e195f49-939d-41be-a6d3-b8c7e6b8f197' and user_id is null;

-- Carnivore Ribeye Steak
update recipes set recipe_kind='cooked', instructions='{"reheat": "Serve cold or gently warmed.", "storage": "Keeps up to 3 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Crisp the bacon and set aside. Season the steak with sea salt and black pepper.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 4, "ingredient_refs": ["bacon, cured, pan-fried", "beef, sirloin steak, lean, raw", "sea salt", "black pepper, ground"]}, {"n": 2, "temp": null, "text": "Sear the steak in the bacon fat 3-4 minutes per side for medium, deglaze with a splash of beef broth, and rest 5 minutes. Plate with the bacon.", "type": "cook", "active": false, "appliance": "stovetop", "duration_min": 10, "ingredient_refs": ["beef broth"]}], "title": "Cook"}], "make_ahead": "Best cooked fresh.", "cook_time_min": 14, "prep_time_min": 3, "total_time_min": 17, "yield_servings": 1}'::jsonb where id='83bc19c8-f009-4148-9d4e-cb9ae607dc23' and user_id is null;

-- Carnivore Ribeye Strip Lunch Plate
update recipes set recipe_kind='cooked', instructions='{"reheat": "Serve cold or gently warmed.", "storage": "Keeps up to 3 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Season the steak with sea salt and black pepper.", "type": "prep", "active": true, "appliance": null, "duration_min": 2, "ingredient_refs": ["beef, sirloin steak, lean, raw", "sea salt", "black pepper, ground"]}, {"n": 2, "temp": null, "text": "Sear 3-4 minutes per side for medium, deglaze with a splash of beef broth, and rest 5 minutes before slicing.", "type": "cook", "active": false, "appliance": "stovetop", "duration_min": 10, "ingredient_refs": ["beef broth"]}], "title": "Cook"}], "make_ahead": "Best cooked fresh.", "cook_time_min": 12, "prep_time_min": 3, "total_time_min": 15, "yield_servings": 1}'::jsonb where id='ede3e71c-3393-48e6-abd0-35f9c4065079' and user_id is null;

-- Carnivore Ribeye with Bone Broth
update recipes set recipe_kind='cooked', instructions='{"reheat": "Serve cold or gently warmed.", "storage": "Keeps up to 3 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Season the steak with sea salt and black pepper.", "type": "prep", "active": true, "appliance": null, "duration_min": 2, "ingredient_refs": ["beef, sirloin steak, lean, raw", "sea salt", "black pepper, ground"]}, {"n": 2, "temp": null, "text": "Sear 3-4 minutes per side for medium; rest 5 minutes. Warm the beef broth and serve alongside as a bone-broth style jus.", "type": "cook", "active": false, "appliance": "stovetop", "duration_min": 10, "ingredient_refs": ["beef broth"]}], "title": "Cook"}], "make_ahead": "Best cooked fresh.", "cook_time_min": 12, "prep_time_min": 3, "total_time_min": 15, "yield_servings": 1}'::jsonb where id='3c2c7f8b-e79d-4e47-a5c7-3afea1b8f681' and user_id is null;

-- Carnivore Salmon Butter Dinner
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat gently so the fish does not dry out.", "storage": "Keeps up to 2 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Season the salmon with sea salt and black pepper.", "type": "prep", "active": true, "appliance": null, "duration_min": 2, "ingredient_refs": ["salmon, atlantic, farmed, raw", "sea salt", "black pepper, ground"]}, {"n": 2, "temp": null, "text": "Pan-sear in a little butter about 4 minutes per side until it flakes, then swirl the heavy cream into the pan for a light sauce and spoon over.", "type": "cook", "active": false, "appliance": "stovetop", "duration_min": 10, "ingredient_refs": ["heavy cream"]}], "title": "Cook"}], "make_ahead": "Best cooked fresh.", "cook_time_min": 10, "prep_time_min": 3, "total_time_min": 13, "yield_servings": 1}'::jsonb where id='1968f638-ca2b-49be-ba86-c85f1e4ef78e' and user_id is null;

-- Carnivore Shrimp Cream Dinner
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat gently so the shrimp stay tender.", "storage": "Keeps up to 1 day refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Pat the shrimp dry and season with sea salt and black pepper.", "type": "prep", "active": true, "appliance": null, "duration_min": 1, "ingredient_refs": ["shrimp, raw", "sea salt", "black pepper, ground"]}, {"n": 2, "temp": null, "text": "Saute in a little butter until pink, about 3 minutes, then swirl in the heavy cream and simmer to a light sauce, about 3 minutes.", "type": "cook", "active": false, "appliance": "stovetop", "duration_min": 6, "ingredient_refs": ["heavy cream"]}], "title": "Cook"}], "make_ahead": "Best cooked fresh.", "cook_time_min": 7, "prep_time_min": 3, "total_time_min": 10, "yield_servings": 1}'::jsonb where id='c11c1812-db08-4e8a-8deb-e01d5daad7b8' and user_id is null;

-- Carnivore Sirloin Ground Beef Mix
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat gently.", "storage": "Keeps up to 3 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Season the sirloin and form the ground beef into a patty; season both with sea salt and black pepper.", "type": "prep", "active": true, "appliance": null, "duration_min": 3, "ingredient_refs": ["beef, sirloin steak, lean, raw", "ground beef, 80% lean, raw", "sea salt", "black pepper, ground"]}, {"n": 2, "temp": null, "text": "Sear the steak 3-4 minutes per side and cook the patty alongside; deglaze with a splash of beef broth. Rest and slice the steak.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 12, "ingredient_refs": ["beef broth"]}], "title": "Cook"}], "make_ahead": "Best cooked fresh.", "cook_time_min": 12, "prep_time_min": 4, "total_time_min": 16, "yield_servings": 1}'::jsonb where id='b2da9d8c-70d0-4a2d-ad40-c86307c2d29c' and user_id is null;

-- Carnivore Sirloin Steak Strips
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat gently.", "storage": "Keeps up to 3 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Slice the sirloin into strips and season with sea salt and black pepper.", "type": "prep", "active": true, "appliance": null, "duration_min": 3, "ingredient_refs": ["beef, sirloin steak, lean, raw", "sea salt", "black pepper, ground"]}, {"n": 2, "temp": null, "text": "Sear the strips in a hot pan until browned, about 6 minutes, deglazing with a splash of beef broth.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 9, "ingredient_refs": ["beef broth"]}], "title": "Cook"}], "make_ahead": "Best cooked fresh; can be cooked up to 3 days ahead.", "cook_time_min": 9, "prep_time_min": 3, "total_time_min": 12, "yield_servings": 1}'::jsonb where id='38e5a6e8-55bd-43f4-b1a1-97b985314b94' and user_id is null;

-- Carnivore Smoked Salmon Bites
update recipes set recipe_kind='assembly', instructions='{"reheat": "Serve cold.", "storage": "Keeps up to 2 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Spread the cream cheese onto the slices of smoked salmon.", "type": "prep", "active": true, "appliance": null, "duration_min": 3, "ingredient_refs": ["cream cheese", "smoked salmon"]}, {"n": 2, "temp": null, "text": "Roll up into bites and season with sea salt and black pepper.", "type": "assemble", "active": true, "appliance": null, "duration_min": 3, "ingredient_refs": ["sea salt", "black pepper, ground"]}], "title": "Assemble"}], "make_ahead": "Assemble up to 1 day ahead.", "cook_time_min": 0, "prep_time_min": 6, "total_time_min": 6, "yield_servings": 1}'::jsonb where id='8a1d4e9d-2e6e-41f7-893d-1884adc01970' and user_id is null;

-- Carnivore Tuna Steak Plate
update recipes set recipe_kind='assembly', instructions='{"reheat": "Serve cold.", "storage": "Keeps up to 2 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Drain the tuna and mound onto a plate.", "type": "prep", "active": true, "appliance": null, "duration_min": 2, "ingredient_refs": ["tuna, canned in water, drained"]}, {"n": 2, "temp": null, "text": "Peel and halve the hard-boiled eggs, add to the plate, and season with sea salt and black pepper.", "type": "assemble", "active": true, "appliance": null, "duration_min": 3, "ingredient_refs": ["egg, whole, hard-boiled", "sea salt", "black pepper, ground"]}], "title": "Assemble"}], "make_ahead": "Boil the eggs ahead; assemble in minutes.", "cook_time_min": 0, "prep_time_min": 5, "total_time_min": 5, "yield_servings": 1}'::jsonb where id='6d98f1de-24ca-4b64-8427-5046f4ca5675' and user_id is null;

-- Carnivore Turkey Breast Dinner
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat gently with a splash of broth.", "storage": "Keeps up to 3 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Season the turkey breast with sea salt and black pepper.", "type": "prep", "active": true, "appliance": null, "duration_min": 2, "ingredient_refs": ["turkey breast, raw", "sea salt", "black pepper, ground"]}, {"n": 2, "temp": {"unit": "C", "value": 74}, "text": "Sear, then cook through over medium with a splash of chicken broth to keep it moist, about 16 minutes (74°C internal); rest and slice.", "type": "cook", "active": false, "appliance": "stovetop", "duration_min": 16, "ingredient_refs": ["chicken broth"]}], "title": "Cook"}], "make_ahead": "Cook up to 3 days ahead; great for meal prep.", "cook_time_min": 18, "prep_time_min": 3, "total_time_min": 21, "yield_servings": 1}'::jsonb where id='89cdb71f-b781-4d2a-a2ba-b1fa4b9334f7' and user_id is null;

-- Carnivore Turkey Breast Lunch Plate
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat gently with a splash of broth.", "storage": "Keeps up to 3 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Season the turkey breast with sea salt and black pepper.", "type": "prep", "active": true, "appliance": null, "duration_min": 2, "ingredient_refs": ["turkey breast, raw", "sea salt", "black pepper, ground"]}, {"n": 2, "temp": {"unit": "C", "value": 74}, "text": "Sear, then cook through over medium with a splash of chicken broth, about 16 minutes (74°C internal); rest and slice.", "type": "cook", "active": false, "appliance": "stovetop", "duration_min": 16, "ingredient_refs": ["chicken broth"]}], "title": "Cook"}], "make_ahead": "Cook up to 3 days ahead; great for meal prep.", "cook_time_min": 18, "prep_time_min": 3, "total_time_min": 21, "yield_servings": 1}'::jsonb where id='150bf659-0e11-4a50-b155-d36bc66bd6ac' and user_id is null;

-- Chicken Tikka Masala
update recipes set recipe_kind='cooked', instructions='{"reheat": "Reheat gently on the stovetop.", "storage": "Keeps up to 3 days refrigerated or 2 months frozen.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Dice the chicken and cook in olive oil over medium-high until browned, about 6 minutes; remove and set aside.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 6, "ingredient_refs": ["chicken breast, broilers or fryers, raw", "olive oil"]}], "title": "Marinate and sear"}, {"steps": [{"n": 2, "temp": null, "text": "Dice the onion and mince the garlic and ginger; saute until soft and fragrant, about 5 minutes.", "type": "cook", "active": true, "appliance": "stovetop", "duration_min": 5, "ingredient_refs": ["onions, raw", "garlic, raw", "ginger root, raw"]}, {"n": 3, "temp": null, "text": "Add the tomato puree and simmer 8 minutes, then stir in the heavy cream and return the chicken; simmer until the sauce is rich and the chicken is cooked through, about 10 minutes.", "type": "cook", "active": false, "appliance": "stovetop", "duration_min": 19, "ingredient_refs": ["tomato products, canned, puree", "heavy cream"]}], "title": "Make the sauce"}, {"steps": [{"n": 4, "temp": null, "text": "Serve over the brown rice.", "type": "assemble", "active": true, "appliance": null, "duration_min": 1, "ingredient_refs": ["brown rice, cooked"]}], "title": "Serve"}], "make_ahead": "Tastes even better the next day; make up to 3 days ahead.", "cook_time_min": 30, "prep_time_min": 10, "total_time_min": 40, "yield_servings": 1}'::jsonb where id='f594fafe-3680-444c-b0ab-1287656a2334' and user_id is null;

-- Cottage Cheese with Strawberries Hemp
update recipes set recipe_kind='assembly', instructions='{"reheat": "Serve cold.", "storage": "Keeps up to 2 days refrigerated.", "sections": [{"steps": [{"n": 1, "temp": null, "text": "Spoon the cottage cheese into a bowl.", "type": "prep", "active": true, "appliance": null, "duration_min": 1, "ingredient_refs": ["cottage cheese, lowfat"]}, {"n": 2, "temp": null, "text": "Top with the sliced strawberries and hemp seeds and drizzle with honey.", "type": "assemble", "active": true, "appliance": null, "duration_min": 3, "ingredient_refs": ["strawberries, raw", "hemp seeds, hulled", "honey"]}], "title": "Assemble"}], "make_ahead": "Assemble fresh or the night before.", "cook_time_min": 0, "prep_time_min": 4, "total_time_min": 4, "yield_servings": 1}'::jsonb where id='3a05b03c-b778-4a31-9746-d02331ccd30a' and user_id is null;

commit;
